PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB2xxmini_0
WHERE
  { ?USRPB2xxmini_0
              a                     SDR:USRPB2xxmini
    { ?Entity_0  RFDevice:isProducerOf  ?USRPB2xxmini_0
      { ?Entity_0  a                    RFDevice:StandoffJamming
        { ?Quantity_0  RFDevice:hasMaxSensedPower  ?Entity_0 }
        { ?Entity_0  a                    RFDevice:SpatialVolumeUnit }
        {   { ?Entity_0  a                    RFDevice:DoubleValue
              { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 = 1842717546 )
              }
            }
          UNION
            { ?Entity_0  a                    Nuvio:InformationContent }
        }
      }
    }
  }
