PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  sf:   <http://www.opengis.net/ont/sf#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB2xx_0
WHERE
  { ?USRPB2xx_0  a                  SDR:USRPB2xx
    { ?USRPB2xx_0  RFDevice:isProducerOf  ?Entity_0
      {   { ?Entity_0  a                    Nuvio:Entity ;
                      Nuvio:isExpressedBy   ?Entity_1
          }
        UNION
          {   { ?Entity_0  a                    sf:MultiSurface }
            UNION
              { ?Ratio_0  RFDevice:hasVoltage  ?Entity_0
                { ?Ratio_0  a                     RFDevice:Ratio }
              }
          }
      }
    }
  }
