PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  sf:   <http://www.opengis.net/ont/sf#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?GNURadio_0
WHERE
  { ?GNURadio_0  a                  SDR:GNURadio
    { ?Entity_0  RFDevice:hasProducer  ?GNURadio_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?InformationEntity_0
                  Nuvio:isExpressedBy   ?Entity_0
        OPTIONAL
          { ?Entity_0  a                    sf:MultiPolygon
            OPTIONAL
              { ObjectDescription:WeightUnit_instance12
                          Nuvio:hasUnitOfMeasure  ?Entity_0
                OPTIONAL
                  { ?Entity_0  a                    RFDevice:Velocity
                    { ?Var0  Nuvio:hasValue  ?Entity_0 }
                  }
              }
            { ?Entity_0  a                    Nuvio:Process .
              ?Artix7FPGA_0
                        RFDevice:hasTarget    ?Entity_0
              { ?Artix7FPGA_0
                          a                     SDR:Artix7FPGA
                { SDR:Xilinx  RFDevice:isProducerOf  ?Artix7FPGA_0 }
              }
            }
          }
        { ?InformationEntity_0
                    a                     Nuvio:InformationEntity .
          ?SpatialLinearUnit_0
                    Nuvio:expresses       ?InformationEntity_0
          { ?SpatialLinearUnit_0
                      a                     RFDevice:SpatialLinearUnit
          }
        }
      }
    }
  }
