PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { ?CrossEyeJamming_0
                RFDevice:supportsSpectrumSensing  ?JammingSystem_0
      { ?Entity_0  RFDevice:hasEffectiveRadiatedPower  ?CrossEyeJamming_0
        { ?Entity_0  a                    RFDevice:BistaticRadar
          { ?Entity_1  Nuvio:compositeOf  ?Entity_0 }
        }
      }
    }
  }
