PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>

SELECT DISTINCT  ?PulseDopplerRadar_0
WHERE
  { ?PulseDopplerRadar_0
              a                     RFDevice:PulseDopplerRadar
    OPTIONAL
      { ?Weight_0  RFDevice:hasHeight  ?PulseDopplerRadar_0
        { ?Weight_0  a                    RFDevice:Weight }
      }
  }
