PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Half_DuplexCommunicationsSystem_0
                RFDevice:supportsTuning  ?Var0
      { ?Var0  a                     Nuvio:Process
        { ?Var0  a                     Nuvio:Entity
          { ?Var0  a                     SDR:USRPX300
            OPTIONAL
              { ?Var0  a                     RFDevice:DRFMJamming
                OPTIONAL
                  { ?Var0  a                     RFDevice:DecimalValue
                    OPTIONAL
                      { ?Var0  Nuvio:hasDataValue  ?DataValue0
                        FILTER ( ?DataValue0 >= -33.79 )
                      }
                  }
              }
          }
        }
      }
    }
  }
