PREFIX  geosparql: <http://www.opengis.net/ont/geosparql#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?PulseRadar_0
                RFDevice:isProducerOf  ?Object_0
      { ?Object_0  a                    Nuvio:Object .
        ?DeceptiveCommunicationsJamming_0
                  Nuvio:participatesIn  ?Object_0
        { ?DeceptiveCommunicationsJamming_0
                    a                     RFDevice:DeceptiveCommunicationsJamming
          { ?Entity_0  Nuvio:hasProcessQuantity  ?DeceptiveCommunicationsJamming_0
            { ?Entity_0  a                    Nuvio:Entity
              { ?Sphere_0  geosparql:defaultGeometry  ?Entity_0
                { ?Sphere_0  a                    gml:Sphere }
                { ?Entity_0  a                    RFDevice:ElectricChargeUnit }
              }
            }
          }
        }
      }
    }
  }
