PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?Entity_0  Nuvio:aggregateOf  ?SurveillanceRadar_0
      {   { ?Entity_0  a                    Nuvio:Entity ;
                      Nuvio:isExpressedBy   ?Entity_0
          }
        UNION
          {   { ?Entity_0  a                    RFDevice:ElectronicWarfare }
            UNION
              { ?Entity_0  a                    RFDevice:IntegerValue }
            OPTIONAL
              { ?Entity_0  a                    Nuvio:Process .
                ObjectDescription:AntennaPolarization_instance6
                          Nuvio:hasProcessQuality  ?Entity_0
              }
            { ?Entity_0  a                    Nuvio:Object }
          }
      }
    }
  }
