PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX300_0
WHERE
  { ?USRPX300_0  a                  SDR:USRPX300
    { ?Entity_0  Nuvio:aggregateOf  ?USRPX300_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?InformationContent_0
                  Nuvio:expresses       ?Entity_0
        { ?Entity_0  a                    RFDevice:RadarModulation
          { ?Entity_0  a                    RFDevice:AngleUnit
            { ?Entity_0  a                    RFDevice:PositiveIntegerValue
              { ?Entity_0  RFDevice:hasDecimalValue  ?DataValue0
                FILTER ( ?DataValue0 = -34.14 )
              }
            }
          }
          { ?Entity_0  a                    Nuvio:Process }
        }
      }
    }
  }
