PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?MonostaticRadar_0
WHERE
  { ?MonostaticRadar_0
              a                     RFDevice:MonostaticRadar
    { ?Object_0  RFDevice:hasProducer  ?MonostaticRadar_0
      { ?Object_0  a                    Nuvio:Object .
        ?Entity_0  RFDevice:hasPolarization  ?Object_0
        { ?Entity_0  Nuvio:expresses  ?Value_0
          {   { ?Entity_0  a                    RFDevice:DigitalModulation }
            UNION
              { ?Entity_0  a                    Nuvio:Value
                { ?Entity_0  a                    RFDevice:PositiveDecimalValue
                  { ?Entity_0  RFDevice:hasFloatValue  ?DataValue0
                    FILTER ( ?DataValue0 != -93.6 )
                  }
                }
              }
            { ?Entity_0  a                    Nuvio:Quantity }
            OPTIONAL
              { ?Entity_0  a                    Nuvio:UnitOfMeasure
                { ?InformationContent_0
                            Nuvio:representedBy  ?Entity_0
                  { ?InformationEntity_0
                              Nuvio:representedBy  ?InformationContent_0
                  }
                }
              }
          }
        }
      }
    }
  }
