PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?CR_0
WHERE
  { ?CR_0  a                     SDR:CR
    OPTIONAL
      { ?Entity_0  RFDevice:isProducerOf  ?CR_0
        { ?Entity_0  Nuvio:expresses  ?Attribute_0
          OPTIONAL
            {   { ?Entity_0  a                    gml:AbstractGeometricPrimitive
                  { ?Entity_0  RFDevice:hasFloatValue  ?DataValue0
                    FILTER ( ! ( ?DataValue0 >= "-180"^^xsd:decimal ) )
                  }
                }
              UNION
                { ?Entity_0  a                    Nuvio:InformationEntity ;
                            Nuvio:informationSource  ?Var0
                  { ?Var0  a                     RFDevice:OnOffKeyingModulation
                    OPTIONAL
                      { ?Var0     a                     Nuvio:Value .
                        ?UnitOfMeasure_0
                                  Nuvio:hasUnitOfMeasure  ?Var0
                      }
                  }
                }
              OPTIONAL
                { ?Attribute_0  a                 Nuvio:Attribute }
            }
        }
      }
  }
