PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB210_0
WHERE
  { ?USRPB210_0  a                  SDR:USRPB210
    { ?Var0  RFDevice:hasCapability  ?USRPB210_0
      { ?Var0  RFDevice:supportsSpectrumSensing  ?Var0
        { ?Var0  Nuvio:hasPrecision  ?DataValue0
          FILTER ( ?DataValue0 <= 2099901355 )
          OPTIONAL
            { ?UnitOfMeasure_0
                        Nuvio:hasParticipant  ?Var0
              { ?UnitOfMeasure_0
                          a                     Nuvio:UnitOfMeasure
              }
            }
        }
        { ?Var0     a                     Nuvio:Process .
          ObjectDescription:CR_instance33
                    Nuvio:participatesIn  ?Var0
        }
      }
    }
  }
