PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE312_0
WHERE
  { ?USRPE312_0  a                  SDR:USRPE312
    { ?Var0  Nuvio:aggregateOf  ?USRPE312_0
      { ?Var0  a                     Nuvio:Entity
        { ?Var0  a                     RFDevice:FrequencyScanRateUnit
          { ?Var0  a                     RFDevice:ShortValue
            { ?Var0  Nuvio:hasPrecision  ?DataValue0
              FILTER ( ?DataValue0 = 177093600 )
            }
          }
        }
        { ?Var1  RFDevice:hasCapacity  ?Var0 }
      }
    }
  }
