PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB2xx_0
WHERE
  { ?USRPB2xx_0  a                  SDR:USRPB2xx
    { ?Var0  RFDevice:supportsSpectrumSensing  ?USRPB2xx_0
      {   { ?Var0  a                     Nuvio:Process ;
                   Nuvio:hasSubprocess   ?Jamming_0
            OPTIONAL
              {   { ?Jamming_0  a                   RFDevice:Jamming }
                UNION
                  { ObjectDescription:Power_instance14
                              RFDevice:hasMaxOutputPower  ?Jamming_0
                  }
              }
          }
        UNION
          { ?Var0  a                     RFDevice:Transceiving }
      }
    }
  }
