PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?Receiver_0  Nuvio:aggregateOf  ?PulseRadar_0
      { ?Receiver_0  a                  RFDevice:Receiver
        OPTIONAL
          { ?Object_0  Nuvio:compositeOf  ?Receiver_0
            { ?Object_0  Nuvio:participatesIn  ?Modulation_0
              OPTIONAL
                { ?Modulation_0
                            a                     RFDevice:Modulation
                }
            }
          }
      }
    }
  }
