PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CR_0
WHERE
  { ?CR_0  a                     SDR:CR
    { ?DirectConversionReceiver_0
                Nuvio:partOf  ?CR_0
      { ?DirectConversionReceiver_0
                  RFDevice:hasNoiseFigure  ?NoiseFigure_0
        {   { ?NoiseFigure_0
                        a                     RFDevice:NoiseFigure
            }
          UNION
            { ?Var0  Nuvio:hasValue  ?NoiseFigure_0
              {   { ?Var0  RFDevice:hasFloatValue  ?DataValue0
                    FILTER ( ?DataValue0 = -71.45 )
                  }
                UNION
                  { ?Var0  Nuvio:hasPrecision  ?DataValue1
                    FILTER ( ?DataValue1 < 1924974425 )
                  }
              }
            }
        }
      }
    }
  }
