PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?USRPN3xx_0
WHERE
  { ?USRPN3xx_0  a                  SDR:USRPN3xx
    { ?Entity_0  RFDevice:isProducerOf  ?USRPN3xx_0
      { ?Entity_0  a                    Nuvio:Entity
        OPTIONAL
          { ?Entity_0  a                    SDR:USRPB200-210
            OPTIONAL
              { ?Var0  Nuvio:aggregateOf  ?Entity_0 }
            OPTIONAL
              { ?Entity_0  a                    RFDevice:FeatureDetection
                { ?Entity_0  a                    RFDevice:InformationUnit }
                { ?Entity_0  a                    Nuvio:Situation .
                  ?ArcByCenterPoint_0
                            Nuvio:relevantIndividual  ?Entity_0
                  { ?ArcByCenterPoint_0
                              a                     gml:ArcByCenterPoint
                  }
                }
              }
          }
      }
    }
  }
