PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?Entity_0  RFDevice:hasProducer  ?SurveillanceRadar_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_0  a                    Nuvio:Situation
          {   { ?Entity_0  a                    RFDevice:PositiveDecimalValue }
            UNION
              { ?Entity_0  RFDevice:hasDecimalValue  ?DataValue0
                FILTER ( ?DataValue0 <= 73.02 )
              }
          }
          { ?Entity_0  a                    Nuvio:Attribute }
        }
      }
    }
  }
