PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?MonostaticRadar_0
WHERE
  { ?MonostaticRadar_0
              a                     RFDevice:MonostaticRadar
    { ?Entity_0  RFDevice:supportsSpectrumSensing  ?MonostaticRadar_0
      { ?Entity_1  Nuvio:isExpressedBy  ?Entity_0
        OPTIONAL
          {   {   { ?Entity_0  a                    RFDevice:FrequencyUnit }
                UNION
                  { ?Var0  Nuvio:hasValue  ?Entity_0
                    { ?Var0  RFDevice:hasPositiveIntegerValue  ?DataValue0
                      FILTER ( ?DataValue0 = -21.88 )
                    }
                  }
              }
            UNION
              { ?Entity_0  a                    Nuvio:Value .
                ?SpatialAreaUnit_0
                          Nuvio:hasUnitOfMeasure  ?Entity_0
                { ?Entity_0  Nuvio:hasPrecision  ?DataValue1
                  FILTER ( ?DataValue1 = 1895693771 )
                }
                { ?SpatialAreaUnit_0
                            a                     RFDevice:SpatialAreaUnit
                }
              }
          }
      }
    }
  }
