PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE313_0
WHERE
  { ?USRPE313_0  a                  SDR:USRPE313
    { ?Weight_0  RFDevice:hasHeight  ?USRPE313_0
      { ?Var0  Nuvio:hasValue  ?Weight_0
        { ?Var0  RFDevice:hasDecimalValue  ?DataValue0
          FILTER ( ! ( ?DataValue0 > "0.0"^^xsd:double ) )
        }
      }
    }
  }
