PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?Object_0  RFDevice:isProducerOf  ?ElectronicAttackSystem_0
      { ?Transceiving_0
                  RFDevice:supportsTuning  ?Object_0
      }
    }
  }
