PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB200_210_0
WHERE
  { ?USRPB200_210_0
              a                     SDR:USRPB200-210
    { ?Object_0  RFDevice:hasProducer  ?USRPB200_210_0
      { ?Object_0  a                    Nuvio:Object .
        ?InboundRangeGatePullOffJamming_0
                  RFDevice:supportsTransmitting  ?Object_0
        OPTIONAL
          { ?InboundRangeGatePullOffJamming_0
                      a                     RFDevice:InboundRangeGatePullOffJamming
          }
      }
    }
  }
