PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN200_0
WHERE
  { ?USRPN200_0  a                  SDR:USRPN200
    OPTIONAL
      { ?RadioComponent_0
                  Nuvio:compositeOf  ?USRPN200_0
        {   { ?RadioComponent_0
                        a                     RFDevice:RadioComponent
            }
          UNION
            { ?RadioComponent_0
                        RFDevice:hasProducer  ObjectDescription:Producer_instance530
            }
        }
      }
  }
