PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?PulseDopplerRadarModulation_0
                RFDevice:supportsJamming  ?PulseRadar_0
      { ?PulseDopplerRadarModulation_0
                  RFDevice:hasMaxOutputPower  ?Entity_0
        { ?Entity_0  a                    RFDevice:VelocityUnit
          { ?Entity_0  RFDevice:hasDecimalValue  ?DataValue0
            FILTER ( ?DataValue0 != 46.23 )
          }
          { ?Entity_0  a                    RFDevice:TimeInterval }
        }
      }
    }
  }
