PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX310_0
WHERE
  { ?USRPX310_0  a                  SDR:USRPX310
    OPTIONAL
      { ?Entity_0  RFDevice:hasMaxPowerConsumption  ?USRPX310_0
        { ?Entity_0  a                    Nuvio:Entity .
          ?Entity_2  Nuvio:isExpressedBy  ?Entity_0
          {   { ?Entity_0  a                    RFDevice:Submarine }
            UNION
              { ?Entity_1  RFDevice:supportsJamming  ?Entity_0 }
            { ?Entity_0  a                    Nuvio:Situation
              { ?Entity_0  a                    Nuvio:Value .
                RFDevice:Watt
                          Nuvio:hasUnitOfMeasure  ?Entity_0
              }
            }
          }
        }
      }
  }
