PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { ?RadioComponent_0
                Nuvio:aggregateOf  ?JammingSystem_0
      { ?Entity_0  RFDevice:isProducerOf  ?RadioComponent_0
        { ?Entity_0  a                    Nuvio:Entity
          { ?Entity_0  a                    SDR:XC6SLX150FPGA
            { ?Var0  RFDevice:hasProducer  ?Entity_0 }
            { ?Entity_0  a                    RFDevice:VelocityUnit }
            { ?Entity_0  Nuvio:hasDataValue  ?DataValue0
              FILTER ( ?DataValue0 > "-8.225409780518874"^^xsd:double )
            }
          }
        }
      }
    }
  }
