PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Entity_0  RFDevice:hasWeight  ?Half_DuplexCommunicationsSystem_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_0  a                    skos:ConceptScheme .
          ?Concept_0  skos:inScheme       ?Entity_0
          { ?Object_0  skos:semanticRelation  ?Concept_0
            { ?Object_0  a                    Nuvio:Object .
              ?Entity_0  RFDevice:hasPolarization  ?Object_0
            }
          }
          OPTIONAL
            { ?Entity_0  RFDevice:hasDoubleValue  ?DataValue0
              FILTER ( ! ( ?DataValue0 <= 1.57 ) )
            }
          { ?Var0  Nuvio:hasValue  ?Entity_0
            { ?Var0  RFDevice:hasDecimalValue  ?DataValue1
              FILTER ( ?DataValue1 > 3.2 )
            }
          }
          { ?Entity_0  RFDevice:hasPulseWidth  ObjectDescription:Frequency_instance311 }
        }
      }
    }
  }
