PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE310_0
WHERE
  { ?USRPE310_0  a                  SDR:USRPE310
    { ?Var0  Nuvio:aggregateOf  ?USRPE310_0
      { ?Var0  a                     RFDevice:LongitudeValueInDegree
        OPTIONAL
          { ?Var0  RFDevice:hasDecimalValue  ?DataValue0
            FILTER ( ?DataValue0 >= "-180"^^xsd:decimal )
          }
        { ?Var0  a                     RFDevice:Gain }
      }
    }
  }
