PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?GNURadio_0
WHERE
  { ?GNURadio_0  a                  SDR:GNURadio
    { ?Entity_0  Nuvio:aggregateOf  ?GNURadio_0
      {   { ?Entity_0  a                    Nuvio:Entity }
        UNION
          { ?Entity_0  a                    gml:GeometricComplex
            { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
              FILTER ( ?DataValue0 > 858337489 )
              { ?Entity_0  a                    Nuvio:InformationEntity .
                ?Var0     Nuvio:informationSource  ?Entity_0
              }
              { ?Entity_0  a                    Nuvio:Process }
            }
          }
      }
    }
  }
