PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Var0  RFDevice:supportsSpectrumSensing  ?Half_DuplexCommunicationsSystem_0
      { ?Var0  a                     RFDevice:FixedBandwidthSensing
        { ?Var0  a                     RFDevice:SelfProtectionJamming
          { ?Quantity_0  RFDevice:hasPulseWidth  ?Var0
            { ?Quantity_0  a                  Nuvio:Quantity }
          }
        }
        { ?Var0  a                     RFDevice:Transceiving }
      }
    }
  }
