PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?Jamming_0  RFDevice:supportsSpectrumSensing  ?ElectronicAttackSystem_0
      { ?Jamming_0  a                   RFDevice:Jamming }
    }
  }
