PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { ?BarrageJamming_0
                RFDevice:supportsJamming  ?JammingSystem_0
      { ?BarrageJamming_0
                  a                     RFDevice:BarrageJamming
        { ObjectDescription:Power_instance49
                    RFDevice:hasEffectiveRadiatedPower  ?BarrageJamming_0
        }
      }
    }
  }
