PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    { ?Object_0  RFDevice:hasProducer  ?Full_DuplexCommunicationsSystem_0
      {   { ?Object_0  a                    Nuvio:Object ;
                      RFDevice:hasHeight    ?Height_0
          }
        UNION
          { ?Height_0  a                    RFDevice:Height }
      }
    }
  }
