PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>

SELECT DISTINCT  ?MonostaticRadar_0
WHERE
  { ?MonostaticRadar_0
              a                     RFDevice:MonostaticRadar
    { ?Object_0  RFDevice:hasProducer  ?MonostaticRadar_0
      { ObjectDescription:Frequency_instance266
                  RFDevice:hasBeamwidth  ?Object_0
      }
    }
  }
