PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB200_0
WHERE
  { ?USRPB200_0  a                  SDR:USRPB200
    { ?USRPB200_0  Nuvio:compositeOf  ?XC6SLX75FPGA_0
      { ?XC6SLX75FPGA_0
                  RFDevice:hasProducer  ?Entity_0
        { ?Entity_0  a                    Nuvio:Entity
          { ?Entity_0  a                    RFDevice:ElectronicSupportSystem
            {   { ?Entity_0  a                    RFDevice:InformationUnit }
              UNION
                { ?Entity_0  a                    RFDevice:Distance }
              { ?Entity_0  a                    Nuvio:Value .
                ?AngleUnit_0  Nuvio:hasUnitOfMeasure  ?Entity_0
                { ?AngleUnit_0  a                 RFDevice:AngleUnit }
              }
            }
          }
        }
      }
    }
  }
