PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?BistaticRadar_0
WHERE
  { ?BistaticRadar_0
              a                     RFDevice:BistaticRadar
    { ?SuperheterodyneReceiver_0
                Nuvio:compositeOf  ?BistaticRadar_0
      { ?SuperheterodyneReceiver_0
                  a                     RFDevice:SuperheterodyneReceiver
        OPTIONAL
          { ?DAC_0  Nuvio:partOf  ?SuperheterodyneReceiver_0
            { ?DAC_0  a                     RFDevice:DAC
              { ObjectDescription:Producer_instance303
                          RFDevice:hasProducer  ?DAC_0
              }
            }
          }
      }
    }
  }
