PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Entity_0  RFDevice:hasCapability  ?Half_DuplexCommunicationsSystem_0
      { ?Entity_0  a                    Nuvio:Object .
        ?Entity_1  Nuvio:hasObjectQuality  ?Entity_0
        { ?Entity_0  a                    Nuvio:InformationContent .
          ?InformationEntity_0
                    Nuvio:representedBy   ?Entity_0
          {   { ?AmplitudeShiftKeyingModulation_0
                          Nuvio:isExpressedBy  ?InformationEntity_0
              }
            UNION
              { ?AmplitudeShiftKeyingModulation_0
                          a                     RFDevice:AmplitudeShiftKeyingModulation
              }
          }
        }
      }
    }
  }
