PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?USRPE3xx_0
WHERE
  { ?USRPE3xx_0  a                  SDR:USRPE3xx
    { ?Var0  RFDevice:supportsSpectrumSensing  ?USRPE3xx_0
      { ?Var0  a                     RFDevice:DeceptiveCommunicationsJamming
        OPTIONAL
          { ObjectDescription:Instance2905
                      RFDevice:hasPulseRepetitionInterval  ?Var0
          }
        { ?Var0  a                     RFDevice:Receiving
          OPTIONAL
            { ?QuantityRange_0
                        RFDevice:hasFrequencyAccuracy  ?Var0
              { ?QuantityRange_0
                          a                     RFDevice:QuantityRange
                OPTIONAL
                  { ?ElectricCharge_0
                              RFDevice:hasMin  ?QuantityRange_0
                    { ?ElectricCharge_0
                                a                     RFDevice:ElectricCharge
                    }
                  }
              }
            }
        }
      }
    }
  }
