PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN3xx_0
WHERE
  { ?USRPN3xx_0  a                  SDR:USRPN3xx
    { ?Entity_0  RFDevice:hasProducer  ?USRPN3xx_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_0  a                    RFDevice:FrequencyUnit
          { ?Entity_0  a                    RFDevice:Height
            { ?Var0  Nuvio:hasValue  ?Entity_0
              { ?Var0  a                     RFDevice:NonNegativeDecimalValue
                { ?Var0  RFDevice:hasNonNegativeIntegerValue  ?DataValue0
                  FILTER ( ?DataValue0 > 95.9 )
                }
              }
            }
          }
          { ?Situation_0  Nuvio:hasUnitOfMeasure  ?Entity_0
            OPTIONAL
              { ?Entity_0  Nuvio:hasPrecision  ?DataValue1
                FILTER ( ?DataValue1 <= 61076376 )
              }
          }
        }
      }
    }
  }
