PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    { ?Entity_0  RFDevice:supportsTransmitting  ?Full_DuplexCommunicationsSystem_0
      { ?Entity_0  a                    Nuvio:Entity
        { ObjectDescription:InstantaneousFrequencyMeasurementReceiver_instance157
                    Nuvio:partOf  ?Entity_0
          { ?Entity_0  a                    RFDevice:FrequencyScanRateUnit }
          { ?Entity_0  a                    Nuvio:InformationEntity
            { ?Entity_0  a                    RFDevice:TimeInterval }
          }
        }
      }
    }
  }
