PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?GNURadio_0
WHERE
  { ?GNURadio_0  a                  SDR:GNURadio
    { ?Var0  RFDevice:supportsTransmitting  ?GNURadio_0
      { ?Var0  a                     RFDevice:AdjustableBandwidthSensing
        OPTIONAL
          { ?Var0  a                     Nuvio:Entity
            { ?Var0  a                     Nuvio:Situation
              { ?CR_0  Nuvio:relevantIndividual  ?Var0
                { ?CR_0  a                     SDR:CR
                  { ?Object_0  RFDevice:hasProducer  ?CR_0
                    { ?Object_0  a                    Nuvio:Object .
                      ObjectDescription:AntennaPolarization_instance22
                                RFDevice:hasPolarization  ?Object_0
                    }
                  }
                }
              }
              { ?Var0  a                     RFDevice:Width }
            }
          }
      }
    }
  }
