PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB205mini_i_0
WHERE
  { ?USRPB205mini_i_0
              a                     SDR:USRPB205mini-i
    { ?XC6SLX150FPGA_0
                Nuvio:compositeOf  ?USRPB205mini_i_0
      { ?XC6SLX150FPGA_0
                  a                     SDR:XC6SLX150FPGA
        { ObjectDescription:Producer_instance1321
                    RFDevice:hasProducer  ?XC6SLX150FPGA_0
        }
      }
    }
  }
