PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { ?CoverJamming_0
                RFDevice:supportsTransmitting  ?JammingSystem_0
      { ?CoverJamming_0
                  a                     RFDevice:CoverJamming
        { ?Power_0  Nuvio:hasProcessQuantity  ?CoverJamming_0
          { ?Power_0  a                     RFDevice:Power
            { ?Var0  Nuvio:hasValue  ?Power_0
              { ?PowerUnit_0  Nuvio:hasUnitOfMeasure  ?Var0
                { ?Var0  Nuvio:hasDataValue  ?DataValue0
                  FILTER ( ?DataValue0 >= 67.37 )
                }
              }
            }
          }
        }
      }
    }
  }
