PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarSystem_0
WHERE
  { ?RadarSystem_0
              a                     RFDevice:RadarSystem
    { ?Entity_0  Nuvio:aggregateOf  ?RadarSystem_0
      { ?InformationContent_0
                  Nuvio:isExpressedBy  ?Entity_0
        { ?Entity_0  a                    RFDevice:AmplitudeModulation
          { ?Entity_0  a                    RFDevice:FrequencyScanRateUnit
            { ?Entity_0  a                    Nuvio:UnitOfMeasure }
            { ?Entity_0  a                    Nuvio:Process ;
                        Nuvio:hasSubprocess   ?DeceptiveCommunicationsJamming_0
              { ?DeceptiveCommunicationsJamming_0
                          a                     RFDevice:DeceptiveCommunicationsJamming
                { ?Quantity_0  RFDevice:hasEffectiveRadiatedPower  ?DeceptiveCommunicationsJamming_0 }
              }
            }
          }
        }
        { ?InformationContent_0
                    a                     Nuvio:InformationContent .
          ?InformationEntity_0
                    Nuvio:represents      ?InformationContent_0
        }
      }
    }
  }
