PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?MonostaticRadar_0
WHERE
  { ?MonostaticRadar_0
              a                     RFDevice:MonostaticRadar
    { ?RadarJammer_0
                Nuvio:compositeOf  ?MonostaticRadar_0
      { ?Entity_0  RFDevice:hasFrequencyAccuracy  ?RadarJammer_0
        { ?Entity_0  a                    Nuvio:Entity ;
                    Nuvio:expresses       ?UnitOfMeasure_0
          { ?Entity_1  RFDevice:hasFrequencyRange  ?Entity_0
            { ?Entity_0  a                    RFDevice:SpatialAreaUnit }
            { ?Entity_0  a                    RFDevice:LatitudeValue
              OPTIONAL
                { ?Entity_0  a                    Nuvio:Situation }
            }
          }
        }
      }
    }
  }
