PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?Entity_0  RFDevice:isProducerOf  ?ElectronicAttackSystem_0
      {   { ?Entity_0  a                    Nuvio:Entity .
            ?UnitOfMeasure_0
                      Nuvio:isExpressedBy   ?Entity_0
          }
        UNION
          {   { ?Entity_0  a                    RFDevice:AngleModulation }
            UNION
              {   { ?FrequencyUnit_0
                              Nuvio:hasUnitOfMeasure  ?Entity_0
                  }
                UNION
                  { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                    FILTER ( ?DataValue0 != -449600355 )
                    { ?FrequencyUnit_0
                                a                     RFDevice:FrequencyUnit
                    }
                  }
              }
          }
      }
    }
  }
