PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB210_0
WHERE
  { ?USRPB210_0  a                  SDR:USRPB210
    { ?Entity_0  RFDevice:hasLevel  ?USRPB210_0
      { ?Entity_0  a                    RFDevice:DipoleAntenna
        OPTIONAL
          { ?Producer_0  RFDevice:isProducerOf  ?Entity_0
            { ?Producer_0  a                  RFDevice:Producer }
          }
        {   { ?Attribute_0  Nuvio:hasProcessQuality  ?Entity_0 }
          UNION
            { ?Attribute_0  a                 Nuvio:Attribute }
        }
        { ?Entity_0  a                    RFDevice:Percentage
          { ?Var0  Nuvio:hasValue  ?Entity_0
            { ?Var0  RFDevice:hasDecimalValue  ?DataValue0
              FILTER ( ?DataValue0 >= "0"^^xsd:decimal )
              {   { ?Var0  a                     RFDevice:PositiveDecimalValue }
                UNION
                  { ?Var0  Nuvio:hasPrecision  ?DataValue1
                    FILTER ( ?DataValue1 != 1242729940 )
                  }
              }
            }
          }
          { ?Entity_0  a                    Nuvio:InformationContent .
            ?InformationRepresentation_0
                      Nuvio:represents      ?Entity_0
            { ?InformationEntity_0
                        Nuvio:representedBy  ?InformationRepresentation_0
            }
          }
        }
      }
    }
  }
