PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ModelX_0
WHERE
  { ?ModelX_0  a                    RFDevice:ModelX
    { ?ModelX_0  RFDevice:hasCapability  ?Entity_0
      { ?Entity_0  Nuvio:expresses  ?InformationRepresentation_0
        { ?Entity_0  a                    RFDevice:ParabolicDishAntenna
          {   { ?Entity_0  a                    RFDevice:IntValue }
            UNION
              { ?Entity_0  RFDevice:hasIntegerValue  ?DataValue0
                FILTER ( ?DataValue0 < -281897570 )
              }
          }
        }
        { ?InformationRepresentation_0
                    a                     Nuvio:InformationRepresentation
        }
      }
    }
  }
