PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE3xx_0
WHERE
  { ?USRPE3xx_0  a                  SDR:USRPE3xx
    OPTIONAL
      { ?Object_0  RFDevice:isDeployedOn  ?USRPE3xx_0
        { ?Object_0  a                    Nuvio:Object .
          ?NoiseFigure_0
                    Nuvio:hasObjectQuantity  ?Object_0
          OPTIONAL
            {   { ?NoiseFigure_0
                            a                     RFDevice:NoiseFigure
                }
              UNION
                { ?Var0  Nuvio:hasValue  ?NoiseFigure_0
                  { ?Var1  Nuvio:hasUnitOfMeasure  ?Var0
                    { ?Var0  a                     RFDevice:NonNegativeIntegerValue
                      OPTIONAL
                        { ?Var0  Nuvio:hasPrecision  ?DataValue0
                          FILTER ( ?DataValue0 > 167388938 )
                        }
                    }
                  }
                }
            }
        }
      }
  }
