PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE312_0
WHERE
  { ?USRPE312_0  a                  SDR:USRPE312
    { ?Var0  Nuvio:aggregateOf  ?USRPE312_0
      { ?Var0  a                     RFDevice:ADC
        { ?DirectionalAntenna_0
                    Nuvio:partOf  ?Var0
          { ?DipoleAntenna_0
                      Nuvio:aggregateOf  ?DirectionalAntenna_0
            { ?DipoleAntenna_0
                        a                     RFDevice:DipoleAntenna
              { ?Gain_0  RFDevice:hasLevel  ?DipoleAntenna_0
                { ?Gain_0  a                     RFDevice:Gain }
              }
            }
          }
        }
      }
    }
  }
