PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    OPTIONAL
      { ?JammingSystem_0
                  RFDevice:hasBeamwidth  ?Weight_0
        { ?Weight_0  a                    RFDevice:Weight }
      }
  }
