PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?SearchRadar_0
WHERE
  { ?SearchRadar_0
              a                     RFDevice:SearchRadar
    { ?Entity_0  Nuvio:partOf  ?SearchRadar_0
      {   { ?Entity_0  a                    Nuvio:Entity }
        UNION
          { ?Entity_0  a                    gml:CubicSpline
            { ?Entity_0  a                    Nuvio:Process .
              ?TimeInterval_0
                        RFDevice:hasPulseRepetitionFrequency  ?Entity_0
              OPTIONAL
                { ?TimeInterval_0
                            a                     RFDevice:TimeInterval
                }
              { ?Entity_0  a                    Nuvio:InformationEntity .
                ?Var0     Nuvio:informationSource  ?Entity_0
                {   { ?Var0  a                     RFDevice:MannedPlatform }
                  UNION
                    { ?DeceptiveCommunicationsJamming_0
                                RFDevice:supportsSpectrumSensing  ?Var0
                      { ?DeceptiveCommunicationsJamming_0
                                  a                     RFDevice:DeceptiveCommunicationsJamming
                        OPTIONAL
                          { ObjectDescription:Instance6128
                                      RFDevice:hasMaxOutputPower  ?DeceptiveCommunicationsJamming_0
                          }
                      }
                    }
                }
                {   { ?Entity_0  a                    Nuvio:Value ;
                                Nuvio:hasUnitOfMeasure  ?SpatialUnit_0
                      { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                        FILTER ( ?DataValue0 < -562066192 )
                      }
                    }
                  UNION
                    { ?SpatialUnit_0
                                a                     RFDevice:SpatialUnit
                    }
                }
              }
            }
          }
      }
    }
  }
