PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RFSystem_0
WHERE
  { ?RFSystem_0  a                  RFDevice:RFSystem
    { ?Entity_0  RFDevice:isDeployedOn  ?RFSystem_0
      { ?Entity_0  a                    Nuvio:Entity ;
                  Nuvio:isExpressedBy   ?Entity_0
        { ?Entity_0  a                    RFDevice:AutomaticGainControl
          OPTIONAL
            { ?Entity_0  Nuvio:hasProcessQuantity  ?Entity_1 }
          OPTIONAL
            { ?Entity_0  a                    RFDevice:VoltageUnit }
          { ?Entity_0  a                    RFDevice:TimeInterval
            { ?Entity_0  a                    Nuvio:Object }
          }
        }
      }
    }
  }
