PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE313_0
WHERE
  { ?USRPE313_0  a                  SDR:USRPE313
    { ?USRPE313_0  Nuvio:compositeOf  ?Object_0
      { ?Object_0  a                    Nuvio:Object .
        ?RadarJamming_0
                  Nuvio:participatesIn  ?Object_0
        { ?RFSystem_0  Nuvio:hasParticipant  ?RadarJamming_0
          { ?RFSystem_0  a                  RFDevice:RFSystem
            { ?IEDJammer_0  Nuvio:aggregateOf  ?RFSystem_0
              {   { ?IEDJammer_0  a                 RFDevice:IEDJammer }
                UNION
                  { ?RadarFrequencyBand_0
                              RFDevice:hasFrequencyRange  ?IEDJammer_0
                    { ?Height_0  RFDevice:hasMin  ?RadarFrequencyBand_0
                      { ?Var0  Nuvio:hasValue  ?Height_0 }
                    }
                  }
              }
            }
          }
        }
      }
    }
  }
