PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ContinuousWaveRadar_0
WHERE
  { ?ContinuousWaveRadar_0
              a                     RFDevice:ContinuousWaveRadar
    { ?Entity_0  RFDevice:hasCapability  ?ContinuousWaveRadar_0
      { ?Entity_0  a                    gml:ArcStringByBulge
        { ?Entity_0  a                    RFDevice:AmplitudeModulation }
        { ObjectDescription:USRPN200_instance38
                    Nuvio:relevantIndividual  ?Entity_0
          { ?CrossEyeJamming_0
                      Nuvio:relevantIndividual  ?Entity_0
            { ?CrossEyeJamming_0
                        RFDevice:hasMaxOutputPower  ?Attribute_0
              { ?Attribute_0  a                 Nuvio:Attribute }
            }
          }
        }
      }
    }
  }
