PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?BistaticRadar_0
WHERE
  { ?BistaticRadar_0
              a                     RFDevice:BistaticRadar
    { ?Object_0  Nuvio:compositeOf  ?BistaticRadar_0
      {   { ?Object_0  a                    Nuvio:Object .
            ?Attribute_0  Nuvio:hasObjectQuality  ?Object_0
          }
        UNION
          { ?Attribute_0  a                 Nuvio:Attribute }
      }
    }
  }
