PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?Object_0  Nuvio:compositeOf  ?PulseRadar_0
      { ?Object_0  a                    Nuvio:Object .
        ObjectDescription:Instance1772
                  Nuvio:participatesIn  ?Object_0
      }
    }
  }
