PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    OPTIONAL
      { ?Entity_0  Nuvio:compositeOf  ?ElectronicAttackSystem_0
        {   { ?Entity_0  a                    Nuvio:Process .
              ?TerrainBounceJamming_0
                        Nuvio:hasSubprocess   ?Entity_0
              OPTIONAL
                { ?Entity_0  a                    RFDevice:FixedBandwidthSensing }
            }
          UNION
            { ?Entity_0  a                    RFDevice:LongitudeValueInDegree
              { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 > -1310116501 )
              }
              { ?Entity_0  a                    Nuvio:InformationEntity .
                ?Var0     Nuvio:informationSource  ?Entity_0
                { ?Var0  a                     gml:Rectangle
                  OPTIONAL
                    { ?Var0  a                     Nuvio:Value ;
                             Nuvio:hasUnitOfMeasure  ?SpatialUnit_0
                    }
                }
              }
            }
        }
      }
  }
