PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB210_0
WHERE
  { ?USRPB210_0  a                  SDR:USRPB210
    { ?Spartan6FPGA_0
                Nuvio:compositeOf  ?USRPB210_0
      { ?Spartan6FPGA_0
                  a                     SDR:Spartan6FPGA
        { ?Entity_0  RFDevice:hasProducer  ?Spartan6FPGA_0
          {   { ?Attribute_0  Nuvio:expresses  ?Entity_0 }
            UNION
              {   { ?Entity_0  a                    Nuvio:Object }
                UNION
                  { ?Attribute_0  a                 Nuvio:Attribute }
              }
          }
        }
      }
    }
  }
