PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB205mini_i_0
WHERE
  { ?USRPB205mini_i_0
              a                     SDR:USRPB205mini-i
    { ?Var0  RFDevice:supportsTuning  ?USRPB205mini_i_0
      { ?Var0  a                     RFDevice:AdjustableBandwidthSensing
        { ?Var0  a                     Nuvio:Process }
        { ?Entity_0  RFDevice:hasPulseWidth  ?Var0
          {   { ?Entity_0  a                    Nuvio:Entity .
                ?InformationRepresentation_0
                          Nuvio:expresses       ?Entity_0
              }
            UNION
              {   { ?Entity_0  RFDevice:isDeployedOn  ?Object_0
                    { ?Object_0  a                    Nuvio:Object }
                  }
                UNION
                  { ?Entity_0  a                    RFDevice:CrossEyeJamming
                    { ?Power_0  RFDevice:hasPulseRepetitionInterval  ?Entity_0
                      { ?Power_0  a                     RFDevice:Power }
                    }
                  }
                OPTIONAL
                  { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                    FILTER ( ?DataValue0 > 1924989293 )
                  }
              }
            OPTIONAL
              { ?InformationRepresentation_0
                          a                     Nuvio:InformationRepresentation .
                ?InformationEntity_0
                          Nuvio:represents      ?InformationRepresentation_0
              }
          }
        }
      }
    }
  }
