PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?SurveillanceRadar_0
                Nuvio:compositeOf  ?Entity_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?Value_0  Nuvio:expresses       ?Entity_0
        {   { ?Entity_0  a                    Nuvio:Situation }
          UNION
            { ?Entity_0  a                    RFDevice:WeightUnit }
          { ?Entity_0  a                    Nuvio:Object .
            ?Attribute_0  RFDevice:hasPolarization  ?Entity_0
            OPTIONAL
              { ?Attribute_0  a                 Nuvio:Attribute }
          }
        }
        { ?SpatialAreaUnit_0
                    Nuvio:hasUnitOfMeasure  ?Value_0
        }
      }
    }
  }
