PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?TrackingRadar_0
WHERE
  { ?TrackingRadar_0
              a                     RFDevice:TrackingRadar
    { ?TrackingRadar_0
                RFDevice:hasCapability  ?Var0
      {   { ?Var0  a                     RFDevice:SpectrumSensing }
        UNION
          { ?Var0  a                     RFDevice:DeceptiveCommunicationsJamming }
        { ?Var0     a                     Nuvio:Process .
          ?DataSize_0  RFDevice:hasPulseRepetitionInterval  ?Var0
          { ?Var1  Nuvio:hasValue  ?DataSize_0 }
        }
      }
    }
  }
