PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?Object_0  Nuvio:compositeOf  ?ElectronicAttackSystem_0
      { ?Object_0  a                    Nuvio:Object .
        ?Ratio_0  RFDevice:hasHeight    ?Object_0
      }
    }
  }
