PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ModelX_0
WHERE
  { ?ModelX_0  a                    RFDevice:ModelX
    { ?Receiving_0  RFDevice:hasCapability  ?ModelX_0
      { ?Entity_0  RFDevice:hasBandwidthRange  ?Receiving_0
        { ?Entity_0  a                    Nuvio:Entity .
          ?Process_0  Nuvio:isExpressedBy  ?Entity_0
          OPTIONAL
            { ?Entity_0  a                    Nuvio:Situation }
          { ?Process_0  a                   Nuvio:Process ;
                      Nuvio:participatesIn  ?Cylinder_0
          }
        }
      }
    }
  }
