PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?GNURadio_0
WHERE
  { ?GNURadio_0  a                  SDR:GNURadio
    OPTIONAL
      { ?RadioComponent_0
                  Nuvio:compositeOf  ?GNURadio_0
        {   { ?RadioComponent_0
                        a                     RFDevice:RadioComponent
            }
          UNION
            { ?Object_0  RFDevice:isProducerOf  ?RadioComponent_0
              { ObjectDescription:Power_instance40
                          Nuvio:hasObjectQuantity  ?Object_0
              }
            }
        }
      }
  }
