PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX3xx_0
WHERE
  { ?USRPX3xx_0  a                  SDR:USRPX3xx
    { ?Entity_0  RFDevice:isProducerOf  ?USRPX3xx_0
      { ?InformationRepresentation_0
                  Nuvio:isExpressedBy  ?Entity_0
        { ?Entity_0  a                    gml:PolygonPatch
          OPTIONAL
            { ?Entity_0  a                    RFDevice:PositiveDecimalValue }
          { ?Entity_0  a                    Nuvio:Process }
        }
        { ?InformationRepresentation_0
                    a                     Nuvio:InformationRepresentation .
          ?InformationContent_0
                    Nuvio:representedBy   ?InformationRepresentation_0
          OPTIONAL
            { ?InformationContent_0
                        a                     Nuvio:InformationContent .
              ?Entity_1  Nuvio:represents     ?InformationContent_0
            }
        }
      }
    }
  }
