PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?Entity_0  RFDevice:supportsTransmitting  ?PulseRadar_0
      { ?Entity_0  a                    Nuvio:Entity
        OPTIONAL
          { ?Entity_0  a                    RFDevice:Producer
            { ?Entity_0  a                    RFDevice:PowerUnit
              { ?Entity_0  a                    RFDevice:Voltage }
            }
          }
      }
    }
  }
