PREFIX  sf:   <http://www.opengis.net/ont/sf#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?BistaticRadar_0
WHERE
  { ?BistaticRadar_0
              a                     RFDevice:BistaticRadar
    { ?Entity_0  RFDevice:isProducerOf  ?BistaticRadar_0
      { ?InformationContent_0
                  Nuvio:expresses  ?Entity_0
        { ?Entity_0  a                    RFDevice:Tuning
          { ?Curve_0  Nuvio:relevantIndividual  ?Entity_0
            OPTIONAL
              { ?Curve_0  a                     sf:Curve }
            OPTIONAL
              { ?Entity_0  a                    RFDevice:DataSize
                { ?Var0  Nuvio:hasValue  ?Entity_0
                  { ?Var0     a                     Nuvio:Value .
                    ObjectDescription:InformationUnit_instance0
                              Nuvio:hasUnitOfMeasure  ?Var0
                  }
                }
              }
          }
        }
      }
    }
  }
