PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?BistaticRadar_0
WHERE
  { ?BistaticRadar_0
              a                     RFDevice:BistaticRadar
    { ?Var0  RFDevice:hasCapability  ?BistaticRadar_0
      {   { ?Var0     a                     Nuvio:Entity .
            ?Situation_0  Nuvio:expresses   ?Var0
          }
        UNION
          {   { ?Var0  a                     SDR:XilinxFPGA
                { ?Var0  a                     RFDevice:WeightUnit
                  OPTIONAL
                    { ?Var0  a                     Nuvio:Quality }
                }
              }
            UNION
              { ?MultiCurve_0
                          Nuvio:relevantIndividual  ?Situation_0
                { ?ArcByCenterPoint_0
                            Nuvio:relevantIndividual  ?Situation_0
                }
              }
          }
        OPTIONAL
          { ?Attribute_0  RFDevice:hasPulseRepetitionFrequency  ?Var0
            { ?Attribute_0  a                 Nuvio:Attribute }
          }
      }
    }
  }
