PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN200_0
WHERE
  { ?USRPN200_0  a                  SDR:USRPN200
    { ?Weight_0  RFDevice:hasMaxPowerConsumption  ?USRPN200_0
      { ?Var0  Nuvio:hasValue  ?Weight_0
        { ?Var0     a                     Nuvio:Entity .
          ?Value_0  Nuvio:isExpressedBy   ?Var0
          { ?Value_0  a                     Nuvio:Value
            { ?Value_0  Nuvio:hasPrecision  ?DataValue0
              FILTER ( ?DataValue0 != 2048984507 )
            }
          }
          { ?Var0  RFDevice:hasDoubleValue  ?DataValue1 }
        }
      }
    }
  }
