PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CommunicationsSystem_0
WHERE
  { ?CommunicationsSystem_0
              a                     RFDevice:CommunicationsSystem
    { ?Entity_0  RFDevice:isProducerOf  ?CommunicationsSystem_0
      {   { ?Process_0  Nuvio:expresses  ?Entity_0 }
        UNION
          { ?Entity_0  a                    gml:MultiPoint
            { ?Entity_0  a                    Nuvio:Object }
            { ?Process_0  a                   Nuvio:Process }
          }
      }
    }
  }
