PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SearchRadar_0
WHERE
  { ?SearchRadar_0
              a                     RFDevice:SearchRadar
    { ?SearchRadar_0
                RFDevice:isProducerOf  ?Entity_0
      { ?Process_0  Nuvio:expresses  ?Entity_0
        { ?Entity_0  Nuvio:hasValue  ?Var0
          { ?UnitOfMeasure_0
                      Nuvio:hasUnitOfMeasure  ?Var0
            { ?UnitOfMeasure_0
                        a                     Nuvio:UnitOfMeasure
            }
            OPTIONAL
              { ?Var0  RFDevice:hasDecimalValue  ?DataValue0
                OPTIONAL
                  { ?Var0  a                     RFDevice:NonNegativeDecimalValue
                    { ?Var0  RFDevice:hasNonNegativeIntegerValue  ?DataValue1
                      FILTER ( ?DataValue1 >= "0"^^xsd:decimal )
                    }
                  }
              }
          }
        }
        {   { ?Process_0  a                   Nuvio:Process .
              ?Power_0  RFDevice:hasMaxSensedPower  ?Process_0
            }
          UNION
            { ?Power_0  Nuvio:hasValue  ?Var1 }
        }
      }
    }
  }
