PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    { ?Entity_0  Nuvio:hasObjectQuantity  ?Full_DuplexCommunicationsSystem_0
      { ?Entity_0  a                    Nuvio:Entity
        {   { ?Entity_0  a                    RFDevice:InformationUnit
              { ?Entity_0  a                    Nuvio:Attribute }
            }
          UNION
            {   { ?Entity_0  a                    Nuvio:Value }
              UNION
                { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                  FILTER ( ?DataValue0 < -638720125 )
                }
            }
        }
      }
    }
  }
