PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE3xx_0
WHERE
  { ?USRPE3xx_0  a                  SDR:USRPE3xx
    OPTIONAL
      { ?SuperheterodyneReceiver_0
                  Nuvio:aggregateOf  ?USRPE3xx_0
        { ?Component_0  Nuvio:aggregateOf  ?SuperheterodyneReceiver_0
          { ?Component_0  a                 RFDevice:Component }
        }
      }
  }
