PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB210_0
WHERE
  { ?USRPB210_0  a                  SDR:USRPB210
    { ?SuperheterodyneReceiver_0
                Nuvio:aggregateOf  ?USRPB210_0
    }
  }
