PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN310_0
WHERE
  { ?USRPN310_0  a                  SDR:USRPN310
    { ?USRPN310_0  Nuvio:compositeOf  ?Var0
      { ?Situation_0  RFDevice:supportsTuning  ?Var0
        OPTIONAL
          {   { ?Situation_0  a                 Nuvio:Situation .
                ?InverseGainJamming_0
                          Nuvio:relevantIndividual  ?Situation_0
              }
            UNION
              { ?InverseGainJamming_0
                          a                     RFDevice:InverseGainJamming
              }
          }
        { ?Var0  RFDevice:hasResolution  ?Var1 }
      }
    }
  }
