PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ModelX_0
WHERE
  { ?ModelX_0  a                    RFDevice:ModelX
    { ?Entity_0  RFDevice:hasLevel  ?ModelX_0
      {   {   { ?InformationContent_0
                          Nuvio:expresses  ?Entity_0
              }
            UNION
              { ?Entity_0  a                    RFDevice:PulseDopplerRadar
                { ?AmplitudeModulation_0
                            Nuvio:relevantIndividual  ?Entity_0
                  { ?SpatialAreaUnit_0
                              Nuvio:relevantIndividual  ?Entity_0
                    { ?SpatialAreaUnit_0
                                a                     RFDevice:SpatialAreaUnit
                    }
                  }
                  { ObjectDescription:FrequencyUnit_instance19
                              Nuvio:hasUnitOfMeasure  ?Entity_0
                    { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                      FILTER ( ?DataValue0 != 932858607 )
                    }
                  }
                }
              }
          }
        UNION
          { ?InformationContent_0
                      a                     Nuvio:InformationContent .
            ?Entity_1  Nuvio:representedBy  ?InformationContent_0
          }
      }
    }
  }
