PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>

SELECT DISTINCT  ?MonostaticRadar_0
WHERE
  { ?MonostaticRadar_0
              a                     RFDevice:MonostaticRadar
    OPTIONAL
      { ?MonostaticRadar_0
                  RFDevice:hasMaxPowerConsumption  ?Weight_0
        { ?Weight_0  a                    RFDevice:Weight }
      }
  }
