PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?Entity_0  Nuvio:hasObjectQuantity  ?SurveillanceRadar_0
      { ?Entity_0  a                    Nuvio:Entity
        OPTIONAL
          {   { ?Entity_0  a                    Nuvio:UnitOfMeasure
                { ?Entity_0  a                    RFDevice:Time }
              }
            UNION
              { ?Var0  Nuvio:informationSource  ?Entity_0 }
          }
      }
    }
  }
