PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarWarningReceiver_0
WHERE
  { ?RadarWarningReceiver_0
              a                     RFDevice:RadarWarningReceiver
    { ?Entity_0  Nuvio:aggregateOf  ?RadarWarningReceiver_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?InformationEntity_0
                    Nuvio:representedBy  ?Entity_0
        }
      }
    }
  }
