PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CR_0
WHERE
  { ?CR_0  a                     SDR:CR
    { ?Var0  RFDevice:supportsTransmitting  ?CR_0
      { ?Var0     a                     Nuvio:Process .
        ?Transmitting_0
                  Nuvio:hasSubprocess   ?Var0
        OPTIONAL
          { ?Transmitting_0
                      a                     RFDevice:Transmitting
            { ?Power_0  RFDevice:hasMaxOutputPower  ?Transmitting_0
              { ?Power_0  Nuvio:hasValue  ?Var1
                { RFDevice:Decibel_milliwatts
                            Nuvio:hasUnitOfMeasure  ?Var1
                  OPTIONAL
                    { ?Var1  RFDevice:hasNonNegativeIntegerValue  ?DataValue0 }
                }
              }
            }
          }
      }
    }
  }
