PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?BlinkingJamming_0
                RFDevice:supportsJamming  ?ElectronicAttackSystem_0
      { ?BlinkingJamming_0
                  RFDevice:hasPulseWidth  ?Quantity_0
      }
    }
  }
