PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ContinuousWaveRadar_0
WHERE
  { ?ContinuousWaveRadar_0
              a                     RFDevice:ContinuousWaveRadar
    { ?Var0  RFDevice:supportsTransmitting  ?ContinuousWaveRadar_0
      { ?Var0  a                     Nuvio:Process ;
               Nuvio:hasSubprocess   ?Transmitting_0
        OPTIONAL
          { ?Quantity_0  RFDevice:hasMaxOutputPower  ?Transmitting_0 }
      }
    }
  }
