PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?TrackingRadar_0
WHERE
  { ?TrackingRadar_0
              a                     RFDevice:TrackingRadar
    { ?TrackingRadar_0
                RFDevice:isDeployedOn  ?Aircraft_0
      { ?Aircraft_0  a                  RFDevice:Aircraft
        { ?Entity_0  RFDevice:supportsJamming  ?Aircraft_0
          { ?Entity_0  Nuvio:expresses  ?Entity_0
            OPTIONAL
              {   { ?Entity_0  a                    skos:ConceptScheme ;
                              skos:topConceptOf     ?Entity_0
                    { ?Entity_0  a                    RFDevice:Voltage }
                  }
                UNION
                  {   { ?InformationEntity_0
                                  Nuvio:representedBy  ?Entity_0
                      }
                    UNION
                      { ?InformationEntity_0
                                  a                     Nuvio:InformationEntity
                      }
                  }
              }
          }
        }
      }
    }
  }
