PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Entity_0  Nuvio:aggregateOf  ?Half_DuplexCommunicationsSystem_0
      { ?Entity_0  a                    Nuvio:Entity ;
                  Nuvio:expresses       ?Value_0
        OPTIONAL
          { ?Entity_0  a                    RFDevice:PhaseShiftKeyingModulation
            { ?Entity_0  a                    Nuvio:Attribute }
            { ?Entity_0  a                    RFDevice:LongitudeValueInDegree
              { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 != 1742059571 )
              }
            }
          }
        { ?Value_0  a                     Nuvio:Value ;
                    Nuvio:hasUnitOfMeasure  RFDevice:Watt
        }
      }
    }
  }
