PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ContinuousWaveRadar_0
WHERE
  { ?ContinuousWaveRadar_0
              a                     RFDevice:ContinuousWaveRadar
    { ?Entity_0  RFDevice:supportsTransmitting  ?ContinuousWaveRadar_0
      { ?InformationContent_0
                  Nuvio:expresses  ?Entity_0
        { ?Entity_0  a                    gml:MultiSurface
          { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
            FILTER ( ?DataValue0 < 1853685998 )
          }
          OPTIONAL
            {   { ?Var0  Nuvio:hasValue  ?Entity_0
                  { ?Var0  a                     RFDevice:FloatValue
                    { ?Var0  Nuvio:hasPrecision  ?DataValue1
                      FILTER ( ?DataValue1 >= 1294071510 )
                    }
                  }
                }
              UNION
                { ?Entity_0  a                    Nuvio:Object ;
                            RFDevice:hasCapacity  ?Angle_0
                  OPTIONAL
                    {   { ?Angle_0  a                     RFDevice:Angle }
                      UNION
                        { ?LongitudeValue_0
                                    Nuvio:hasValue  ?Angle_0
                          { ?LongitudeValue_0
                                      a                     RFDevice:LongitudeValue
                          }
                        }
                    }
                }
            }
        }
      }
    }
  }
