PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?TrackingRadar_0
WHERE
  { ?TrackingRadar_0
              a                     RFDevice:TrackingRadar
    { ?Entity_0  RFDevice:hasCapacity  ?TrackingRadar_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?Attribute_0  Nuvio:isExpressedBy  ?Entity_0
        OPTIONAL
          { ?Entity_0  a                    skos:OrderedCollection
            { ?Attribute_0  a                 Nuvio:Attribute }
          }
      }
    }
  }
