PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB205mini_i_0
WHERE
  { ?USRPB205mini_i_0
              a                     SDR:USRPB205mini-i
    { ?Entity_0  RFDevice:isProducerOf  ?USRPB205mini_i_0
      { ?InformationRepresentation_0
                  Nuvio:expresses  ?Entity_0
        { ?Entity_0  a                    RFDevice:Time
          { ?Entity_0  a                    Nuvio:InformationEntity .
            ?Var0     Nuvio:informationSource  ?Entity_0
            { ?Var0  a                     Nuvio:UnitOfMeasure }
          }
        }
        OPTIONAL
          { ?InformationRepresentation_0
                      a                     Nuvio:InformationRepresentation .
            ?InformationContent_0
                      Nuvio:representedBy   ?InformationRepresentation_0
            { ?InformationContent_0
                        a                     Nuvio:InformationContent
            }
          }
      }
    }
  }
