PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ContinuousWaveRadar_0
WHERE
  { ?ContinuousWaveRadar_0
              a                     RFDevice:ContinuousWaveRadar
    OPTIONAL
      { ?ContinuousWaveRadar_0
                  RFDevice:hasWeight  ?Weight_0
        { ?Weight_0  Nuvio:hasValue  ?Var0
          { ?WeightUnit_0
                      Nuvio:hasUnitOfMeasure  ?Var0
            { ?WeightUnit_0
                        a                     RFDevice:WeightUnit
            }
          }
        }
      }
  }
