PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    OPTIONAL
      { ?Full_DuplexCommunicationsSystem_0
                  RFDevice:isProducerOf  ?Entity_0
        { ?Entity_0  a                    Nuvio:Entity .
          ?Entity_1  Nuvio:isExpressedBy  ?Entity_0
          {   { ?Entity_0  a                    RFDevice:CumulativeDetection }
            UNION
              { ?Entity_0  a                    RFDevice:InformationUnit
                { ?Entity_0  a                    RFDevice:LongitudeValueInDegree
                  { ?Entity_0  a                    Nuvio:Attribute }
                  { ?Entity_0  a                    Nuvio:InformationEntity ;
                              Nuvio:isExpressedBy   ?ContinuousWaveRadar_0
                    { ?ContinuousWaveRadar_0
                                a                     RFDevice:ContinuousWaveRadar
                      OPTIONAL
                        { ?ContinuousWaveRadar_0
                                    RFDevice:isDeployedOn  ObjectDescription:Satellite_instance43
                        }
                    }
                  }
                }
              }
          }
        }
      }
  }
