PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RFSystem_0
WHERE
  { ?RFSystem_0  a                  RFDevice:RFSystem
    { ?Var0  RFDevice:hasCapability  ?RFSystem_0
      {   { ?Entity_0  RFDevice:hasPulseRepetitionInterval  ?Var0
            { ?Entity_0  a                    Nuvio:Entity .
              ?Object_0  Nuvio:isExpressedBy  ?Entity_0
              { ?Entity_0  a                    RFDevice:LatitudeValueInRadian
                OPTIONAL
                  { ?Entity_0  a                    Nuvio:Process }
                OPTIONAL
                  { ?Object_0  a                    Nuvio:Object .
                    ?Voltage_0  Nuvio:hasObjectQuantity  ?Object_0
                  }
              }
            }
          }
        UNION
          { ?Var0  a                     RFDevice:Transceiving }
      }
    }
  }
