PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CR_0
WHERE
  { ?CR_0  a                     SDR:CR
    { ?CR_0  RFDevice:supportsJamming  ?Var0
      { ?Var0  a                     RFDevice:AdjustableBandwidthSensing
        OPTIONAL
          { ?Var0  a                     Nuvio:Entity
            { ?Var0     a                     Nuvio:Process .
              ?AbstractParametricCurveSurface_0
                        Nuvio:participatesIn  ?Var0
              { ?Var0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 >= 286734343 )
              }
            }
          }
      }
    }
  }
