PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?BistaticRadar_0
WHERE
  { ?BistaticRadar_0
              a                     RFDevice:BistaticRadar
    OPTIONAL
      { ?Entity_0  RFDevice:hasProducer  ?BistaticRadar_0
        {   { ?Value_0  Nuvio:expresses  ?Entity_0 }
          UNION
            { ?Entity_0  RFDevice:hasMaxSensedPower  ?Entity_0
              { ?Entity_0  a                    RFDevice:FrequencyScanRateUnit
                { ?Entity_0  a                    Nuvio:Quality }
              }
              { ?Value_0  a                     Nuvio:Value .
                ?Object_0  Nuvio:hasUnitOfMeasure  ?Value_0
                { ?Object_0  a                    Nuvio:Object ;
                            Nuvio:hasParticipant  ObjectDescription:Transceiving_instance105
                }
              }
            }
        }
      }
  }
