PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB2xx_0
WHERE
  { ?USRPB2xx_0  a                  SDR:USRPB2xx
    OPTIONAL
      { ?Entity_0  Nuvio:aggregateOf  ?USRPB2xx_0
        { ?Entity_0  a                    RFDevice:SpectrumSensing
          { ?Quantity_0  RFDevice:hasBandwidth  ?Entity_0
            { ?Quantity_0  a                  Nuvio:Quantity }
          }
          { ?Entity_0  a                    RFDevice:LatitudeValueInRadian }
          { ?InformationContent_0
                      Nuvio:relevantIndividual  ?Entity_0
            { ?InformationContent_0
                        a                     Nuvio:InformationContent
            }
            { ?Entity_0  a                    Nuvio:InformationEntity ;
                        Nuvio:expresses       ?SelfProtectionJamming_0
              { ?SelfProtectionJamming_0
                          a                     RFDevice:SelfProtectionJamming
              }
            }
          }
        }
      }
  }
