PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseDopplerRadar_0
WHERE
  { ?PulseDopplerRadar_0
              a                     RFDevice:PulseDopplerRadar
    { ObjectDescription:Transmitter_instance74
                Nuvio:partOf  ?PulseDopplerRadar_0
    }
  }
