PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>

SELECT DISTINCT  ?TrackingRadar_0
WHERE
  { ?TrackingRadar_0
              a                     RFDevice:TrackingRadar
    { ?TrackingRadar_0
                RFDevice:supportsSpectrumSensing  ?Var0
      { ?Var0  a                     RFDevice:TerrainBounceJamming
        OPTIONAL
          { ObjectDescription:Instance123
                      RFDevice:hasPulseWidth  ?Var0
          }
      }
    }
  }
