PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX3xx_0
WHERE
  { ?USRPX3xx_0  a                  SDR:USRPX3xx
    { ?Entity_0  RFDevice:isDeployedOn  ?USRPX3xx_0
      {   { ?Entity_0  a                    Nuvio:Entity ;
                      Nuvio:isExpressedBy   ?InformationRepresentation_0
          }
        UNION
          {   { ?Entity_0  a                    RFDevice:Modulation
                OPTIONAL
                  { ?Entity_0  a                    Nuvio:Value ;
                              Nuvio:hasUnitOfMeasure  ?TimeUnit_0
                    { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                      FILTER ( ?DataValue0 != 1560183167 )
                    }
                  }
                { ?Var0  Nuvio:informationSource  ?Entity_0
                  { ?Var0  a                     RFDevice:GroundPlatform
                    { ?Var0  a                     RFDevice:ContinuousWaveRadarModulation }
                  }
                }
              }
            UNION
              { ?InformationContent_0
                          Nuvio:represents  ?InformationRepresentation_0
              }
          }
      }
    }
  }
