PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?BistaticRadar_0
WHERE
  { ?BistaticRadar_0
              a                     RFDevice:BistaticRadar
    { ?Entity_0  RFDevice:isProducerOf  ?BistaticRadar_0
      {   { ?Entity_0  a                    Nuvio:Entity }
        UNION
          {   { ?Entity_0  a                    RFDevice:FloatValue }
            UNION
              { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 <= -850677965 )
              }
            { ?Entity_0  a                    RFDevice:TimeInterval
              { ?Var0  Nuvio:hasValue  ?Entity_0
                { ?Var0  RFDevice:hasNonNegativeIntegerValue  ?DataValue1
                  OPTIONAL
                    { ?TimeUnit_0  Nuvio:hasUnitOfMeasure  ?Var0
                      { ?TimeUnit_0  a                  RFDevice:TimeUnit }
                    }
                }
              }
            }
            { ?Entity_0  a                    Nuvio:Process }
          }
      }
    }
  }
