PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CommunicationsSystem_0
WHERE
  { ?CommunicationsSystem_0
              a                     RFDevice:CommunicationsSystem
    OPTIONAL
      { ?RadioComponent_0
                  Nuvio:compositeOf  ?CommunicationsSystem_0
        { ?CortexA9_0  Nuvio:aggregateOf  ?RadioComponent_0
          { ?CortexA9_0  Nuvio:partOf  ?IEDJammer_0
            { ?IEDJammer_0  a                 RFDevice:IEDJammer
              OPTIONAL
                { ?IEDJammer_0  RFDevice:hasFrequencyRange  ?FreqencyRange_0
                  { ?FreqencyRange_0
                              a                     RFDevice:FreqencyRange
                    { ?FreqencyRange_0
                                RFDevice:hasMin  ?Entity_0
                      { ?Entity_0  a                    Nuvio:Entity ;
                                  Nuvio:expresses       ?Entity_0
                        { ?Entity_0  a                    RFDevice:JammingSystem
                          OPTIONAL
                            { ?Entity_0  a                    RFDevice:FloatValue
                              { ?Entity_0  a                    RFDevice:ElectricCharge
                                { ?Entity_0  Nuvio:hasValue  ?Var0
                                  { ?Var0  a                     RFDevice:DecimalValue }
                                }
                              }
                            }
                        }
                      }
                    }
                  }
                }
            }
          }
        }
      }
  }
