PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?Submarine_0  RFDevice:isDeployedOn  ?ElectronicAttackSystem_0
      { ?Submarine_0  RFDevice:hasCapability  ?Process_0 }
    }
  }
