PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>

SELECT DISTINCT  ?ModelX_0
WHERE
  { ?ModelX_0  a                    RFDevice:ModelX
    { ?Var0  RFDevice:supportsTransmitting  ?ModelX_0
      {   { ?Var0  a                     RFDevice:CommunicationsJamming }
        UNION
          { ObjectDescription:Instance197
                      RFDevice:hasPulseWidth  ?Var0
          }
        { ?Var0  a                     RFDevice:Transceiving }
      }
    }
  }
