PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB210_0
WHERE
  { ?USRPB210_0  a                  SDR:USRPB210
    { ?InstantaneousFrequencyMeasurementReceiver_0
                Nuvio:partOf  ?USRPB210_0
      { ?InstantaneousFrequencyMeasurementReceiver_0
                  a                     RFDevice:InstantaneousFrequencyMeasurementReceiver
        OPTIONAL
          { ?RadarJammer_0
                      Nuvio:aggregateOf  ?InstantaneousFrequencyMeasurementReceiver_0
            { ?RadarJammer_0
                        a                     RFDevice:RadarJammer
              { ?ElectronicWarfare_0
                          RFDevice:supportsJamming  ?RadarJammer_0
                { ?ElectronicWarfare_0
                            a                     RFDevice:ElectronicWarfare
                }
              }
            }
          }
      }
    }
  }
