PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?Entity_0  RFDevice:hasCapacity  ?PulseRadar_0
      { ?Entity_0  a                    RFDevice:FormationJamming
        { ?Attribute_0  RFDevice:hasPulseRepetitionInterval  ?Entity_0
          { ?Attribute_0  a                 Nuvio:Attribute }
        }
        { ?Entity_0  a                    RFDevice:Frequency
          { ?Var0  Nuvio:hasValue  ?Entity_0
            { ?Var0  RFDevice:hasFloatValue  ?DataValue0
              FILTER ( ! ( ?DataValue0 >= "0"^^xsd:decimal ) )
              OPTIONAL
                { ?Var0  a                     RFDevice:DecimalValue
                  { ?Var0  RFDevice:hasFloatValue  ?DataValue1
                    FILTER ( ?DataValue1 < 93.46 )
                  }
                }
            }
          }
        }
      }
    }
  }
