PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>

SELECT DISTINCT  ?RFSystem_0
WHERE
  { ?RFSystem_0  a                  RFDevice:RFSystem
    { ?Ship_0  RFDevice:isDeployedOn  ?RFSystem_0
      { ?Moving_0  RFDevice:hasCapability  ?Ship_0 }
    }
  }
