PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?USRPB210_0
WHERE
  { ?USRPB210_0  a                  SDR:USRPB210
    { SDR:USRP_SpectrumSensing_Instance0
                RFDevice:supportsJamming  ?USRPB210_0
    }
  }
