PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseDopplerRadar_0
WHERE
  { ?PulseDopplerRadar_0
              a                     RFDevice:PulseDopplerRadar
    OPTIONAL
      { ?PulseDopplerRadar_0
                  RFDevice:isProducerOf  ?Object_0
        { ?Object_0  a                    Nuvio:Object .
          ?TimeInterval_0
                    RFDevice:hasMaxPowerConsumption  ?Object_0
          { ?Var0  Nuvio:hasValue  ?TimeInterval_0
            { ?Var0  a                     Nuvio:Entity
              { ?UnitOfMeasure_0
                          Nuvio:hasUnitOfMeasure  ?Var0
                { ?UnitOfMeasure_0
                            a                     Nuvio:UnitOfMeasure
                }
              }
            }
          }
        }
      }
  }
