PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CR_0
WHERE
  { ?CR_0  a                     SDR:CR
    { ?CR_0  RFDevice:supportsJamming  ?Var0
      { ?Var0  a                     Nuvio:Entity
        { ?Var0  a                     RFDevice:SpotJamming
          OPTIONAL
            { ?Power_0  RFDevice:hasMaxOutputPower  ?Var0
              { ?Power_0  a                     RFDevice:Power
                OPTIONAL
                  { ?Power_0  Nuvio:hasValue  ?Var1 }
              }
            }
        }
      }
    }
  }
