PREFIX  geosparql: <http://www.opengis.net/ont/geosparql#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarWarningReceiver_0
WHERE
  { ?RadarWarningReceiver_0
              a                     RFDevice:RadarWarningReceiver
    { ?Entity_0  RFDevice:isProducerOf  ?RadarWarningReceiver_0
      { ?Entity_0  a                    Nuvio:Entity
        {   { ?Entity_0  a                    Nuvio:Situation }
          UNION
            { ?Feature_0  Nuvio:relevantIndividual  ?Entity_0
              { ?Feature_0  a                   geosparql:Feature }
            }
          { ?Entity_0  a                    RFDevice:AntennaPolarization }
        }
      }
    }
  }
