PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Satellite_0  RFDevice:isDeployedOn  ?Half_DuplexCommunicationsSystem_0
      { ?Entity_0  RFDevice:supportsTuning  ?Satellite_0
        { ?Entity_0  a                    Nuvio:Situation
          { ?Entity_0  Nuvio:relevantIndividual  ?CommunicationsSystem_0
            { ?Var0  RFDevice:supportsTransmitting  ?CommunicationsSystem_0
              { ?Var0  a                     RFDevice:AdjustableBandwidthSensing
                OPTIONAL
                  { ?FreqencyRange_0
                              RFDevice:hasBandwidthRange  ?Var0
                    { ?FreqencyRange_0
                                a                     RFDevice:FreqencyRange
                    }
                  }
                OPTIONAL
                  { ?Var0  a                     RFDevice:SweptSpotJamming }
                { ?Entity_0  RFDevice:hasPulseWidth  ?Var0 }
              }
            }
          }
        }
      }
    }
  }
