PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseDopplerRadar_0
WHERE
  { ?PulseDopplerRadar_0
              a                     RFDevice:PulseDopplerRadar
    OPTIONAL
      { ?InstantaneousFrequencyMeasurementReceiver_0
                  Nuvio:compositeOf  ?PulseDopplerRadar_0
        { ?InstantaneousFrequencyMeasurementReceiver_0
                    a                     RFDevice:InstantaneousFrequencyMeasurementReceiver
        }
      }
  }
