PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB205mini_i_0
WHERE
  { ?USRPB205mini_i_0
              a                     SDR:USRPB205mini-i
    { ?Var0  Nuvio:compositeOf  ?USRPB205mini_i_0
      {   { ?Var0  a                     Nuvio:Entity
            { ?Var0  a                     SDR:XC7K325TFPGA
              { ?DipoleAntenna_0
                          Nuvio:partOf  ?Var0
                { ?DipoleAntenna_0
                            a                     RFDevice:DipoleAntenna
                }
              }
              { ?Var0  a                     RFDevice:TimeUnit }
              { ?Var0  a                     Nuvio:UnitOfMeasure }
            }
          }
        UNION
          { ?Var1  RFDevice:hasSamplingRate  ?Var0 }
      }
    }
  }
