PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?MonostaticRadar_0
WHERE
  { ?MonostaticRadar_0
              a                     RFDevice:MonostaticRadar
    { ?MonostaticRadar_0
                RFDevice:supportsTuning  ?Var0
      { ?Var0  Nuvio:subprocessOf  ?TerrainBounceJamming_0
        { ?TerrainBounceJamming_0
                    RFDevice:hasPulseRepetitionFrequency  ?Power_0
        }
      }
    }
  }
