PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?BistaticRadar_0
WHERE
  { ?BistaticRadar_0
              a                     RFDevice:BistaticRadar
    { ?BistaticRadar_0
                RFDevice:isDeployedOn  ?Entity_0
      {   { ?Entity_0  a                    gml:Circle }
        UNION
          { ?Entity_0  a                    RFDevice:VelocityUnit }
        { ?Entity_0  a                    Nuvio:InformationEntity .
          ?Arc_0    Nuvio:isExpressedBy   ?Entity_0
          OPTIONAL
            { ?Arc_0  a                     gml:Arc }
        }
        OPTIONAL
          { ?Entity_0  a                    RFDevice:TimeInterval }
      }
    }
  }
