PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    OPTIONAL
      { ?Entity_0  RFDevice:hasProducer  ?JammingSystem_0
        { ?Entity_0  a                    Nuvio:Entity
          { ?Entity_0  a                    RFDevice:PulseRadar
            OPTIONAL
              { ?RadarJammer_0
                          Nuvio:aggregateOf  ?Entity_0
              }
            { ?Entity_0  a                    Nuvio:InformationEntity .
              ?AbstractGeometry_0
                        Nuvio:isExpressedBy   ?Entity_0
            }
          }
        }
      }
  }
