PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?USRPB200_0
WHERE
  { ?USRPB200_0  a                  SDR:USRPB200
    { ?USRPB200_0  RFDevice:supportsJamming  ?Var0
      { ?Var0  a                     RFDevice:AdjustableBandwidthSensing
        { ?Var0  Nuvio:expresses  ?InformationEntity_0
          { ?Var0  a                     gml:MultiSurface
            { ?Var0  a                     RFDevice:AngleUnit
              { ?Var0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 = -2066147499 )
              }
              { ?Var0  a                     Nuvio:Object
                { ?Var0  a                     Nuvio:Situation
                  { ?Var0  Nuvio:relevantIndividual  ObjectDescription:ADC_instance161 }
                }
              }
            }
          }
          { ?InformationEntity_0
                      a                     Nuvio:InformationEntity
          }
        }
      }
    }
  }
