PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    { ?Full_DuplexCommunicationsSystem_0
                RFDevice:isProducerOf  ?Entity_0
      { ?Entity_0  a                    Nuvio:Entity
        OPTIONAL
          {   { ?Entity_0  a                    skos:ConceptScheme }
            UNION
              { ObjectDescription:Instance4784
                          Nuvio:hasSubprocess  ?Entity_0
              }
          }
      }
    }
  }
