PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?USRPE312_0
WHERE
  { ?USRPE312_0  a                  SDR:USRPE312
    { ?Entity_0  RFDevice:hasProducer  ?USRPE312_0
      { ?Entity_0  a                    Nuvio:Entity ;
                  Nuvio:expresses       ?Attribute_0
        { ?Entity_0  a                    gml:PolynomialSpline
          { ?Entity_0  a                    Nuvio:Value
            { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
              FILTER ( ?DataValue0 = -1798191650 )
            }
          }
        }
        { ?Attribute_0  a                 Nuvio:Attribute }
      }
    }
  }
