PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Process_0  RFDevice:hasCapability  ?Half_DuplexCommunicationsSystem_0
      { ?Process_0  a                   Nuvio:Process .
        ?Length_0  RFDevice:hasTransmitPowerRange  ?Process_0
        OPTIONAL
          { ?Length_0  a                    RFDevice:Length
            OPTIONAL
              { ?Length_0  Nuvio:hasValue  ?Var0
                { ?Var0     a                     Nuvio:Entity .
                  ?Attribute_1  Nuvio:expresses   ?Var0
                  { ?Var0  a                     RFDevice:OnOffKeyingModulation
                    { ?Var0  RFDevice:hasCapacity  ?Attribute_0 }
                    { ?Var0  a                     RFDevice:DataSize
                      { ?Var1  Nuvio:hasValue  ?Var0 }
                    }
                  }
                }
              }
          }
      }
    }
  }
