PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RFSystem_0
WHERE
  { ?RFSystem_0  a                  RFDevice:RFSystem
    { ?Entity_0  RFDevice:hasProducer  ?RFSystem_0
      {   { ?Entity_0  a                    Nuvio:Entity ;
                      Nuvio:expresses       ?Process_0
            { ?Entity_0  a                    RFDevice:SpatialUnit
              { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 >= 161249245 )
              }
            }
          }
        UNION
          { ?Process_0  a                   Nuvio:Process }
      }
    }
  }
