PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?GNURadio_0
WHERE
  { ?GNURadio_0  a                  SDR:GNURadio
    { ?Var0  RFDevice:supportsTuning  ?GNURadio_0
      { ?Var0  a                     RFDevice:InboundRangeGatePullOffJamming
        OPTIONAL
          { ?Var0     a                     Nuvio:Entity .
            ?InformationContent_0
                      Nuvio:expresses       ?Var0
            {   { ?Var0  a                     RFDevice:CrossEyeJamming
                  OPTIONAL
                    {   { ?Var0  a                     RFDevice:LongValue }
                      UNION
                        { ?Var0  RFDevice:hasDoubleValue  ?DataValue0
                          FILTER ( ?DataValue0 <= -459749580 )
                        }
                    }
                }
              UNION
                { ?Var0  a                     Nuvio:Situation
                  { ObjectDescription:IEDJammer_instance239
                              Nuvio:relevantIndividual  ?Var0
                  }
                }
            }
            { ?InformationContent_0
                        a                     Nuvio:InformationContent
            }
          }
      }
    }
  }
