PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX300_0
WHERE
  { ?USRPX300_0  a                  SDR:USRPX300
    OPTIONAL
      { ?Var0  Nuvio:compositeOf  ?USRPX300_0
        { ?Var1  RFDevice:hasResolution  ?Var0
          { ?Var0  a                     RFDevice:ADC
            { ?DataSize_0  RFDevice:hasResolution  ?Var0
              { ?DataSize_0  a                  RFDevice:DataSize }
            }
          }
        }
      }
  }
