PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RFSystem_0
WHERE
  { ?RFSystem_0  a                  RFDevice:RFSystem
    { ?Entity_0  RFDevice:isProducerOf  ?RFSystem_0
      { ?Attribute_0  Nuvio:expresses  ?Entity_0
        { ?Entity_0  a                    RFDevice:InverseGainJamming
          { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
            FILTER ( ?DataValue0 <= -929233528 )
          }
          { ?Entity_0  a                    Nuvio:Situation
            { ?TimeInstant_0
                        Nuvio:relevantIndividual  ?Entity_0
            }
          }
        }
        { ?Attribute_0  a                 Nuvio:Attribute }
      }
    }
  }
