PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>

SELECT DISTINCT  ?MonostaticRadar_0
WHERE
  { ?MonostaticRadar_0
              a                     RFDevice:MonostaticRadar
    { ?Object_0  RFDevice:hasProducer  ?MonostaticRadar_0
      { ?AntennaPolarization_0
                  RFDevice:hasPolarization  ?Object_0
        { ?AntennaPolarization_0
                    a                     RFDevice:AntennaPolarization
        }
      }
    }
  }
