PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE312_0
WHERE
  { ?USRPE312_0  a                  SDR:USRPE312
    { ?Entity_0  RFDevice:hasProducer  ?USRPE312_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?Situation_0  Nuvio:expresses   ?Entity_0
        { ?Entity_0  a                    Nuvio:Object .
          ObjectDescription:AntennaPolarization_instance41
                    Nuvio:hasObjectQuality  ?Entity_0
          { ?Entity_0  a                    RFDevice:Height }
          { ?Situation_0  a                 Nuvio:Situation
            { ?SweptSpotJamming_0
                        Nuvio:relevantIndividual  ?Situation_0
              { ?SweptSpotJamming_0
                          a                     RFDevice:SweptSpotJamming
                { ?Entity_0  RFDevice:hasPulseWidth  ?SweptSpotJamming_0 }
              }
            }
          }
        }
      }
    }
  }
