PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    OPTIONAL
      { ?Var0  RFDevice:hasCapability  ?JammingSystem_0
        { ?Attribute_0  Nuvio:isExpressedBy  ?Var0
          {   { ?Var0  a                     RFDevice:Ship
                OPTIONAL
                  { ?Var0  a                     Nuvio:UnitOfMeasure }
              }
            UNION
              { ?Var0  a                     Nuvio:Situation
                { ?Spartan6FPGA_0
                            Nuvio:relevantIndividual  ?Var0
                  { ?Spartan6FPGA_0
                              a                     SDR:Spartan6FPGA
                  }
                }
              }
          }
        }
      }
  }
