PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?ElectronicAttackSystem_0
                RFDevice:hasGain  ?Weight_0
      { ?Weight_0  a                    RFDevice:Weight
        { ?Weight_0  Nuvio:hasValue  ?Var0
          { ?Var0  RFDevice:hasFloatValue  ?DataValue0
            FILTER ( ! ( ?DataValue0 > "0.0"^^xsd:double ) )
            { ?UnitOfMeasure_0
                        Nuvio:hasUnitOfMeasure  ?Var0
              { ?UnitOfMeasure_0
                          a                     Nuvio:UnitOfMeasure
              }
            }
            OPTIONAL
              { ?Var0  Nuvio:hasDataValue  ?DataValue1 }
          }
        }
      }
    }
  }
