PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicSupportSystem_0
WHERE
  { ?ElectronicSupportSystem_0
              a                     RFDevice:ElectronicSupportSystem
    { ?ElectronicSupportSystem_0
                RFDevice:hasCapability  ?Var0
      { ?InformationRepresentation_0
                  Nuvio:expresses  ?Var0
        OPTIONAL
          { ?Var0  a                     RFDevice:LongitudeValueInDegree }
        { ?Var0  a                     RFDevice:SweepJamming
          { ?Power_0  RFDevice:hasPulseWidth  ?Var0
            {   { ?Power_0  a                     RFDevice:Power }
              UNION
                { ?Var1  Nuvio:hasValue  ?Power_0
                  { ?Var1  a                     RFDevice:ShortValue }
                }
            }
          }
        }
        { ?Var0  a                     RFDevice:Transceiving }
      }
    }
  }
