PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?Entity_0  RFDevice:isProducerOf  ?ElectronicAttackSystem_0
      { ?UnitOfMeasure_0
                  Nuvio:expresses  ?Entity_0
        { ?Entity_0  a                    SDR:USRPE312
          { ?Entity_0  a                    RFDevice:Transceiving }
          { ?Entity_0  a                    Nuvio:Value .
            ?PowerUnit_0  Nuvio:hasUnitOfMeasure  ?Entity_0
            { ?PowerUnit_0  a                 RFDevice:PowerUnit }
          }
          OPTIONAL
            {   { ?Entity_0  a                    RFDevice:PositiveDecimalValue }
              UNION
                { ?Entity_0  RFDevice:hasFloatValue  ?DataValue0
                  FILTER ( ?DataValue0 > 35.64 )
                }
            }
          { ?UnitOfMeasure_0
                      a                     Nuvio:UnitOfMeasure
          }
        }
      }
    }
  }
