PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  sf:   <http://www.opengis.net/ont/sf#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?USRPB205mini_i_0
WHERE
  { ?USRPB205mini_i_0
              a                     SDR:USRPB205mini-i
    OPTIONAL
      { ?Entity_0  RFDevice:hasProducer  ?USRPB205mini_i_0
        { ?UnitOfMeasure_0
                    Nuvio:isExpressedBy  ?Entity_0
          { ?Entity_0  a                    sf:LinearRing
            { ?Entity_0  a                    Nuvio:Value .
              ?DimensionlessUnit_0
                        Nuvio:hasUnitOfMeasure  ?Entity_0
              { ?DimensionlessUnit_0
                          a                     Nuvio:DimensionlessUnit
              }
              { ?Entity_0  a                    RFDevice:IntValue
                { ?Entity_0  RFDevice:hasPositiveIntegerValue  ?DataValue0
                  FILTER ( ?DataValue0 <= 1025276177 )
                }
              }
            }
            OPTIONAL
              { ?Entity_0  a                    Nuvio:InformationEntity }
          }
        }
      }
  }
