PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?GNURadio_0
WHERE
  { ?GNURadio_0  a                  SDR:GNURadio
    OPTIONAL
      { ?Object_0  RFDevice:hasProducer  ?GNURadio_0
        { ?Gain_0  RFDevice:hasVoltage  ?Object_0
          { ?Gain_0  a                     RFDevice:Gain
            { ?Var0  Nuvio:hasValue  ?Gain_0 }
          }
        }
      }
  }
