PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarWarningReceiver_0
WHERE
  { ?RadarWarningReceiver_0
              a                     RFDevice:RadarWarningReceiver
    OPTIONAL
      { ?Entity_0  Nuvio:partOf  ?RadarWarningReceiver_0
        { ?Entity_0  a                    Nuvio:Entity
          { ?Jammer_0  Nuvio:partOf  ?Entity_0
            { ?Jammer_0  a                    RFDevice:Jammer
              OPTIONAL
                { ?Jammer_0  RFDevice:hasFrequencyAccuracy  ?Object_0
                  { ?Object_0  a                    Nuvio:Object }
                }
            }
            { ?Quantity_0  Nuvio:hasProcessQuantity  ?Entity_0
              { ?Var0  Nuvio:informationSource  ?Entity_0
                { ?Var0  a                     Nuvio:UnitOfMeasure }
                {   { ?Entity_0  a                    Nuvio:InformationContent .
                      ?InformationRepresentation_0
                                Nuvio:represents      ?Entity_0
                    }
                  UNION
                    { ?Entity_0  Nuvio:represents  ?InformationRepresentation_0 }
                }
              }
            }
          }
        }
      }
  }
