PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  sf:   <http://www.opengis.net/ont/sf#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE310_0
WHERE
  { ?USRPE310_0  a                  SDR:USRPE310
    { ?Var0  RFDevice:supportsTuning  ?USRPE310_0
      { ?Var0  a                     RFDevice:AdjustableBandwidthSensing
        { ?Entity_0  RFDevice:hasPulseRepetitionFrequency  ?Var0
          { ?Entity_0  a                    Nuvio:Entity .
            ?Object_0  Nuvio:isExpressedBy  ?Entity_0
            OPTIONAL
              { ?Entity_0  a                    RFDevice:DirectConversionReceiver
                { ?Entity_0  a                    Nuvio:UnitOfMeasure }
                OPTIONAL
                  { ?Entity_0  a                    Nuvio:Process .
                    ObjectDescription:Frequency_instance310
                              Nuvio:hasProcessQuantity  ?Entity_0
                  }
              }
            { ?Object_0  a                    Nuvio:Object .
              ?InformationEntity_0
                        Nuvio:hasParticipant  ?Object_0
              { ?InformationEntity_0
                          Nuvio:isExpressedBy  ?PolyhedralSurface_0
                { ?PolyhedralSurface_0
                            a                     sf:PolyhedralSurface
                }
              }
            }
          }
        }
      }
    }
  }
