PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>

SELECT DISTINCT  ?MonostaticRadar_0
WHERE
  { ?MonostaticRadar_0
              a                     RFDevice:MonostaticRadar
    OPTIONAL
      { ?Aircraft_0  RFDevice:isDeployedOn  ?MonostaticRadar_0
        { ?Aircraft_0  a                  RFDevice:Aircraft }
      }
  }
