PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN200_0
WHERE
  { ?USRPN200_0  a                  SDR:USRPN200
    { ?USRPN200_0  Nuvio:aggregateOf  ?XC3SD1800AFPGA_0
      { ?XC3SD1800AFPGA_0
                  a                     SDR:XC3SD1800AFPGA
      }
    }
  }
