PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>

SELECT DISTINCT  ?PulseDopplerRadar_0
WHERE
  { ?PulseDopplerRadar_0
              a                     RFDevice:PulseDopplerRadar
    OPTIONAL
      { ?PulseDopplerRadar_0
                  RFDevice:hasCapability  ?PulseRadarModulation_0
        { ?PulseRadarModulation_0
                    a                     RFDevice:PulseRadarModulation
          { RFDevice:Freq_40GHz
                      RFDevice:hasMaxOutputPower  ?PulseRadarModulation_0
          }
        }
      }
  }
