PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ContinuousWaveRadar_0
WHERE
  { ?ContinuousWaveRadar_0
              a                     RFDevice:ContinuousWaveRadar
    { ?ContinuousWaveRadar_0
                RFDevice:isProducerOf  ?Entity_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?Object_0  Nuvio:isExpressedBy  ?Entity_0
        { ?Entity_0  a                    RFDevice:MannedPlatform
          { ?Entity_0  a                    RFDevice:IntValue
            { ?Entity_0  RFDevice:hasNonNegativeIntegerValue  ?DataValue0
              FILTER ( ?DataValue0 > 47.23 )
            }
          }
          { ?Entity_0  a                    Nuvio:UnitOfMeasure }
        }
        OPTIONAL
          { ?Object_0  a                    Nuvio:Object .
            ?EmitterLocationDetection_0
                      Nuvio:participatesIn  ?Object_0
          }
      }
    }
  }
