PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription100.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB2xxmini_0
WHERE
  { ?USRPB2xxmini_0
              a                     SDR:USRPB2xxmini
    { ?USRPB2xxmini_0
                Nuvio:partOf  ?Var0
      { ?InformationContent_0
                  Nuvio:isExpressedBy  ?Var0
        OPTIONAL
          { ?Var0  a                     RFDevice:Height }
        { ?Var1  RFDevice:hasCapacity  ?Var0 }
      }
    }
  }
