PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription100.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?GNURadio_0
WHERE
  { ?GNURadio_0  a                  SDR:GNURadio
    { ?GNURadio_0  RFDevice:hasProducer  ?Entity_0
      { ?InformationRepresentation_0
                  Nuvio:expresses  ?Entity_0
        {   { ?Entity_0  a                    RFDevice:EnergyDetection
              { ?Entity_0  a                    Nuvio:Quantity
                { ?Var0  Nuvio:informationSource  ?Entity_0
                  { ?Var0  a                     RFDevice:Component }
                }
              }
            }
          UNION
            { ?InformationRepresentation_0
                        a                     Nuvio:InformationRepresentation ;
                        Nuvio:represents      ?InformationEntity_0
            }
        }
      }
    }
  }
