PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription100.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX310_0
WHERE
  { ?USRPX310_0  a                  SDR:USRPX310
    { ?Object_0  RFDevice:isDeployedOn  ?USRPX310_0
      { ?Object_0  a                    Nuvio:Object .
        ?DeceptiveJamming_0
                  Nuvio:participatesIn  ?Object_0
        {   { ?DeceptiveJamming_0
                        a                     RFDevice:DeceptiveJamming
            }
          UNION
            { ?Power_0  RFDevice:hasPulseRepetitionFrequency  ?DeceptiveJamming_0
              { ?Power_0  a                     RFDevice:Power }
            }
        }
      }
    }
  }
