PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription100.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarWarningReceiver_0
WHERE
  { ?RadarWarningReceiver_0
              a                     RFDevice:RadarWarningReceiver
    { ?Entity_0  RFDevice:hasNoiseFigure  ?RadarWarningReceiver_0
      { ?Entity_0  a                    Nuvio:Entity
        {   { ?Entity_0  a                    RFDevice:DeceptiveCommunicationsJamming
              { ?Entity_1  Nuvio:hasProcessQuantity  ?Entity_0 }
            }
          UNION
            { ?Entity_0  a                    Nuvio:Attribute }
        }
      }
    }
  }
