PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription100.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ContinuousWaveRadar_0
WHERE
  { ?ContinuousWaveRadar_0
              a                     RFDevice:ContinuousWaveRadar
    OPTIONAL
      { ?ContinuousWaveRadar_0
                  Nuvio:aggregateOf  ?DirectConversionReceiver_0
        { ?DirectConversionReceiver_0
                    a                     RFDevice:DirectConversionReceiver
          { ?QuantityRange_0
                      RFDevice:hasFrequencyRange  ?DirectConversionReceiver_0
            { ?QuantityRange_0
                        a                     RFDevice:QuantityRange
              { ?QuantityRange_0
                          RFDevice:hasMax  ?NoiseFigure_0
                { ?NoiseFigure_0
                            Nuvio:hasValue  ?Var0
                }
              }
            }
          }
        }
      }
  }
