PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription100.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB200mini_0
WHERE
  { ?USRPB200mini_0
              a                     SDR:USRPB200mini
    { ?USRPB200mini_0
                RFDevice:hasNoiseFigure  ?Entity_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?InformationEntity_0
                  Nuvio:expresses       ?Entity_0
        {   { ?Entity_0  a                    RFDevice:SpatialVolumeUnit }
          UNION
            {   {   { ?FrequencyScanRateUnit_0
                                Nuvio:hasUnitOfMeasure  ?Entity_0
                    }
                  UNION
                    { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                      FILTER ( ?DataValue0 >= 476232539 )
                    }
                  OPTIONAL
                    { ?FrequencyScanRateUnit_0
                                a                     RFDevice:FrequencyScanRateUnit
                    }
                }
              UNION
                {   { ?Entity_0  a                    Nuvio:InformationContent .
                      ?InformationEntity_0
                                Nuvio:represents      ?Entity_0
                    }
                  UNION
                    { ?InformationEntity_0
                                a                     Nuvio:InformationEntity
                    }
                }
            }
        }
      }
    }
  }
