PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription100.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?BistaticRadar_0
WHERE
  { ?BistaticRadar_0
              a                     RFDevice:BistaticRadar
    OPTIONAL
      { ?BistaticRadar_0
                  RFDevice:hasSamplingRate  ?Entity_0
        { ?Entity_0  a                    Nuvio:Entity .
          ?Object_0  Nuvio:isExpressedBy  ?Entity_0
        }
      }
  }
