PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription100.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicSupportSystem_0
WHERE
  { ?ElectronicSupportSystem_0
              a                     RFDevice:ElectronicSupportSystem
    { ?Entity_0  RFDevice:hasCapability  ?ElectronicSupportSystem_0
      {   { ?Attribute_0  Nuvio:expresses  ?Entity_0 }
        UNION
          {   { ?ElectricChargeUnit_0
                          Nuvio:hasUnitOfMeasure  ?Entity_0
              }
            UNION
              { ?ElectricChargeUnit_0
                          a                     RFDevice:ElectricChargeUnit
              }
          }
        { ?Attribute_0  a                 Nuvio:Attribute }
      }
    }
  }
