PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription100.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SDR_0
WHERE
  { ?SDR_0  a                     SDR:SDR
    { ?IEDJammer_0  Nuvio:partOf  ?SDR_0
      {   { ?IEDJammer_0  a                 RFDevice:IEDJammer }
        UNION
          { ?Object_0  RFDevice:hasFrequencyRange  ?IEDJammer_0
            { ?Object_0  a                    Nuvio:Object }
          }
      }
    }
  }
