PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription100.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?Entity_0  Nuvio:partOf  ?SurveillanceRadar_0
      {   { ?Entity_0  a                    SDR:USRPB205mini-i }
        UNION
          { ?Var0  Nuvio:partOf  ?Entity_0
            { ?Var0  RFDevice:hasResolution  SDR:Data_12bit }
          }
      }
    }
  }
