PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription100.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB205mini_i_0
WHERE
  { ?USRPB205mini_i_0
              a                     SDR:USRPB205mini-i
    { ?USRPB205mini_i_0
                RFDevice:supportsTransmitting  ?Var0
      { ?Var0  a                     RFDevice:AdjustableBandwidthSensing
        {   { ?Var1  RFDevice:hasNoiseFigure  ?Var0 }
          UNION
            {   { ?Var0  a                     RFDevice:DRFMJamming }
              UNION
                { ?Var0  RFDevice:hasPulseWidth  ?Attribute_0
                  { ?Attribute_0  a                 Nuvio:Attribute }
                }
            }
        }
      }
    }
  }
