PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription100.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?Entity_0  RFDevice:hasProducer  ?PulseRadar_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?Attribute_0  Nuvio:expresses   ?Entity_0
        { ?Entity_0  a                    Nuvio:InformationEntity ;
                    Nuvio:expresses       RFDevice:Bit
          {   { ?Entity_0  a                    Nuvio:Value .
                ?SpatialLinearUnit_0
                          Nuvio:hasUnitOfMeasure  ?Entity_0
              }
            UNION
              { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 >= -1032289796 )
                { ?SpatialLinearUnit_0
                            a                     RFDevice:SpatialLinearUnit
                }
              }
          }
        }
      }
    }
  }
