PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CommunicationsSystem_0
WHERE
  { ?CommunicationsSystem_0
              a                     RFDevice:CommunicationsSystem
    { ?Entity_0  RFDevice:supportsJamming  ?CommunicationsSystem_0
      {   { ?Entity_0  a                    Nuvio:Entity ;
                      Nuvio:isExpressedBy   ?Attribute_0
          }
        UNION
          { ?Entity_0  a                    RFDevice:RangeGatePullOffJamming
            OPTIONAL
              { ?Power_0  RFDevice:hasPulseWidth  ?Entity_0 }
            { ?Var0  Nuvio:hasValue  ?Entity_0 }
            { ?Entity_0  a                    Nuvio:Attribute }
          }
      }
    }
  }
