PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseDopplerRadar_0
WHERE
  { ?PulseDopplerRadar_0
              a                     RFDevice:PulseDopplerRadar
    { ?MobilePlatform_0
                RFDevice:isDeployedOn  ?PulseDopplerRadar_0
      { ?Process_0  RFDevice:supportsTransmitting  ?MobilePlatform_0
        { ?Mixer_0  Nuvio:hasParticipant  ?Process_0
          OPTIONAL
            { ?Mixer_0  a                     RFDevice:Mixer }
        }
      }
    }
  }
