PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription50.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { ?Object_0  RFDevice:hasProducer  ?JammingSystem_0
      { ?DeceptiveJamming_0
                  Nuvio:participatesIn  ?Object_0
        { ?DeceptiveJamming_0
                    a                     RFDevice:DeceptiveJamming
        }
      }
    }
  }
