PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription50.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CommunicationsSystem_0
WHERE
  { ?CommunicationsSystem_0
              a                     RFDevice:CommunicationsSystem
    { ?Entity_0  Nuvio:compositeOf  ?CommunicationsSystem_0
      { ?Object_0  Nuvio:expresses  ?Entity_0
        { ?Entity_0  a                    RFDevice:ShortValue
          { ?Entity_0  a                    Nuvio:Process .
            ?Quality_0  Nuvio:hasProcessQuantity  ?Entity_0
            { ?Quality_0  a                   Nuvio:Quality }
          }
        }
      }
    }
  }
