PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription50.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { SDR:Weight_1_2kg
                RFDevice:hasWeight  ?JammingSystem_0
    }
  }
