PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription50.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB200mini_0
WHERE
  { ?USRPB200mini_0
              a                     SDR:USRPB200mini
    { ?USRPB200mini_0
                RFDevice:supportsSpectrumSensing  ?Var0
      { ?Var0     a                     Nuvio:Entity .
        ?InformationContent_0
                  Nuvio:expresses       ?Var0
        { ?InformationContent_0
                    a                     Nuvio:InformationContent .
          ?InformationEntity_0
                    Nuvio:represents      ?InformationContent_0
          { ?InformationEntity_0
                      a                     Nuvio:InformationEntity
          }
        }
        { ?Var0  a                     RFDevice:CommunicationsJamming
          { ?Quality_0  Nuvio:hasProcessQuality  ?Var0
            { ?Quality_0  a                   Nuvio:Quality }
          }
        }
      }
    }
  }
