PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription50.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ContinuousWaveRadar_0
WHERE
  { ?ContinuousWaveRadar_0
              a                     RFDevice:ContinuousWaveRadar
    { ?Entity_0  RFDevice:isDeployedOn  ?ContinuousWaveRadar_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_0  a                    RFDevice:WhipAntenna
          { ?Entity_0  a                    Nuvio:UnitOfMeasure
            { ?Var0  Nuvio:hasValue  ?Entity_0
              { ?Var0  RFDevice:hasDoubleValue  ?DataValue0
                FILTER ( ?DataValue0 > "0"^^xsd:decimal )
              }
            }
          }
        }
      }
    }
  }
