PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription50.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseDopplerRadar_0
WHERE
  { ?PulseDopplerRadar_0
              a                     RFDevice:PulseDopplerRadar
    { ?RadarJammer_0
                Nuvio:compositeOf  ?PulseDopplerRadar_0
      { ObjectDescription:Producer_instance2
                  RFDevice:isProducerOf  ?RadarJammer_0
      }
    }
  }
