PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription50.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SDR_0
WHERE
  { ?SDR_0  a                     SDR:SDR
    { ?Var0  RFDevice:supportsJamming  ?SDR_0
      { ?Var0  a                     RFDevice:SpectrumSensing
        OPTIONAL
          { ?Var0  RFDevice:hasBandwidthRange  ?Entity_0
            { ?Entity_0  Nuvio:hasValue  ?Var1
              { ?Var1  a                     RFDevice:PositiveIntegerValue }
            }
          }
        OPTIONAL
          { ?Var0  a                     Nuvio:Process }
      }
    }
  }
