PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription50.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    OPTIONAL
      { ?PulseRadar_0
                  Nuvio:aggregateOf  ?Entity_0
        {   { ?Entity_0  a                    SDR:USRPN210 }
          UNION
            {   { ?Entity_0  a                    RFDevice:SpotJamming }
              UNION
                { ObjectDescription:Power_instance0
                            RFDevice:hasTransmitPowerRange  ?Entity_0
                }
            }
          { ?Entity_0  a                    RFDevice:SpatialLinearUnit
            { ?Entity_0  a                    RFDevice:NonNegativeDecimalValue }
            {   { ?Entity_0  a                    Nuvio:InformationRepresentation .
                  ?InformationContent_0
                            Nuvio:representedBy   ?Entity_0
                }
              UNION
                { ?InformationContent_0
                            a                     Nuvio:InformationContent .
                  ?InformationEntity_0
                            Nuvio:representedBy   ?InformationContent_0
                  { ?InformationEntity_0
                              a                     Nuvio:InformationEntity
                  }
                }
            }
          }
        }
      }
  }
