PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription50.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?TrackingRadar_0
WHERE
  { ?TrackingRadar_0
              a                     RFDevice:TrackingRadar
    { ?Entity_0  RFDevice:hasMaxPowerConsumption  ?TrackingRadar_0
      { ?Entity_0  a                    Nuvio:Entity ;
                  Nuvio:isExpressedBy   ?Entity_0
        { ?Entity_0  a                    Nuvio:UnitOfMeasure
          { ?Entity_0  a                    Nuvio:Situation
            { ?Moving_0  Nuvio:relevantIndividual  ?Entity_0
              { ?Moving_0  a                    RFDevice:Moving }
            }
          }
          { ?Entity_0  Nuvio:hasUnitOfMeasure  ?Entity_0 }
        }
      }
    }
  }
