PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription50.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?Var0  RFDevice:supportsSpectrumSensing  ?SurveillanceRadar_0
      { ?Var0  a                     Nuvio:Entity
        { ?Attribute_0  RFDevice:hasResolution  ?Var0
          { ?Attribute_0  a                 Nuvio:Attribute }
          { ?Var0  a                     RFDevice:PositiveIntegerValue
            { ?Var0  RFDevice:hasDecimalValue  ?DataValue0
              FILTER ( ?DataValue0 <= -1741085027 )
            }
          }
        }
        { ?Var0  a                     RFDevice:InverseGainJamming
          OPTIONAL
            { ObjectDescription:Power_instance2
                        RFDevice:hasPulseRepetitionFrequency  ?Var0
            }
          { ?Var0  RFDevice:hasFrequencyAccuracy  ?Var0 }
        }
      }
    }
  }
