PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB205mini_i_0
WHERE
  { ?USRPB205mini_i_0
              a                     SDR:USRPB205mini-i
    { ?Entity_0  RFDevice:isProducerOf  ?USRPB205mini_i_0
      {   { ?Entity_0  a                    Nuvio:Entity .
            ?InformationRepresentation_0
                      Nuvio:expresses       ?Entity_0
          }
        UNION
          { ?InformationRepresentation_0
                      a                     Nuvio:InformationRepresentation .
            ?InformationContent_0
                      Nuvio:represents      ?InformationRepresentation_0
            { ?InformationEntity_0
                        Nuvio:representedBy  ?InformationContent_0
              { ?InformationEntity_0
                          a                     Nuvio:InformationEntity
              }
            }
          }
      }
    }
  }
