PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?ElectronicAttackSystem_0
                RFDevice:isProducerOf  ?Entity_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_0  a                    RFDevice:StandoffJamming
          { ?Attribute_0  RFDevice:hasEffectiveRadiatedPower  ?Entity_0
            { ?Attribute_0  a                 Nuvio:Attribute }
          }
          { ?Entity_0  a                    Nuvio:InformationEntity ;
                      Nuvio:isExpressedBy   ?ArcByCenterPoint_0
          }
          { ?Entity_0  a                    RFDevice:ElectricCharge }
          { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
            FILTER ( ?DataValue0 > 436007389 )
          }
        }
      }
    }
  }
