PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE312_0
WHERE
  { ?USRPE312_0  a                  SDR:USRPE312
    { ?Entity_0  RFDevice:hasVoltage  ?USRPE312_0
      { ?Entity_0  a                    Nuvio:InformationEntity
        { ?Entity_0  a                    RFDevice:EmitterLocationDetection
          { ?Var0  Nuvio:hasParticipant  ?Entity_0
            { ?CommunicationsJamming_0
                        RFDevice:supportsTransmitting  ?Var0
              { ?Entity_0  RFDevice:hasProducer  ?Var0 }
            }
          }
          OPTIONAL
            { ?Entity_0  a                    RFDevice:PositiveDecimalValue }
        }
      }
    }
  }
