PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    OPTIONAL
      { ?Entity_0  RFDevice:hasProducer  ?JammingSystem_0
        { ?Entity_0  a                    Nuvio:Entity .
          ?Attribute_0  Nuvio:expresses   ?Entity_0
          { ?Entity_0  a                    Nuvio:Quality
            OPTIONAL
              { ?Entity_0  a                    Nuvio:InformationEntity .
                ?Receiver_0  Nuvio:expresses    ?Entity_0
                OPTIONAL
                  { ?Receiver_0  a                  RFDevice:Receiver }
              }
          }
        }
      }
  }
