PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN210_0
WHERE
  { ?USRPN210_0  a                  SDR:USRPN210
    { ?USRPN210_0  Nuvio:aggregateOf  ?Entity_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_0  a                    SDR:CortexA9
          { ?Oscillator_0
                      Nuvio:partOf  ?Entity_0
            { ?Oscillator_0
                        a                     RFDevice:Oscillator
            }
          }
          { ?Entity_0  a                    Nuvio:UnitOfMeasure }
          {   { ?Entity_0  a                    RFDevice:DataSize }
            UNION
              { ?TimeInstant_0
                          Nuvio:expresses  ?Entity_0
                OPTIONAL
                  { ?TimeInstant_0
                              a                     RFDevice:TimeInstant
                    OPTIONAL
                      { ?Var0  Nuvio:hasValue  ?TimeInstant_0 }
                  }
              }
          }
        }
      }
    }
  }
