PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>

SELECT DISTINCT  ?SearchRadar_0
WHERE
  { ?SearchRadar_0
              a                     RFDevice:SearchRadar
    { ?SearchRadar_0
                RFDevice:supportsJamming  ?Var0
      { ?Var0  a                     RFDevice:Mixer
        { ?Var0  a                     RFDevice:AngleValue
          { ?Var0  a                     RFDevice:Velocity }
        }
      }
    }
  }
