PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RFSystem_0
WHERE
  { ?RFSystem_0  a                  RFDevice:RFSystem
    { ?Entity_0  RFDevice:hasProducer  ?RFSystem_0
      { ?Entity_0  a                    Nuvio:Entity
        {   { ?Entity_0  a                    RFDevice:BarrageJamming }
          UNION
            {   { ?InformationContent_0
                            Nuvio:relevantIndividual  ?Entity_0
                }
              UNION
                { ?Entity_0  a                    Nuvio:Process }
            }
        }
      }
    }
  }
