PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE312_0
WHERE
  { ?USRPE312_0  a                  SDR:USRPE312
    { ?Var0  RFDevice:hasNoiseFigure  ?USRPE312_0
      {   { ?Var0  a                     Nuvio:Entity ;
                   Nuvio:isExpressedBy   ?InformationContent_0
            { ?Var0  a                     RFDevice:NoiseJamming
              { ?Var0  a                     Nuvio:Object }
            }
            { ?InformationContent_0
                        a                     Nuvio:InformationContent .
              ?InformationEntity_0
                        Nuvio:representedBy   ?InformationContent_0
              { ?InformationEntity_0
                          a                     Nuvio:InformationEntity
              }
            }
          }
        UNION
          { ?Var1  Nuvio:hasValue  ?Var0 }
      }
    }
  }
