PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX300_0
WHERE
  { ?USRPX300_0  a                  SDR:USRPX300
    { ?Entity_0  RFDevice:hasProducer  ?USRPX300_0
      { ?Object_0  Nuvio:isExpressedBy  ?Entity_0
        { ?Object_0  RFDevice:isProducerOf  ?Entity_0
          { ?Object_0  a                    Nuvio:Object }
          OPTIONAL
            { ?Entity_0  a                    Nuvio:Situation .
              ?MultiSurface_0
                        Nuvio:relevantIndividual  ?Entity_0
              { ?ModelX_0  Nuvio:relevantIndividual  ?Entity_0
                { ?Entity_1  RFDevice:hasHeight  ?ModelX_0 }
              }
            }
        }
      }
    }
  }
