PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?TrackingRadar_0
WHERE
  { ?TrackingRadar_0
              a                     RFDevice:TrackingRadar
    OPTIONAL
      { ?TrackingRadar_0
                  RFDevice:isDeployedOn  ?Entity_0
        {   { ?Situation_0  Nuvio:expresses  ?Entity_0 }
          UNION
            { ?Situation_0  a                 Nuvio:Situation ;
                        Nuvio:relevantIndividual  ?Mixer_0
            }
        }
      }
  }
