PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SDR_0
WHERE
  { ?SDR_0  a                     SDR:SDR
    { ?Var0  RFDevice:supportsTransmitting  ?SDR_0
      { ?Entity_0  RFDevice:hasPulseRepetitionInterval  ?Var0
        { ?Entity_0  a                    Nuvio:Entity .
          ?InformationEntity_0
                    Nuvio:expresses       ?Entity_0
          OPTIONAL
            { ObjectDescription:AntennaPolarization_instance34
                        Nuvio:hasObjectQuality  ?Entity_0
              { ?Entity_0  a                    Nuvio:Situation }
            }
        }
      }
    }
  }
