PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CommunicationsSystem_0
WHERE
  { ?CommunicationsSystem_0
              a                     RFDevice:CommunicationsSystem
    { ?Receiver_0  Nuvio:partOf  ?CommunicationsSystem_0
      { ?Receiver_0  a                  RFDevice:Receiver
        { ObjectDescription:Instance5458
                    Nuvio:compositeOf  ?Receiver_0
        }
      }
    }
  }
