PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription4000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE313_0
WHERE
  { ?USRPE313_0  a                  SDR:USRPE313
    { ?USRPE313_0  RFDevice:hasNoiseFigure  ?Weight_0
      { ?Weight_0  a                    RFDevice:Weight
        { ?Var0  Nuvio:hasValue  ?Weight_0
          {   {   { ?Var0  a                     gml:CompositeSurface }
                UNION
                  { ?Var0  a                     Nuvio:Process }
                { ?Entity_0  Nuvio:hasUnitOfMeasure  ?Var0 }
              }
            UNION
              { ?Var0  RFDevice:hasNonNegativeIntegerValue  ?DataValue0 }
          }
        }
      }
    }
  }
