PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN200_0
WHERE
  { ?USRPN200_0  a                  SDR:USRPN200
    { ?Var0  RFDevice:supportsJamming  ?USRPN200_0
      { ?Var0     a                     Nuvio:Entity .
        ?InformationEntity_0
                  Nuvio:isExpressedBy   ?Var0
        { ?Quantity_0  RFDevice:hasMaxOutputPower  ?Var0
          { ?Quantity_0  a                  Nuvio:Quantity }
          { ?FixedBandwidthSensing_0
                      Nuvio:hasSubprocess  ?Var0
            { ?FixedBandwidthSensing_0
                        a                     RFDevice:SpectrumSensing
            }
          }
        }
      }
    }
  }
