PREFIX  sf:   <http://www.opengis.net/ont/sf#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?PulseRadar_0
                RFDevice:isProducerOf  ?Entity_0
      { ?Entity_0  a                    Nuvio:Entity
        {   { ?Entity_0  a                    sf:MultiCurve }
          UNION
            { ?Entity_0  a                    RFDevice:EmitterLocationDetection
              { ?Var0  RFDevice:hasTarget  ?Entity_0 }
            }
          {   { ?Entity_0  a                    RFDevice:TimeUnit }
            UNION
              { ?Entity_0  a                    Nuvio:Situation }
          }
        }
      }
    }
  }
