PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX300_0
WHERE
  { ?USRPX300_0  a                  SDR:USRPX300
    { ?Entity_0  RFDevice:hasProducer  ?USRPX300_0
      { ?Entity_0  a                    Nuvio:Entity ;
                  Nuvio:expresses       ?Entity_0
        OPTIONAL
          { ?Entity_0  a                    SDR:USRPN3xx
            { ?Receiving_0  RFDevice:supportsJamming  ?Entity_0
              { ?Receiving_0  a                 RFDevice:Receiving }
            }
            { ?Entity_0  a                    RFDevice:Gain }
            { ?Entity_0  a                    Nuvio:UnitOfMeasure }
          }
      }
    }
  }
