PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?Entity_0  RFDevice:hasProducer  ?PulseRadar_0
      { ?Entity_0  a                    Nuvio:Entity
        {   { ?Entity_0  a                    Nuvio:Value
              { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 <= 860427877 )
              }
            }
          UNION
            { ?Entity_0  a                    RFDevice:VelocityUnit }
          { ?Entity_0  a                    Nuvio:InformationEntity ;
                      Nuvio:isExpressedBy   ObjectDescription:Instance867
          }
        }
      }
    }
  }
