PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?Entity_0  RFDevice:hasBeamwidth  ?SurveillanceRadar_0
      {   {   {   { ?Entity_0  a                    RFDevice:BarrageJamming }
                UNION
                  { ?Quantity_0  RFDevice:hasPulseWidth  ?Entity_0
                    { ?Quantity_0  a                  Nuvio:Quantity }
                  }
                { ?Entity_0  a                    RFDevice:VelocityUnit }
              }
            UNION
              { ?Entity_0  a                    Nuvio:Value .
                ?InformationEntity_0
                          Nuvio:hasUnitOfMeasure  ?Entity_0
                { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                  FILTER ( ?DataValue0 = -65400209 )
                }
              }
          }
        UNION
          { ?Entity_0  a                    RFDevice:Width
            { ?Var0  Nuvio:hasValue  ?Entity_0 }
          }
      }
    }
  }
