PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CommunicationsSystem_0
WHERE
  { ?CommunicationsSystem_0
              a                     RFDevice:CommunicationsSystem
    OPTIONAL
      { ?Receiving_0  RFDevice:supportsSpectrumSensing  ?CommunicationsSystem_0
        { ?RadarFrequencyBand_0
                    RFDevice:hasFrequencyAccuracy  ?Receiving_0
          { ?Attribute_0  RFDevice:hasMax  ?RadarFrequencyBand_0
            { ?Attribute_0  a                 Nuvio:Attribute }
          }
        }
      }
  }
