PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?MonostaticRadar_0
WHERE
  { ?MonostaticRadar_0
              a                     RFDevice:MonostaticRadar
    OPTIONAL
      { ?MonostaticRadar_0
                  RFDevice:supportsTuning  ?Var0
        { ?InformationEntity_0
                    Nuvio:isExpressedBy  ?Var0
          { ?Var0  a                     Nuvio:Process
            { ?InformationEntity_0
                        a                     Nuvio:InformationEntity .
              ObjectDescription:Instance356
                        Nuvio:isExpressedBy   ?InformationEntity_0
            }
          }
          OPTIONAL
            { ?Var0  a                     RFDevice:Receiving }
        }
      }
  }
