PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicSupportSystem_0
WHERE
  { ?ElectronicSupportSystem_0
              a                     RFDevice:ElectronicSupportSystem
    { ?DirectConversionReceiver_0
                Nuvio:partOf  ?ElectronicSupportSystem_0
      { ?DirectConversionReceiver_0
                  a                     RFDevice:DirectConversionReceiver
        { ?DirectConversionReceiver_0
                    Nuvio:compositeOf  ?HardwareComponent_0
        }
      }
    }
  }
