PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?GNURadio_0
WHERE
  { ?GNURadio_0  a                  SDR:GNURadio
    { ?Entity_0  RFDevice:isDeployedOn  ?GNURadio_0
      { ?Situation_0  Nuvio:isExpressedBy  ?Entity_0
        {   { ?Situation_0  a                 Nuvio:Situation }
          UNION
            { ?Triangle_0  Nuvio:relevantIndividual  ?Situation_0
              { ?Triangle_0  a                  gml:Triangle }
            }
        }
      }
    }
  }
