PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?IEDTrigger_0
                Nuvio:aggregateOf  ?Half_DuplexCommunicationsSystem_0
      { ?IEDTrigger_0
                  a                     RFDevice:IEDTrigger
        { ?FreqencyRange_0
                    RFDevice:hasFrequencyAccuracy  ?IEDTrigger_0
          { ?FreqencyRange_0
                      a                     RFDevice:FreqencyRange
            { ?Frequency_0  RFDevice:hasMax  ?FreqencyRange_0
              { ?Var0  Nuvio:hasValue  ?Frequency_0 }
            }
          }
        }
      }
    }
  }
