PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Object_0  RFDevice:isProducerOf  ?Half_DuplexCommunicationsSystem_0
      {   { ?Object_0  a                    Nuvio:Object ;
                      RFDevice:hasBeamwidth  ?Velocity_0
          }
        UNION
          { ?Velocity_0  a                  RFDevice:Velocity }
      }
    }
  }
