PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB210_0
WHERE
  { ?USRPB210_0  a                  SDR:USRPB210
    { ?XC6SLX75FPGA_0
                Nuvio:aggregateOf  ?USRPB210_0
      { ?XC6SLX75FPGA_0
                  a                     SDR:XC6SLX75FPGA
      }
    }
  }
