PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?SuperheterodyneReceiver_0
                Nuvio:aggregateOf  ?Half_DuplexCommunicationsSystem_0
      { ?SuperheterodyneReceiver_0
                  RFDevice:hasFrequencyAccuracy  ?RadioFrequencyBand_0
        { ?Attribute_0  RFDevice:hasMin  ?RadioFrequencyBand_0
          { ?Attribute_0  a                 Nuvio:Attribute }
        }
      }
    }
  }
