PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarSystem_0
WHERE
  { ?RadarSystem_0
              a                     RFDevice:RadarSystem
    { ?Entity_0  RFDevice:hasMaxPowerConsumption  ?RadarSystem_0
      { ?PositiveIntegerValue_0
                  Nuvio:relevantIndividual  ?Entity_0
        { ?InformationEntity_0
                    Nuvio:represents  ?Entity_0
        }
      }
    }
  }
