PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB200mini_0
WHERE
  { ?USRPB200mini_0
              a                     SDR:USRPB200mini
    { ?USRPB200mini_0
                RFDevice:hasCapability  ?Var0
      { ?Var1  RFDevice:hasMaxOutputPower  ?Var0
        { ?Var2  Nuvio:hasValue  ?Var1
          OPTIONAL
            { ?Var1  a                     RFDevice:Power
              { ?Var3  Nuvio:hasValue  ?Var1
                { ?Entity_0  Nuvio:hasUnitOfMeasure  ?Var3
                  { ?Entity_0  a                    Nuvio:Entity }
                  { ?Var3  a                     RFDevice:NonNegativeDecimalValue }
                }
              }
            }
        }
      }
    }
  }
