PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB205mini_i_0
WHERE
  { ?USRPB205mini_i_0
              a                     SDR:USRPB205mini-i
    OPTIONAL
      { ?Var0  Nuvio:compositeOf  ?USRPB205mini_i_0
        { ?Modulator_0  Nuvio:partOf  ?Var0
          { ?Transmitter_0
                      Nuvio:compositeOf  ?Modulator_0
            { ?Transmitter_0
                        a                     RFDevice:Transmitter
              { ?RadarFrequencyBand_0
                          RFDevice:hasFrequencyAccuracy  ?Transmitter_0
              }
            }
          }
          OPTIONAL
            { ?Var1  RFDevice:hasVoltage  ?Var0 }
        }
      }
  }
