PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?BistaticRadar_0
WHERE
  { ?BistaticRadar_0
              a                     RFDevice:BistaticRadar
    { ?BistaticRadar_0
                RFDevice:hasCapability  ?Var0
      {   { ?Var0  Nuvio:hasSubprocess  ?Jamming_0
            { ?Jamming_0  a                   RFDevice:Jamming
              { ?Attribute_0  RFDevice:hasPulseRepetitionInterval  ?Jamming_0 }
            }
          }
        UNION
          { ?Var0  a                     RFDevice:Transceiving }
      }
    }
  }
