PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { ?RadioComponent_0
                Nuvio:compositeOf  ?JammingSystem_0
      { ?RadioComponent_0
                  a                     RFDevice:RadioComponent
        { ?Entity_0  RFDevice:hasProducer  ?RadioComponent_0
          { ?Entity_0  Nuvio:expresses  ?Entity_0
            OPTIONAL
              { ?Entity_0  a                    RFDevice:IntegerValue
                { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                  FILTER ( ?DataValue0 < 1793929398 )
                }
                { ?Entity_0  a                    Nuvio:Process }
                OPTIONAL
                  { ?Entity_0  a                    Nuvio:Attribute }
              }
          }
        }
      }
    }
  }
