PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SearchRadar_0
WHERE
  { ?SearchRadar_0
              a                     RFDevice:SearchRadar
    { ?Weight_0  RFDevice:hasWidth  ?SearchRadar_0
      { ?Weight_0  a                    RFDevice:Weight
        { ?Weight_0  Nuvio:hasValue  ?Var0
          {   { ?Var0  a                     Nuvio:Value }
            UNION
              { ?Var0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 != -1153410075 )
              }
          }
        }
      }
    }
  }
