PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX3xx_0
WHERE
  { ?USRPX3xx_0  a                  SDR:USRPX3xx
    { ?Entity_0  RFDevice:hasProducer  ?USRPX3xx_0
      { ?Entity_0  a                    Nuvio:Entity ;
                  Nuvio:expresses       ?Object_0
        OPTIONAL
          { ?Var0  Nuvio:hasParticipant  ?Entity_0
            {   { ?Var0  a                     SDR:USRPN3xx }
              UNION
                { ?Var1  Nuvio:compositeOf  ?Var0
                  { ?Var2  RFDevice:hasVoltage  ?Var1 }
                }
            }
            { ?Entity_0  a                    RFDevice:AntennaPolarization }
            { ?Height_0  Nuvio:relevantIndividual  ?Entity_0 }
            OPTIONAL
              { ?Object_0  a                    Nuvio:Object }
          }
      }
    }
  }
