PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { ?Var0  RFDevice:supportsSpectrumSensing  ?JammingSystem_0
      { ?Var0  a                     RFDevice:FixedBandwidthSensing
        { ?Var0  RFDevice:hasBandwidth  ObjectDescription:Frequency_instance224 }
      }
    }
  }
