PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB200_210_0
WHERE
  { ?USRPB200_210_0
              a                     SDR:USRPB200-210
    { ?XilinxFPGA_0
                Nuvio:compositeOf  ?USRPB200_210_0
      { ?XilinxFPGA_0
                  a                     SDR:XilinxFPGA
        { ObjectDescription:XC6SLX150FPGA_instance18
                    Nuvio:compositeOf  ?XilinxFPGA_0
        }
      }
    }
  }
