PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE310_0
WHERE
  { ?USRPE310_0  a                  SDR:USRPE310
    { ?USRPE310_0  RFDevice:hasVoltage  ?Entity_0
      {   { ?Entity_0  a                    Nuvio:Entity }
        UNION
          {   {   { ?Entity_0  a                    Nuvio:Situation .
                    ?ElectronicAttack_0
                              Nuvio:relevantIndividual  ?Entity_0
                  }
                UNION
                  { ?ElectronicAttack_0
                              a                     RFDevice:ElectronicAttack
                  }
                { ?Entity_0  a                    Nuvio:Attribute }
              }
            UNION
              { ?Entity_0  a                    Nuvio:Object .
                ?FrequencyModulation_0
                          Nuvio:participatesIn  ?Entity_0
                { ?Entity_0  a                    Nuvio:UnitOfMeasure }
              }
          }
      }
    }
  }
