PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?GNURadio_0
WHERE
  { ?GNURadio_0  a                  SDR:GNURadio
    { ?IEDTrigger_0
                Nuvio:compositeOf  ?GNURadio_0
      { ?FreqencyRange_0
                  RFDevice:hasFrequencyRange  ?IEDTrigger_0
        { ?FreqencyRange_0
                    a                     RFDevice:FreqencyRange
          { ?Entity_0  RFDevice:hasMin  ?FreqencyRange_0
            { ?Entity_0  Nuvio:expresses  ?Entity_0
              OPTIONAL
                { ?Entity_0  a                    RFDevice:TimeUnit
                  { ?Entity_0  a                    RFDevice:Percentage
                    { ?Entity_0  a                    Nuvio:UnitOfMeasure }
                  }
                }
            }
          }
        }
      }
    }
  }
