PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?Entity_0  RFDevice:isProducerOf  ?SurveillanceRadar_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?InformationRepresentation_0
                  Nuvio:expresses       ?Entity_0
        {   { ?Entity_0  a                    RFDevice:DRFMJamming }
          UNION
            { ?Attribute_0  RFDevice:hasTransmitPowerRange  ?Entity_0
              { ?Attribute_0  a                 Nuvio:Attribute }
            }
          { ?Entity_0  a                    RFDevice:Angle }
          { ?Entity_0  a                    Nuvio:Process .
            ?Attribute_0  Nuvio:hasProcessQuality  ?Entity_0
          }
          { ?InformationRepresentation_0
                      a                     Nuvio:InformationRepresentation .
            ?Entity_1  Nuvio:representedBy  ?InformationRepresentation_0
          }
        }
      }
    }
  }
