PREFIX  sf:   <http://www.opengis.net/ont/sf#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?SurveillanceRadar_0
                RFDevice:supportsSpectrumSensing  ?Process_0
      { ?Process_0  a                   Nuvio:Process .
        ?Point_0  RFDevice:hasTarget    ?Process_0
        { ?Point_0  a                     sf:Point }
      }
    }
  }
