PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB205mini_i_0
WHERE
  { ?USRPB205mini_i_0
              a                     SDR:USRPB205mini-i
    { ?Entity_0  Nuvio:hasObjectQuantity  ?USRPB205mini_i_0
      {   { ?Entity_1  Nuvio:isExpressedBy  ?Entity_0 }
        UNION
          { ?Entity_0  a                    RFDevice:ElectronicSupportSystem
            { ?Entity_0  a                    Nuvio:UnitOfMeasure }
            { ?Var0  Nuvio:hasValue  ?Entity_0
              {   { ?Var0  a                     RFDevice:FloatValue }
                UNION
                  { ?Var0  RFDevice:hasPositiveIntegerValue  ?DataValue0
                    FILTER ( ?DataValue0 = "8.249298"^^xsd:double )
                  }
              }
            }
          }
      }
    }
  }
