PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>

SELECT DISTINCT  ?CommunicationsSystem_0
WHERE
  { ?CommunicationsSystem_0
              a                     RFDevice:CommunicationsSystem
    { ?Receiving_0  RFDevice:supportsTuning  ?CommunicationsSystem_0
      { ?Receiving_0  a                 RFDevice:Receiving
        { ?RadarFrequencyBand_0
                    RFDevice:hasFrequencyAccuracy  ?Receiving_0
        }
      }
    }
  }
