PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?GNURadio_0
WHERE
  { ?GNURadio_0  a                  SDR:GNURadio
    { ?Var0  RFDevice:supportsTuning  ?GNURadio_0
      { ?Var0  a                     RFDevice:InboundRangeGatePullOffJamming
        { ?Var0     a                     Nuvio:Entity .
          ?Attribute_0  Nuvio:isExpressedBy  ?Var0
          { ?Var0  a                     RFDevice:CommunicationsJamming
            { ?Var0  a                     RFDevice:InformationUnit
              OPTIONAL
                { ?NoiseFigure_0
                            RFDevice:hasNoiseFigure  ?Var0
                  { ?NoiseFigure_0
                              a                     RFDevice:NoiseFigure
                  }
                }
            }
            { ?Attribute_0  a                 Nuvio:Attribute }
          }
        }
      }
    }
  }
