PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?Var0  RFDevice:supportsSpectrumSensing  ?SurveillanceRadar_0
      { ObjectDescription:RadarFrequencyBand_instance126
                  RFDevice:hasBandwidthRange  ?Var0
      }
    }
  }
