PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB2xxmini_0
WHERE
  { ?USRPB2xxmini_0
              a                     SDR:USRPB2xxmini
    { ?Entity_0  RFDevice:hasProducer  ?USRPB2xxmini_0
      { ?Entity_0  a                    Nuvio:Object .
        ?AmplitudeModulation_0
                  Nuvio:participatesIn  ?Entity_0
        { ?Entity_0  a                    RFDevice:ShortValue
          { ?Entity_0  RFDevice:hasDoubleValue  ?DataValue0
            FILTER ( ?DataValue0 != 51.26 )
          }
        }
        OPTIONAL
          { ?Entity_0  a                    RFDevice:TimeInstant
            { ?Var0  Nuvio:hasValue  ?Entity_0
              { ?Var0     a                     Nuvio:Value .
                ?VoltageUnit_0
                          Nuvio:hasUnitOfMeasure  ?Var0
                {   { ?Var0  Nuvio:hasPrecision  ?DataValue1
                      FILTER ( ?DataValue1 != 759354334 )
                    }
                  UNION
                    { ?VoltageUnit_0
                                a                     RFDevice:VoltageUnit
                    }
                }
              }
            }
          }
      }
    }
  }
