PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ModelX_0
WHERE
  { ?ModelX_0  a                    RFDevice:ModelX
    { ?Aircraft_0  RFDevice:isDeployedOn  ?ModelX_0
      { ?Aircraft_0  a                  RFDevice:Aircraft
        { ?Entity_0  RFDevice:supportsJamming  ?Aircraft_0
          { ?Entity_0  a                    Nuvio:Entity .
            ?UnitOfMeasure_0
                      Nuvio:isExpressedBy   ?Entity_0
            OPTIONAL
              { ?UnitOfMeasure_0
                          a                     Nuvio:UnitOfMeasure
              }
          }
        }
      }
    }
  }
