PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?Entity_0  RFDevice:isProducerOf  ?SurveillanceRadar_0
      {   { ?Entity_0  a                    Nuvio:Entity .
            ?Situation_0  Nuvio:isExpressedBy  ?Entity_0
          }
        UNION
          {   { ?Entity_0  a                    RFDevice:AngleValue }
            UNION
              { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 <= -2084982930 )
              }
            { ?Entity_0  a                    Nuvio:Attribute }
          }
        {   { ?Situation_0  a                 Nuvio:Situation .
              ?Power_0  Nuvio:relevantIndividual  ?Situation_0
            }
          UNION
            { ?Var0  Nuvio:hasValue  ?Power_0
              { ?Var0  Nuvio:hasDataValue  ?DataValue1
                FILTER ( ?DataValue1 <= -11.22 )
              }
            }
        }
      }
    }
  }
