PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN3xx_0
WHERE
  { ?USRPN3xx_0  a                  SDR:USRPN3xx
    { ?USRPN3xx_0  Nuvio:compositeOf  ?Entity_0
      { ?Entity_0  Nuvio:expresses  ?Entity_0
        { ?Entity_0  a                    RFDevice:SuperheterodyneReceiver
          OPTIONAL
            { ?Entity_0  a                    RFDevice:ShortValue }
          OPTIONAL
            { ?USRPE312_0  RFDevice:hasTarget  ?Entity_0
              { ?USRPE312_0  a                  SDR:USRPE312
                { ?USRPE312_0  RFDevice:hasHeight  ?Var0 }
              }
            }
        }
      }
    }
  }
