PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarWarningReceiver_0
WHERE
  { ?RadarWarningReceiver_0
              a                     RFDevice:RadarWarningReceiver
    { ?Entity_0  RFDevice:hasChargingTime  ?RadarWarningReceiver_0
      { ?Entity_0  a                    Nuvio:Entity ;
                  Nuvio:expresses       ?Attribute_0
        { ?Process_0  RFDevice:supportsSpectrumSensing  ?Entity_0
          { ?Attribute_0  a                 Nuvio:Attribute }
        }
      }
    }
  }
