PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Half_DuplexCommunicationsSystem_0
                RFDevice:hasProducer  ?Entity_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?InstantaneousFrequencyMeasurementReceiver_0
                    Nuvio:aggregateOf  ?Entity_0
          { ?Component_0  Nuvio:compositeOf  ?InstantaneousFrequencyMeasurementReceiver_0 }
          { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
            FILTER ( ?DataValue0 < -929860605 )
          }
        }
      }
    }
  }
