PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?DeceptiveJamming_0
                RFDevice:supportsSpectrumSensing  ?ElectronicAttackSystem_0
      { ?DeceptiveJamming_0
                  a                     RFDevice:DeceptiveJamming
        { ?Quantity_0  RFDevice:hasPulseWidth  ?DeceptiveJamming_0 }
      }
    }
  }
