PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?Var0  RFDevice:hasCapability  ?PulseRadar_0
      {   { ?Var0    a                     Nuvio:Process .
            ?Ship_0  Nuvio:participatesIn  ?Var0
            { ?Ship_0  a                     RFDevice:Ship
              { ?Ship_0  RFDevice:supportsTransmitting  ?Var0 }
            }
          }
        UNION
          { ?Var0  a                     RFDevice:Receiving
            { ?RadioFrequencyBand_0
                        RFDevice:hasBandwidthRange  ?Var0
            }
          }
      }
    }
  }
