PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicSupportSystem_0
WHERE
  { ?ElectronicSupportSystem_0
              a                     RFDevice:ElectronicSupportSystem
    { ?InstantaneousFrequencyMeasurementReceiver_0
                Nuvio:compositeOf  ?ElectronicSupportSystem_0
      { ObjectDescription:Instance951
                  RFDevice:hasNoiseFigure  ?InstantaneousFrequencyMeasurementReceiver_0
      }
    }
  }
