PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?TrackingRadar_0
WHERE
  { ?TrackingRadar_0
              a                     RFDevice:TrackingRadar
    { ?Entity_0  RFDevice:isProducerOf  ?TrackingRadar_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?Process_0  Nuvio:isExpressedBy  ?Entity_0
        { ?Entity_0  a                    RFDevice:FrequencyShiftKeyingModulation
          { ?Entity_0  a                    RFDevice:ElectricChargeUnit }
          { ?Process_0  a                   Nuvio:Process .
            ?QuadratureAmplitudeModulation_0
                      Nuvio:subprocessOf    ?Process_0
          }
        }
      }
    }
  }
