PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?GNURadio_0
WHERE
  { ?GNURadio_0  a                  SDR:GNURadio
    { ?Var0  RFDevice:supportsTransmitting  ?GNURadio_0
      { ?Var0  a                     Nuvio:Entity ;
               Nuvio:expresses       ?InformationContent_0
        { ?Var0  a                     gml:OrientableSurface
          {   { ?Var1  Nuvio:hasValue  ?Var0
                { ?Var1  a                     RFDevice:IntegerValue }
              }
            UNION
              { ?Var0  Nuvio:hasProcessQuality  ?Quality_0
                { ?Quality_0  a                   Nuvio:Quality }
              }
          }
        }
        OPTIONAL
          { ?InformationContent_0
                      a                     Nuvio:InformationContent
          }
        { ?Var0  a                     RFDevice:CommunicationsJamming }
      }
    }
  }
