PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?SDR_0
WHERE
  { ?SDR_0  a                     SDR:SDR
    { ?Entity_0  RFDevice:hasProducer  ?SDR_0
      { ?Entity_0  a                    Nuvio:Entity
        {   { ?Entity_0  a                    gml:Clothoid }
          UNION
            { ?Entity_0  a                    RFDevice:FeatureDetection }
          { ?Entity_0  a                    RFDevice:FloatValue }
          OPTIONAL
            { ?Entity_0  a                    Nuvio:UnitOfMeasure }
        }
      }
    }
  }
