PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    OPTIONAL
      { ?Var0  RFDevice:supportsSpectrumSensing  ?Half_DuplexCommunicationsSystem_0
        {   { ?Var0  a                     Nuvio:Process }
          UNION
            {   { ?Var0  a                     RFDevice:InverseGainJamming }
              UNION
                { ?Var0  a                     RFDevice:TimeUnit
                  { ?Var0  a                     RFDevice:Ratio }
                  OPTIONAL
                    { ?UnitOfMeasure_0
                                Nuvio:hasUnitOfMeasure  ?Var0
                      {   { ?Var0  Nuvio:hasPrecision  ?DataValue0
                            FILTER ( ?DataValue0 > -1871170586 )
                          }
                        UNION
                          { ?UnitOfMeasure_0
                                      a                     Nuvio:UnitOfMeasure
                          }
                      }
                      OPTIONAL
                        { ?Var0  a                     Nuvio:Attribute }
                    }
                }
            }
        }
      }
  }
