PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?Aircraft_0  RFDevice:isDeployedOn  ?ElectronicAttackSystem_0
      { ?Aircraft_0  a                  RFDevice:Aircraft
        { ?Entity_0  RFDevice:supportsTransmitting  ?Aircraft_0
          { ?Entity_0  Nuvio:expresses  ?Entity_0
            { ObjectDescription:Angle_instance10
                        RFDevice:hasNoiseFigure  ?Entity_0
              { ?Entity_1  RFDevice:hasEffectiveRadiatedPower  ?Entity_0
                { ?Entity_0  a                    RFDevice:LongValue
                  { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                    FILTER ( ?DataValue0 <= -787273164 )
                  }
                }
              }
              OPTIONAL
                { ?Entity_0  a                    RFDevice:Percentage }
              { ?Entity_0  a                    Nuvio:Attribute }
            }
          }
        }
      }
    }
  }
