PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    OPTIONAL
      { ?Aircraft_0  RFDevice:isDeployedOn  ?Full_DuplexCommunicationsSystem_0
        { ?Entity_0  RFDevice:supportsJamming  ?Aircraft_0
          { ?Value_0  Nuvio:isExpressedBy  ?Entity_0
            { ?XC6SLX150FPGA_0
                        Nuvio:compositeOf  ?Entity_0
              { ?Entity_0  Nuvio:hasDataValue  ?DataValue0
                FILTER ( ?DataValue0 >= "-75.15370872078601"^^xsd:double )
              }
              { ?Value_0  a                     Nuvio:Value .
                RFDevice:Decibel_milliwatts
                          Nuvio:hasUnitOfMeasure  ?Value_0
                { ?Value_0  Nuvio:hasPrecision  ?DataValue1
                  FILTER ( ?DataValue1 = 906339147 )
                }
              }
            }
          }
        }
      }
  }
