PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ModelX_0
WHERE
  { ?ModelX_0  a                    RFDevice:ModelX
    { ?Entity_0  RFDevice:hasWidth  ?ModelX_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_0  a                    RFDevice:LongitudeValue }
      }
    }
  }
