PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN200_0
WHERE
  { ?USRPN200_0  a                  SDR:USRPN200
    { ?Entity_0  Nuvio:hasObjectQuantity  ?USRPN200_0
      {   { ?Entity_0  a                    Nuvio:Entity ;
                      Nuvio:expresses       ?Entity_0
          }
        UNION
          { ?Entity_0  a                    Nuvio:InformationEntity
            { ?Entity_0  a                    Nuvio:Object .
              ObjectDescription:Weight_instance87
                        RFDevice:hasVoltage   ?Entity_0
            }
          }
      }
    }
  }
