PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    OPTIONAL
      { ?PulseRadar_0
                  RFDevice:isProducerOf  ?Entity_0
        { ?Entity_0  a                    Nuvio:Entity ;
                    Nuvio:expresses       ?Entity_0
          { ?Entity_0  a                    RFDevice:FrequencyUnit
            { ?Entity_0  a                    Nuvio:InformationEntity }
            {   { ?Entity_0  a                    Nuvio:Value .
                  ?Object_0  Nuvio:hasUnitOfMeasure  ?Entity_0
                }
              UNION
                { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                  FILTER ( ?DataValue0 = -87974193 )
                }
              { ?Object_0  a                    Nuvio:Object }
            }
          }
        }
      }
  }
