PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX310_0
WHERE
  { ?USRPX310_0  a                  SDR:USRPX310
    { ?Var0  RFDevice:supportsJamming  ?USRPX310_0
      { ?InformationContent_0
                  Nuvio:expresses  ?Var0
        { ?Quantity_0  RFDevice:hasPulseRepetitionFrequency  ?Var0
          { ?Var0  a                     Nuvio:Process
            { ?Var0  a                     RFDevice:FrequencyScanRate }
          }
          { ?Var0  a                     Nuvio:Attribute }
          OPTIONAL
            { ?Var0  a                     Nuvio:InformationEntity }
          { ?InformationContent_0
                      a                     Nuvio:InformationContent .
            ?Var0     Nuvio:represents      ?InformationContent_0
          }
        }
      }
    }
  }
