PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?Var0  RFDevice:supportsTransmitting  ?ElectronicAttackSystem_0
      { ?Var0  a                     RFDevice:CommunicationsJamming
        { ObjectDescription:Power_instance35
                    RFDevice:hasTransmitPowerRange  ?Var0
        }
      }
    }
  }
