PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?TrackingRadar_0
WHERE
  { ?TrackingRadar_0
              a                     RFDevice:TrackingRadar
    { ?Var0  RFDevice:supportsTuning  ?TrackingRadar_0
      { ?Var0  a                     Nuvio:Process
        OPTIONAL
          { ?Entity_0  RFDevice:hasMaxOutputPower  ?Var0
            { ?Entity_0  a                    Nuvio:Entity
              { ?Entity_0  a                    RFDevice:DataSize
                { ?Entity_0  Nuvio:hasValue  ?Var1
                  { ?Var1  a                     RFDevice:DecimalValue
                    OPTIONAL
                      { ?Var1  Nuvio:hasPrecision  ?DataValue0
                        FILTER ( ?DataValue0 < -1054639816 )
                      }
                  }
                }
              }
            }
          }
      }
    }
  }
