PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB2xx_0
WHERE
  { ?USRPB2xx_0  a                  SDR:USRPB2xx
    { ?Entity_0  Nuvio:compositeOf  ?USRPB2xx_0
      { ?Entity_0  a                    Nuvio:Entity
        {   { ?Entity_0  a                    RFDevice:IEDJammer
              { ?SweepJamming_0
                          RFDevice:hasCapability  ?Entity_0
                { ?SweepJamming_0
                            a                     RFDevice:SweepJamming
                }
              }
            }
          UNION
            { ?Attribute_0  RFDevice:hasPulseWidth  ?Entity_0 }
          { ?Entity_0  a                    Nuvio:Object .
            ObjectDescription:TimeInterval_instance20
                      RFDevice:hasWeight    ?Entity_0
            { ?Entity_0  a                    RFDevice:LongitudeValueInRadian
              { ?Entity_0  RFDevice:hasDoubleValue  ?DataValue0 }
              { ?Entity_0  a                    Nuvio:Value ;
                          Nuvio:hasUnitOfMeasure  ?Entity_0
                { ?Entity_0  Nuvio:hasPrecision  ?DataValue1
                  FILTER ( ?DataValue1 != 1833161699 )
                }
              }
            }
          }
        }
      }
    }
  }
