PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE313_0
WHERE
  { ?USRPE313_0  a                  SDR:USRPE313
    { ?Var0  RFDevice:supportsTransmitting  ?USRPE313_0
      {   { ?Var0  a                     RFDevice:FixedBandwidthSensing }
        UNION
          { ?Var0  a                     RFDevice:DeceptiveJamming }
        { ?Var0  a                     Nuvio:Entity
          { ?Producer_0  RFDevice:isProducerOf  ?Var0
            { ?Producer_0  a                  RFDevice:Producer }
            { ?Var0  a                     Nuvio:DimensionlessUnit }
          }
        }
      }
    }
  }
