PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN310_0
WHERE
  { ?USRPN310_0  a                  SDR:USRPN310
    { ?Var0  RFDevice:supportsJamming  ?USRPN310_0
      { ?Var0  a                     Nuvio:Process
        {   { ?Var0     a                     Nuvio:Entity .
              ?Value_0  Nuvio:isExpressedBy   ?Var0
              { ?Var0  a                     RFDevice:TimeInterval
                { ?Var0  a                     Nuvio:InformationEntity .
                  ?Var1  Nuvio:informationSource  ?Var0
                  OPTIONAL
                    { ?Var1  a                     RFDevice:Jammer
                      { ?Var1  a                     RFDevice:EmitterIdentification
                        { ?Var1  a                     Nuvio:Attribute }
                      }
                    }
                }
              }
            }
          UNION
            { ?Var0  a                     RFDevice:Transmitting }
        }
      }
    }
  }
