PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarWarningReceiver_0
WHERE
  { ?RadarWarningReceiver_0
              a                     RFDevice:RadarWarningReceiver
    OPTIONAL
      { ?Entity_0  Nuvio:aggregateOf  ?RadarWarningReceiver_0
        { ?Entity_0  a                    Nuvio:Entity ;
                    Nuvio:isExpressedBy   ?Attribute_0
          {   { ?Entity_0  a                    RFDevice:AnalogModulation
                {   { ?Entity_0  a                    RFDevice:FloatValue
                      { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                        FILTER ( ?DataValue0 < -1652098673 )
                      }
                    }
                  UNION
                    { ?Entity_0  a                    Nuvio:InformationEntity .
                      ?Var0     Nuvio:informationSource  ?Entity_0
                      { ?Var0  a                     Nuvio:Value }
                    }
                }
              }
            UNION
              { ?Attribute_0  a                 Nuvio:Attribute }
          }
        }
      }
  }
