PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB2xxmini_0
WHERE
  { ?USRPB2xxmini_0
              a                     SDR:USRPB2xxmini
    { ?Var0  RFDevice:supportsJamming  ?USRPB2xxmini_0
      { ?Var0  a                     RFDevice:SpectrumSensing
        { ObjectDescription:Frequency_instance68
                    RFDevice:hasBandwidth  ?Var0
          { ?Var0  RFDevice:hasBandwidthRange  ?Entity_0
            {   { ?Entity_0  a                    Nuvio:Entity ;
                            Nuvio:isExpressedBy   ?Object_0
                  { ?Entity_0  a                    RFDevice:IEDTrigger
                    OPTIONAL
                      { ?Ratio_0  RFDevice:hasNoiseFigure  ?Entity_0 }
                  }
                }
              UNION
                {   { ?StandoffJamming_0
                                RFDevice:supportsTransmitting  ?Object_0
                    }
                  UNION
                    { ?StandoffJamming_0
                                a                     RFDevice:StandoffJamming
                      OPTIONAL
                        { ?Attribute_0  RFDevice:hasPulseRepetitionFrequency  ?StandoffJamming_0 }
                    }
                }
            }
          }
        }
        { ?Var0  a                     RFDevice:CrossEyeJamming }
        { ?Var0  a                     Nuvio:Process }
      }
    }
  }
