PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE3xx_0
WHERE
  { ?USRPE3xx_0  a                  SDR:USRPE3xx
    { ?USRPE3xx_0  RFDevice:hasBeamwidth  ?Entity_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_0  a                    RFDevice:JammingSystem
          { ?Entity_0  a                    RFDevice:PositiveFloatValue }
          { ObjectDescription:Frequency_instance18
                      Nuvio:relevantIndividual  ?Entity_0
          }
        }
      }
    }
  }
