PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN2xx_0
WHERE
  { ?USRPN2xx_0  a                  SDR:USRPN2xx
    { ?Entity_0  RFDevice:hasBeamwidth  ?USRPN2xx_0
      { ?Entity_0  Nuvio:hasDataValue  ?DataValue0
        FILTER ( ?DataValue0 >= -652664258 )
        { ?Var0  Nuvio:informationSource  ?Entity_0 }
        { ?Entity_0  a                    Nuvio:Process .
          ?FrequencyAccuracy_0
                    RFDevice:hasPulseRepetitionFrequency  ?Entity_0
          { ?Var1  Nuvio:hasValue  ?FrequencyAccuracy_0
            { ?Var1  a                     RFDevice:FloatValue }
          }
        }
      }
    }
  }
