PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN200_0
WHERE
  { ?USRPN200_0  a                  SDR:USRPN200
    { ?Var0  Nuvio:compositeOf  ?USRPN200_0
      { ?Var0  a                     Nuvio:Entity
        { ?Var0  a                     RFDevice:AngleValue
          { ?Var0  Nuvio:hasPrecision  ?DataValue0
            FILTER ( ?DataValue0 < 962935853 )
          }
        }
      }
    }
  }
