PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?GNURadio_0
WHERE
  { ?GNURadio_0  a                  SDR:GNURadio
    { ?Var0  RFDevice:hasCapability  ?GNURadio_0
      { ?Var0  a                     Nuvio:Entity
        { ?Var0  a                     RFDevice:Jamming
          { ?Attribute_0  RFDevice:hasPulseRepetitionFrequency  ?Var0
            { ?Attribute_0  a                 Nuvio:Attribute }
          }
          { ?Var0  a                     RFDevice:FrequencyScanRate
            { ?Var1  Nuvio:hasValue  ?Var0
              { ?Var1  a                     RFDevice:PositiveIntegerValue
                { ?Var1  RFDevice:hasFloatValue  ?DataValue0
                  FILTER ( ?DataValue0 = 75.04 )
                }
              }
            }
          }
        }
      }
    }
  }
