PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    OPTIONAL
      { ?Entity_0  RFDevice:hasBeamwidth  ?PulseRadar_0
        { ?Entity_0  a                    Nuvio:Entity ;
                    Nuvio:expresses       ?UnitOfMeasure_0
          { ?Entity_0  a                    RFDevice:ElectricChargeUnit
            { ?Entity_0  a                    RFDevice:Time
              { ?Var0  Nuvio:hasValue  ?Entity_0 }
              { ?Entity_0  a                    Nuvio:Process }
            }
            OPTIONAL
              { ?UnitOfMeasure_0
                          a                     Nuvio:UnitOfMeasure
              }
          }
        }
      }
  }
