PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Jammer_0  Nuvio:partOf  ?Half_DuplexCommunicationsSystem_0
      { ?Jammer_0  RFDevice:hasProducer  ?Object_0
        { ?Object_0  Nuvio:hasObjectQuality  ObjectDescription:AntennaPolarization_instance15 }
      }
    }
  }
