PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB205mini_i_0
WHERE
  { ?USRPB205mini_i_0
              a                     SDR:USRPB205mini-i
    OPTIONAL
      { ?Var0  RFDevice:supportsTuning  ?USRPB205mini_i_0
        {   { ?Var0  a                     RFDevice:SpectrumSensing }
          UNION
            { ?Object_0  RFDevice:hasBandwidthRange  ?Var0
              { ?Object_0  a                    Nuvio:Object .
                ?Time_0   RFDevice:hasNoiseFigure  ?Object_0
                { ?Time_0  a                     RFDevice:Time }
              }
            }
          { ?Var0  a                     RFDevice:Receiving
            { ?RadarFrequencyBand_0
                        RFDevice:hasBandwidthRange  ?Var0
            }
          }
        }
      }
  }
