PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX300_0
WHERE
  { ?USRPX300_0  a                  SDR:USRPX300
    { ?Aircraft_0  RFDevice:isDeployedOn  ?USRPX300_0
      { ?Aircraft_0  a                  RFDevice:Aircraft
        { ?Process_0  RFDevice:supportsTransmitting  ?Aircraft_0
          { ?Process_0  a                   Nuvio:Process .
            ?Attribute_0  RFDevice:hasMaxOutputPower  ?Process_0
          }
        }
      }
    }
  }
