PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?USRPX300_0
WHERE
  { ?USRPX300_0  a                  SDR:USRPX300
    { SDR:Length_27_7cm
                RFDevice:hasLength  ?USRPX300_0
    }
  }
