PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarWarningReceiver_0
WHERE
  { ?RadarWarningReceiver_0
              a                     RFDevice:RadarWarningReceiver
    { ?Var0  RFDevice:supportsTransmitting  ?RadarWarningReceiver_0
      { ?Var0     a                     Nuvio:Entity .
        ?InformationEntity_0
                  Nuvio:isExpressedBy   ?Var0
        OPTIONAL
          {   { ?Var0  a                     RFDevice:RadioComponent
                { ?InstantaneousFrequencyMeasurementReceiver_0
                            Nuvio:partOf  ?Var0
                  { ?FreqencyRange_0
                              RFDevice:hasFrequencyAccuracy  ?InstantaneousFrequencyMeasurementReceiver_0
                    { ?FreqencyRange_0
                                a                     RFDevice:FreqencyRange
                    }
                  }
                }
              }
            UNION
              { ?Var0  a                     RFDevice:VelocityUnit
                { ?Var0  a                     RFDevice:LongValue }
              }
            { ?Var0  a                     Nuvio:Value
              { ?Var0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 = 1877933585 )
              }
            }
            { ?InformationEntity_0
                        a                     Nuvio:InformationEntity
            }
          }
        { ?Var0  a                     RFDevice:Receiving }
      }
    }
  }
