PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE310_0
WHERE
  { ?USRPE310_0  a                  SDR:USRPE310
    { ?USRPE310_0  RFDevice:hasCapability  ?Var0
      { ?Var1  RFDevice:hasPulseRepetitionInterval  ?Var0
        { ?Var1  a                     RFDevice:Power
          { ?Var1  Nuvio:hasValue  ?Var2
            { ?Var2  Nuvio:hasUnitOfMeasure  ?UnitOfMeasure_0
              { ?UnitOfMeasure_0
                          a                     Nuvio:UnitOfMeasure
              }
            }
          }
        }
      }
    }
  }
