PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?RadarModulation_0
                RFDevice:supportsSpectrumSensing  ?PulseRadar_0
      { ?RadarModulation_0
                  a                     RFDevice:RadarModulation
      }
    }
  }
