PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicSupportSystem_0
WHERE
  { ?ElectronicSupportSystem_0
              a                     RFDevice:ElectronicSupportSystem
    { ?IEDJammer_0  Nuvio:aggregateOf  ?ElectronicSupportSystem_0
      { ?IEDJammer_0  a                 RFDevice:IEDJammer
        OPTIONAL
          { ?SweptSpotJamming_0
                      RFDevice:hasCapability  ?IEDJammer_0
          }
      }
    }
  }
