PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    OPTIONAL
      { ?Var0  RFDevice:supportsSpectrumSensing  ?SurveillanceRadar_0
        { ?Var0  a                     Nuvio:Process
          OPTIONAL
            {   { ?Var0  a                     gml:GeodesicString }
              UNION
                { ?Var0  a                     Nuvio:UnitOfMeasure }
              { ?Var0  a                     Nuvio:Object }
            }
        }
      }
  }
