PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?PulseRadar_0
                Nuvio:aggregateOf  ?SuperheterodyneReceiver_0
      { ?SuperheterodyneReceiver_0
                  a                     RFDevice:SuperheterodyneReceiver
        { ?Producer_0  RFDevice:hasProducer  ?SuperheterodyneReceiver_0
          { ?Producer_0  a                  RFDevice:Producer }
        }
      }
    }
  }
