PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE310_0
WHERE
  { ?USRPE310_0  a                  SDR:USRPE310
    { ?Entity_0  RFDevice:hasWeight  ?USRPE310_0
      {   { ?Process_0  Nuvio:isExpressedBy  ?Entity_0 }
        UNION
          {   { ?Entity_0  a                    RFDevice:GainRange }
            UNION
              { ?Entity_0  a                    RFDevice:FixedBandwidthSensing
                { SDR:Freq_100MHz
                            RFDevice:hasBandwidth  ?Entity_0
                }
              }
            { ?Entity_0  Nuvio:hasUnitOfMeasure  RFDevice:AngleUnit_Degree }
          }
      }
    }
  }
