PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarSystem_0
WHERE
  { ?RadarSystem_0
              a                     RFDevice:RadarSystem
    { ?Entity_0  Nuvio:hasObjectQuantity  ?RadarSystem_0
      { ?Situation_0  Nuvio:expresses  ?Entity_0
        { ?Situation_0  a                 Nuvio:Situation
          OPTIONAL
            { ObjectDescription:GNURadio_instance20
                        Nuvio:relevantIndividual  ?Situation_0
            }
        }
      }
    }
  }
