PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE313_0
WHERE
  { ?USRPE313_0  a                  SDR:USRPE313
    { ?USRPE313_0  Nuvio:aggregateOf  ?Entity_0
      { ?Entity_0  a                    Nuvio:Entity
        { ObjectDescription:Producer_instance93
                    RFDevice:hasProducer  ?Entity_0
          { ?Entity_0  a                    RFDevice:SpatialLinearUnit }
          {   { ?Receiver_0  Nuvio:relevantIndividual  ?Entity_0 }
            UNION
              { ?AutomaticGainControl_0
                          Nuvio:relevantIndividual  ?Entity_0
                { ObjectDescription:Power_instance28
                            RFDevice:hasTransmitPowerRange  ?AutomaticGainControl_0
                }
              }
          }
        }
      }
    }
  }
