PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>

SELECT DISTINCT  ?BistaticRadar_0
WHERE
  { ?BistaticRadar_0
              a                     RFDevice:BistaticRadar
    OPTIONAL
      { ?PulseDopplerRadarModulation_0
                  RFDevice:supportsTransmitting  ?BistaticRadar_0
        { ?PulseDopplerRadarModulation_0
                    a                     RFDevice:PulseDopplerRadarModulation
          { ?PulseDopplerRadarModulation_0
                      RFDevice:hasPulseWidth  ObjectDescription:TimeInterval_instance8
          }
        }
      }
  }
