PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?USRPB205mini_i_0
WHERE
  { ?USRPB205mini_i_0
              a                     SDR:USRPB205mini-i
    { ?Entity_0  Nuvio:aggregateOf  ?USRPB205mini_i_0
      { ?Entity_0  a                    gml:AbstractSurfacePatch
        OPTIONAL
          { ?Entity_0  a                    RFDevice:ElectricChargeUnit }
        { ?Entity_0  a                    Nuvio:InformationEntity .
          ?LatitudeValue_0
                    Nuvio:isExpressedBy   ?Entity_0
          { ?LatitudeValue_0
                      Nuvio:hasPrecision  ?DataValue0
            FILTER ( ?DataValue0 < 1673716144 )
          }
        }
      }
    }
  }
