PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?USRPX300_0
WHERE
  { ?USRPX300_0  a                  SDR:USRPX300
    { ?Aircraft_0  RFDevice:isDeployedOn  ?USRPX300_0
      {   { ?Aircraft_0  a                  RFDevice:Aircraft }
        UNION
          { ObjectDescription:Moving_instance15
                      RFDevice:supportsTuning  ?Aircraft_0
          }
      }
    }
  }
