PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ContinuousWaveRadar_0
WHERE
  { ?ContinuousWaveRadar_0
              a                     RFDevice:ContinuousWaveRadar
    OPTIONAL
      { ?Entity_0  Nuvio:aggregateOf  ?ContinuousWaveRadar_0
        { ?Value_0  Nuvio:isExpressedBy  ?Entity_0
          { ?Entity_0  a                    RFDevice:ElectronicProtection
            { ?Entity_0  a                    RFDevice:PowerUnit
              OPTIONAL
                { ?Entity_0  RFDevice:hasDecimalValue  ?DataValue0
                  FILTER ( ?DataValue0 >= 2127352591 )
                }
            }
            { ?Value_0  a                     Nuvio:Value .
              ?Entity_0  Nuvio:hasUnitOfMeasure  ?Value_0
            }
          }
        }
      }
  }
