PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?Var0  RFDevice:hasCapability  ?PulseRadar_0
      { ?Var0     a                     Nuvio:Entity .
        ?Value_0  Nuvio:expresses       ?Var0
        { ?Var0  a                     Nuvio:Situation }
        OPTIONAL
          {   { ?Value_0  a                     Nuvio:Value .
                ?VoltageUnit_0
                          Nuvio:hasUnitOfMeasure  ?Value_0
              }
            UNION
              { ?Value_0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 > -1062617013 )
                { ?VoltageUnit_0
                            a                     RFDevice:VoltageUnit
                }
              }
          }
      }
    }
  }
