PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?USRPE3xx_0
WHERE
  { ?USRPE3xx_0  a                  SDR:USRPE3xx
    { ?Var0  RFDevice:supportsSpectrumSensing  ?USRPE3xx_0
      { ?Var0  a                     RFDevice:SpotJamming
        {   { ?Var0  a                     skos:OrderedCollection
              { ?Var0  a                     RFDevice:Tuning }
              OPTIONAL
                { ?Var0  a                     RFDevice:LatitudeValueInRadian }
            }
          UNION
            { ?CompositeSolid_0
                        Nuvio:relevantIndividual  ?Var0
              { ?CompositeSolid_0
                          a                     gml:CompositeSolid
              }
            }
        }
      }
    }
  }
