PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  geosparql: <http://www.opengis.net/ont/geosparql#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?USRPB2xx_0
WHERE
  { ?USRPB2xx_0  a                  SDR:USRPB2xx
    OPTIONAL
      { ?Entity_0  Nuvio:compositeOf  ?USRPB2xx_0
        { ?Entity_0  a                    geosparql:SpatialObject ;
                    geosparql:rcc8eq      ?MultiGeometry_0
          { ?MultiGeometry_0
                      a                     gml:MultiGeometry
          }
          {   { ?Entity_0  a                    RFDevice:LongitudeValue }
            UNION
              { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 != 1660633435 )
              }
            { ?Entity_0  a                    Nuvio:Object }
          }
        }
      }
  }
