PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB2xxmini_0
WHERE
  { ?USRPB2xxmini_0
              a                     SDR:USRPB2xxmini
    OPTIONAL
      { ?Entity_0  RFDevice:isProducerOf  ?USRPB2xxmini_0
        { ?Entity_0  Nuvio:isExpressedBy  ?Entity_0
          { ?Entity_0  a                    RFDevice:RangeGatePullOffJamming
            { ObjectDescription:USRPN200_instance37
                        Nuvio:relevantIndividual  ?Entity_0
              { ?Entity_0  a                    Nuvio:Value
                { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                  FILTER ( ?DataValue0 <= -1785552741 )
                }
              }
              {   { ?Entity_0  a                    RFDevice:Angle
                    { ObjectDescription:LongitudeValue_instance0
                                Nuvio:hasValue  ?Entity_0
                    }
                  }
                UNION
                  { ?Entity_0  a                    Nuvio:InformationRepresentation ;
                              Nuvio:represents      ?InformationEntity_0
                  }
              }
            }
          }
        }
      }
  }
