PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?USRPN310_0
WHERE
  { ?USRPN310_0  a                  SDR:USRPN310
    { ?Var0  RFDevice:hasWeight  ?USRPN310_0 }
  }
