PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?Var0  RFDevice:supportsTuning  ?SurveillanceRadar_0
      {   { ?Var0  Nuvio:isExpressedBy  ?Object_0
            { ?Height_0  RFDevice:hasBeamwidth  ?Object_0
              { ?Var1  Nuvio:hasValue  ?Height_0
                { ?Entity_0  Nuvio:hasUnitOfMeasure  ?Var1 }
              }
            }
          }
        UNION
          { ?Var0  a                     RFDevice:Transceiving
            {   { ?Var0  a                     RFDevice:SweepJamming }
              UNION
                { ?Attribute_0  Nuvio:hasProcessQuantity  ?Var0
                  { ?Attribute_0  a                 Nuvio:Attribute }
                }
            }
          }
      }
    }
  }
