PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?BistaticRadar_0
WHERE
  { ?BistaticRadar_0
              a                     RFDevice:BistaticRadar
    OPTIONAL
      { ?BistaticRadar_0
                  Nuvio:partOf  ?InstantaneousFrequencyMeasurementReceiver_0
        { ?InstantaneousFrequencyMeasurementReceiver_0
                    a                     RFDevice:InstantaneousFrequencyMeasurementReceiver
          { ?InstantaneousFrequencyMeasurementReceiver_0
                      Nuvio:partOf  ?Component_0
            { ?Component_0  a                 RFDevice:Component }
          }
        }
      }
  }
