PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB205mini_i_0
WHERE
  { ?USRPB205mini_i_0
              a                     SDR:USRPB205mini-i
    { ?USRPB205mini_i_0
                Nuvio:partOf  ?Spartan6FPGA_0
      { ?Spartan6FPGA_0
                  a                     SDR:Spartan6FPGA
      }
    }
  }
