PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SearchRadar_0
WHERE
  { ?SearchRadar_0
              a                     RFDevice:SearchRadar
    { ?Entity_0  Nuvio:partOf  ?SearchRadar_0
      { ?Entity_0  Nuvio:isExpressedBy  ?UnitOfMeasure_0
        { ?Entity_0  a                    RFDevice:AmplitudeShiftKeyingModulation
          OPTIONAL
            { ?Var0  Nuvio:hasValue  ?Entity_0
              { ?Var0  a                     RFDevice:DecimalValue }
            }
          { ?Entity_0  a                    Nuvio:UnitOfMeasure }
        }
      }
    }
  }
