PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarSystem_0
WHERE
  { ?RadarSystem_0
              a                     RFDevice:RadarSystem
    OPTIONAL
      { ?RadioComponent_0
                  Nuvio:compositeOf  ?RadarSystem_0
        { ?RadioComponent_0
                    a                     RFDevice:RadioComponent
          { ?RadioComponent_0
                      RFDevice:hasProducer  ?Object_0
            { ?Object_0  a                    Nuvio:Object .
              ?AntennaPolarization_0
                        Nuvio:hasObjectQuality  ?Object_0
            }
          }
        }
      }
  }
