PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { ?Entity_0  RFDevice:hasProducer  ?JammingSystem_0
      { ?Entity_0  a                    Nuvio:Entity
        {   { ?Entity_0  a                    SDR:Series7FPGA }
          UNION
            { ?Var0  RFDevice:isProducerOf  ?Entity_0 }
          OPTIONAL
            {   { ?Entity_0  a                    Nuvio:Situation }
              UNION
                { ?Modulator_0  Nuvio:relevantIndividual  ?Entity_0
                  { ?Modulator_0  a                 RFDevice:Modulator
                    { ?Process_0  RFDevice:supportsSpectrumSensing  ?Modulator_0 }
                  }
                }
            }
        }
      }
    }
  }
