PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    OPTIONAL
      { ?SurveillanceRadar_0
                  RFDevice:hasProducer  ?Entity_0
        { ?Entity_0  a                    Nuvio:Entity .
          ?Object_0  Nuvio:expresses      ?Entity_0
          { ?Entity_0  a                    RFDevice:FrequencyUnit
            { ?Entity_0  a                    RFDevice:LatitudeValueInRadian
              { ?Entity_0  a                    RFDevice:Height
                { ?Entity_0  Nuvio:hasValue  ?Var0 }
              }
              { ?Entity_0  Nuvio:participatesIn  ObjectDescription:RadioFrequencyBand_instance42 }
            }
            { ?Object_0  a                    Nuvio:Object }
          }
        }
      }
  }
