PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    OPTIONAL
      { ?Half_DuplexCommunicationsSystem_0
                  RFDevice:isProducerOf  ?Entity_0
        { ?Entity_0  Nuvio:isExpressedBy  ?InformationContent_0
          {   { ?Entity_0  a                    RFDevice:AutomaticGainControl
                { SDR:Power_15dBm
                            RFDevice:hasMaxOutputPower  ?Entity_0
                }
                { ?Entity_0  a                    Nuvio:DimensionlessUnit
                  { ?Entity_0  a                    RFDevice:LongitudeValueInRadian }
                  {   { ?Entity_0  a                    Nuvio:Value .
                        RFDevice:MilliampereHour
                                  Nuvio:hasUnitOfMeasure  ?Entity_0
                      }
                    UNION
                      { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                        FILTER ( ?DataValue0 <= -135991397 )
                      }
                  }
                  { ?Entity_0  a                    Nuvio:Process }
                }
              }
            UNION
              { ?InformationRepresentation_0
                          Nuvio:represents  ?InformationContent_0
              }
          }
        }
      }
  }
