PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?DRFMJamming_0
                RFDevice:supportsJamming  ?ElectronicAttackSystem_0
      { ?DRFMJamming_0
                  a                     RFDevice:DRFMJamming
      }
    }
  }
