PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    OPTIONAL
      { ?ElectronicAttackSystem_0
                  RFDevice:isProducerOf  ?Entity_0
        { ?Entity_0  a                    Nuvio:Entity .
          ?Object_0  Nuvio:isExpressedBy  ?Entity_0
          { ?Entity_0  a                    RFDevice:Amplifier
            { ?Entity_0  RFDevice:isProducerOf  ?Producer_0 }
            { ?Entity_0  Nuvio:hasValue  ?Var0
              { ?Entity_1  Nuvio:hasUnitOfMeasure  ?Var0 }
              { ?Entity_0  a                    Nuvio:Object }
            }
          }
        }
      }
  }
