PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CR_0
WHERE
  { ?CR_0  a                     SDR:CR
    { ?Var0  RFDevice:supportsJamming  ?CR_0
      { ?Value_0  Nuvio:expresses  ?Var0
        { ?Entity_0  RFDevice:hasMaxOutputPower  ?Var0 }
        OPTIONAL
          { ?Value_0  a                     Nuvio:Value ;
                      Nuvio:hasUnitOfMeasure  ?Value_0
            { ?Value_0  Nuvio:hasPrecision  ?DataValue0
              FILTER ( ?DataValue0 < 1893494824 )
            }
          }
      }
    }
  }
