PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    OPTIONAL
      { ?SurveillanceRadar_0
                  RFDevice:isProducerOf  ?Entity_0
        { ?Entity_0  a                    Nuvio:Entity .
          ?Situation_0  Nuvio:isExpressedBy  ?Entity_0
          {   { ?Entity_0  a                    RFDevice:ElectricChargeUnit }
            UNION
              { ?Entity_0  a                    RFDevice:LatitudeValue
                { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                  FILTER ( ?DataValue0 > 1734308035 )
                }
              }
            { ?Entity_0  a                    Nuvio:Process }
          }
          OPTIONAL
            { ?BSpline_0  Nuvio:relevantIndividual  ?Situation_0
              { ?BSpline_0  a                   gml:BSpline }
            }
        }
      }
  }
