PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SearchRadar_0
WHERE
  { ?SearchRadar_0
              a                     RFDevice:SearchRadar
    OPTIONAL
      { ?SearchRadar_0
                  RFDevice:isProducerOf  ?Entity_0
        { ?Entity_1  Nuvio:expresses  ?Entity_0
          { ?Entity_0  a                    Nuvio:Object .
            ?FrequencyShiftKeyingModulation_0
                      RFDevice:supportsJamming  ?Entity_0
            { ?FrequencyShiftKeyingModulation_0
                        a                     RFDevice:FrequencyShiftKeyingModulation
            }
            { ?Entity_0  a                    Nuvio:Process }
          }
        }
      }
  }
