PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?GNURadio_0
WHERE
  { ?GNURadio_0  a                  SDR:GNURadio
    { ?Aircraft_0  RFDevice:isDeployedOn  ?GNURadio_0
      { ?Aircraft_0  a                  RFDevice:Aircraft
        { ?Aircraft_0  RFDevice:supportsTransmitting  ?Entity_0
          {   { ?Entity_0  a                    RFDevice:ADC }
            UNION
              { ?Entity_0  a                    RFDevice:LatitudeValueInRadian
                { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                  FILTER ( ?DataValue0 >= -938251840 )
                }
                OPTIONAL
                  { ?Entity_0  a                    Nuvio:Situation .
                    ?DAC_0    Nuvio:relevantIndividual  ?Entity_0
                    { ObjectDescription:Instance2517
                                Nuvio:compositeOf  ?DAC_0
                    }
                  }
              }
          }
        }
      }
    }
  }
