PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB200mini_i_0
WHERE
  { ?USRPB200mini_i_0
              a                     SDR:USRPB200mini-i
    { ?Weight_0  RFDevice:hasWeight  ?USRPB200mini_i_0
      { ?Var0  Nuvio:hasValue  ?Weight_0
        { ?Var0  a                     RFDevice:PositiveFloatValue
          { ?Var0  RFDevice:hasDecimalValue  ?DataValue0
            FILTER ( ?DataValue0 = "-94.33998"^^xsd:double )
          }
          { ?Var0  RFDevice:hasFloatValue  ?DataValue1
            FILTER ( ?DataValue1 > "0.0"^^xsd:double )
          }
        }
      }
    }
  }
