PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN210_0
WHERE
  { ?USRPN210_0  a                  SDR:USRPN210
    OPTIONAL
      { ?Entity_0  RFDevice:isProducerOf  ?USRPN210_0
        {   { ?Entity_0  a                    Nuvio:Entity .
              ?Object_0  Nuvio:expresses      ?Entity_0
            }
          UNION
            { ?Object_0  a                    Nuvio:Object .
              ?EmitterIdentification_0
                        Nuvio:participatesIn  ?Object_0
            }
        }
      }
  }
