PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SDR_0
WHERE
  { ?SDR_0  a                     SDR:SDR
    { ?Entity_0  RFDevice:hasProducer  ?SDR_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?Object_0  Nuvio:isExpressedBy  ?Entity_0
        {   { ?Entity_0  a                    RFDevice:LongitudeValue }
          UNION
            { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
              FILTER ( ?DataValue0 <= -67464299 )
            }
          { ?Entity_0  a                    Nuvio:Value .
            ?SpatialAreaUnit_0
                      Nuvio:hasUnitOfMeasure  ?Entity_0
            { ?SpatialAreaUnit_0
                        a                     RFDevice:SpatialAreaUnit
            }
          }
          { ?StandoffJamming_0
                      Nuvio:hasParticipant  ?Object_0
            { ?StandoffJamming_0
                        RFDevice:hasPulseWidth  ?Attribute_0
            }
          }
        }
      }
    }
  }
