PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?Ship_0  RFDevice:isDeployedOn  ?PulseRadar_0
      { ?Ship_0  a                     RFDevice:Ship
        { ?Ship_0  RFDevice:supportsTuning  ?Process_0
          { ?Process_0  a                   Nuvio:Process .
            ?InformationEntity_0
                      Nuvio:participatesIn  ?Process_0
            { ?InformationEntity_0
                        a                     Nuvio:InformationEntity
            }
          }
        }
      }
    }
  }
