PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    { ?Entity_0  Nuvio:partOf  ?Full_DuplexCommunicationsSystem_0
      {   { ?Entity_0  a                    Nuvio:Entity .
            ?InformationEntity_0
                      Nuvio:expresses       ?Entity_0
            { ?Entity_0  a                    Nuvio:Situation
              { ?Composite_0  Nuvio:relevantIndividual  ?Entity_0 }
              { ?Entity_0  a                    RFDevice:QuadratureAmplitudeModulation
                { ?Entity_0  a                    RFDevice:AngleUnit }
              }
              { ?Entity_0  a                    RFDevice:Length }
            }
          }
        UNION
          { ?Cylinder_0  Nuvio:expresses  ?InformationEntity_0 }
      }
    }
  }
