PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CommunicationsSystem_0
WHERE
  { ?CommunicationsSystem_0
              a                     RFDevice:CommunicationsSystem
    { ?Submarine_0  RFDevice:isDeployedOn  ?CommunicationsSystem_0
      { ?Submarine_0  a                 RFDevice:Submarine
        OPTIONAL
          { ?Entity_0  RFDevice:supportsJamming  ?Submarine_0
            {   { ?Process_0  Nuvio:isExpressedBy  ?Entity_0 }
              UNION
                {   { ?Processor_0  Nuvio:compositeOf  ?Entity_0
                      { ?Processor_0  a                 RFDevice:Processor
                        OPTIONAL
                          { ?Spartan6FPGA_0
                                      Nuvio:partOf  ?Processor_0
                          }
                      }
                      { ?Entity_0  a                    RFDevice:VoltageUnit }
                      { ?Entity_0  a                    Nuvio:Situation .
                        ObjectDescription:SearchRadar_instance21
                                  Nuvio:relevantIndividual  ?Entity_0
                      }
                    }
                  UNION
                    { ?Process_0  a                   Nuvio:Process }
                }
            }
          }
      }
    }
  }
