PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CommunicationsSystem_0
WHERE
  { ?CommunicationsSystem_0
              a                     RFDevice:CommunicationsSystem
    OPTIONAL
      { ?CommunicationsSystem_0
                  RFDevice:supportsTransmitting  ?Process_0
        { ?ElectricCharge_0
                    RFDevice:hasMaxSensedPower  ?Process_0
          { ?Var0  Nuvio:hasValue  ?ElectricCharge_0
            { ?Var0  a                     Nuvio:Entity
              OPTIONAL
                { ?Var0  a                     RFDevice:SpatialLinearUnit
                  { ?Var0  a                     RFDevice:Voltage
                    { ?Var0  a                     Nuvio:InformationContent ;
                             Nuvio:represents      ?InformationRepresentation_0
                      { ?InformationRepresentation_0
                                  a                     Nuvio:InformationRepresentation
                      }
                    }
                  }
                }
            }
          }
        }
      }
  }
