PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE313_0
WHERE
  { ?USRPE313_0  a                  SDR:USRPE313
    { ?Var0  RFDevice:supportsJamming  ?USRPE313_0
      { ?Var0  a                     RFDevice:CommunicationsJamming
        { ?Entity_0  RFDevice:hasTransmitPowerRange  ?Var0
          { ?Situation_0  Nuvio:expresses  ?Entity_0
            { ?Entity_0  a                    RFDevice:Filter
              OPTIONAL
                {   { ?Entity_0  a                    RFDevice:FrequencyUnit }
                  UNION
                    { ?Entity_0  a                    Nuvio:Situation
                      { ?PowerRange_0
                                  Nuvio:relevantIndividual  ?Entity_0
                        { ?PowerRange_0
                                    RFDevice:hasMax  ?Gain_0
                          { ?Gain_0  a                     RFDevice:Gain }
                        }
                      }
                    }
                }
            }
          }
        }
      }
    }
  }
