PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  sf:   <http://www.opengis.net/ont/sf#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?USRPB200mini_i_0
WHERE
  { ?USRPB200mini_i_0
              a                     SDR:USRPB200mini-i
    { ?Entity_0  RFDevice:hasProducer  ?USRPB200mini_i_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?Situation_0  Nuvio:expresses   ?Entity_0
        { ?Entity_0  a                    RFDevice:SpatialAreaUnit
          { ?Entity_0  a                    Nuvio:Attribute
            OPTIONAL
              { ?Entity_0  a                    Nuvio:Object ;
                          Nuvio:participatesIn  ?FixedBandwidthSensing_0
                { ?Attribute_0  RFDevice:hasBandwidth  ?FixedBandwidthSensing_0 }
              }
          }
          {   {   { ?Situation_0  a                 Nuvio:Situation .
                    ?LinearRing_0
                              Nuvio:relevantIndividual  ?Situation_0
                  }
                UNION
                  { ?CompositeCurve_0
                              Nuvio:relevantIndividual  ?Situation_0
                    { ?CompositeCurve_0
                                a                     gml:CompositeCurve
                    }
                  }
              }
            UNION
              { ?LinearRing_0
                          a                     sf:LinearRing
              }
          }
        }
      }
    }
  }
