PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SDR_0
WHERE
  { ?SDR_0  a                     SDR:SDR
    OPTIONAL
      { ?Var0  RFDevice:supportsTuning  ?SDR_0
        { ?Var0  a                     RFDevice:SpectrumSensing
          { ?Var0  a                     RFDevice:Jamming
            { ?Quantity_0  RFDevice:hasPulseWidth  ?Var0 }
            { ?Var0  a                     Nuvio:Entity
              { ?Var0  a                     RFDevice:Receiving
                { ?Var0     a                     Nuvio:Value .
                  ?FrequencyScanRateUnit_0
                            Nuvio:hasUnitOfMeasure  ?Var0
                  { ?FrequencyScanRateUnit_0
                              a                     RFDevice:FrequencyScanRateUnit
                  }
                }
              }
            }
          }
        }
      }
  }
