PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    OPTIONAL
      { ?Aircraft_0  RFDevice:isDeployedOn  ?PulseRadar_0
        { ?Aircraft_0  a                  RFDevice:Aircraft
          { ?Moving_0  RFDevice:supportsSpectrumSensing  ?Aircraft_0 }
        }
      }
  }
