PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>

SELECT DISTINCT  ?SearchRadar_0
WHERE
  { ?SearchRadar_0
              a                     RFDevice:SearchRadar
    { ?Satellite_0  RFDevice:isDeployedOn  ?SearchRadar_0
      { ?Satellite_0  a                 RFDevice:Satellite
        OPTIONAL
          { ?Satellite_0  RFDevice:hasCapability  ObjectDescription:Moving_instance33 }
      }
    }
  }
