PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarSystem_0
WHERE
  { ?RadarSystem_0
              a                     RFDevice:RadarSystem
    { ?Var0  RFDevice:supportsJamming  ?RadarSystem_0
      {   { ?Var0     a                     Nuvio:Entity .
            ?Situation_0  Nuvio:isExpressedBy  ?Var0
            { ?Var0  Nuvio:hasPrecision  ?DataValue0
              FILTER ( ?DataValue0 != 207159436 )
            }
          }
        UNION
          { ?Platform_0  Nuvio:relevantIndividual  ?Situation_0 }
      }
    }
  }
