PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>

SELECT DISTINCT  ?BistaticRadar_0
WHERE
  { ?BistaticRadar_0
              a                     RFDevice:BistaticRadar
    { ?PulseDopplerRadarModulation_0
                RFDevice:supportsJamming  ?BistaticRadar_0
      {   { ?PulseDopplerRadarModulation_0
                      a                     RFDevice:PulseDopplerRadarModulation
          }
        UNION
          { ObjectDescription:TimeInterval_instance0
                      RFDevice:hasEffectiveRadiatedPower  ?PulseDopplerRadarModulation_0
          }
      }
    }
  }
