PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarWarningReceiver_0
WHERE
  { ?RadarWarningReceiver_0
              a                     RFDevice:RadarWarningReceiver
    OPTIONAL
      { ?Var0  RFDevice:supportsJamming  ?RadarWarningReceiver_0
        { ?Var0  Nuvio:isExpressedBy  ?Object_0
          { ?Var0  a                     RFDevice:SpatialAreaUnit
            OPTIONAL
              { ?Var0  a                     RFDevice:Time }
            { ?Var0  a                     Nuvio:Attribute }
            OPTIONAL
              { ?Object_0  a                    Nuvio:Object }
          }
        }
      }
  }
