PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE312_0
WHERE
  { ?USRPE312_0  a                  SDR:USRPE312
    { ?Var0  RFDevice:supportsTransmitting  ?USRPE312_0
      { ?Var0  a                     RFDevice:SpectrumSensing
        OPTIONAL
          { ?Entity_0  RFDevice:hasBandwidth  ?Var0
            { ?Entity_0  a                    gml:LineString
              OPTIONAL
                { ?Entity_0  a                    RFDevice:TimeUnit }
            }
          }
        { ?Var0  a                     RFDevice:Transceiving
          { ?Var0  a                     Nuvio:Process }
        }
      }
    }
  }
