PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { ?RadarJamming_0
                RFDevice:supportsJamming  ?JammingSystem_0
      { ?RadarJamming_0
                  a                     RFDevice:RadarJamming
        { ?PulseDopplerRadar_0
                    RFDevice:hasTarget  ?RadarJamming_0
          { ?PulseDopplerRadar_0
                      a                     RFDevice:PulseDopplerRadar
          }
        }
      }
    }
  }
