PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    OPTIONAL
      { ?Transceiving_0
                  RFDevice:supportsTuning  ?Full_DuplexCommunicationsSystem_0
        { ?Transceiving_0
                    a                     RFDevice:Transceiving
          { ?Transceiving_0
                      a                     Nuvio:Process
          }
        }
      }
  }
