PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?BistaticRadar_0
WHERE
  { ?BistaticRadar_0
              a                     RFDevice:BistaticRadar
    OPTIONAL
      { ?Var0  RFDevice:supportsJamming  ?BistaticRadar_0
        { ?Var0     a                     Nuvio:Entity .
          ?Value_0  Nuvio:expresses       ?Var0
          {   { ?Var0  a                     RFDevice:ElectronicAttack
                OPTIONAL
                  { ?Var0  a                     Nuvio:DimensionlessUnit }
                { ?Var0  a                     RFDevice:PositiveDecimalValue }
                { ?Var0     a                     Nuvio:Object .
                  ?Attribute_0  Nuvio:hasObjectQuality  ?Var0
                }
              }
            UNION
              { ?Value_0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 = 506714188 )
              }
          }
          { ?Var0  a                     RFDevice:RangeGatePullOffJamming }
          { ?Var0  a                     RFDevice:SelfProtectionJamming
            { ?Entity_0  Nuvio:hasProcessQuantity  ?Var0 }
          }
        }
      }
  }
