PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX310_0
WHERE
  { ?USRPX310_0  a                  SDR:USRPX310
    OPTIONAL
      { ?Entity_0  RFDevice:isProducerOf  ?USRPX310_0
        {   { ?Entity_0  a                    Nuvio:Entity .
              ?Object_0  Nuvio:isExpressedBy  ?Entity_0
              { ?DAC_0  Nuvio:aggregateOf  ?Entity_0
                { ?DAC_0  a                     RFDevice:DAC }
                { ?Entity_0  a                    RFDevice:Angle
                  { ?AngleValue_0
                              Nuvio:hasValue  ?Entity_0
                    { ?AngleValue_0
                                Nuvio:hasPrecision  ?DataValue0
                      FILTER ( ?DataValue0 >= 1228598002 )
                    }
                  }
                }
              }
            }
          UNION
            { ?Object_0  a                    Nuvio:Object ;
                        Nuvio:hasObjectQuality  ?Entity_0
            }
        }
      }
  }
