PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE3xx_0
WHERE
  { ?USRPE3xx_0  a                  SDR:USRPE3xx
    { ?IEDTrigger_0
                Nuvio:partOf  ?USRPE3xx_0
      { ?IEDTrigger_0
                  a                     RFDevice:IEDTrigger
        OPTIONAL
          { ?Entity_0  RFDevice:supportsTuning  ?IEDTrigger_0
            { ?Entity_0  a                    gml:Clothoid
              { ?Entity_0  a                    Nuvio:Object .
                ?UnitOfMeasure_0
                          RFDevice:supportsTransmitting  ?Entity_0
                { ?Entity_0  a                    Nuvio:Value .
                  ?InformationUnit_0
                            Nuvio:hasUnitOfMeasure  ?Entity_0
                  { ?InformationUnit_0
                              a                     RFDevice:InformationUnit
                  }
                }
              }
            }
          }
      }
    }
  }
