PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { ?IEDTrigger_0
                Nuvio:partOf  ?JammingSystem_0
      { ?IEDTrigger_0
                  a                     RFDevice:IEDTrigger
        { ?XilinxFPGA_0
                    Nuvio:compositeOf  ?IEDTrigger_0
        }
      }
    }
  }
