PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE313_0
WHERE
  { ?USRPE313_0  a                  SDR:USRPE313
    { ?Entity_0  RFDevice:isDeployedOn  ?USRPE313_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?Entity_2  Nuvio:expresses      ?Entity_0
        OPTIONAL
          { ?Entity_1  RFDevice:hasProducer  ?Entity_0
            OPTIONAL
              { ?Entity_0  a                    Nuvio:Situation .
                ?Modulator_0  Nuvio:relevantIndividual  ?Entity_0
                { ?Modulator_0  a                 RFDevice:Modulator }
                { ?Entity_0  a                    Nuvio:UnitOfMeasure }
              }
          }
      }
    }
  }
