PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SearchRadar_0
WHERE
  { ?SearchRadar_0
              a                     RFDevice:SearchRadar
    { ?Jammer_0  Nuvio:compositeOf  ?SearchRadar_0
      {   { ?Jammer_0  a                    RFDevice:Jammer }
        UNION
          { ?Object_0  RFDevice:isProducerOf  ?Jammer_0
            { ?Jammer_0  RFDevice:hasProducer  ?Producer_0 }
          }
      }
    }
  }
