PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CR_0
WHERE
  { ?CR_0  a                     SDR:CR
    { ?Var0  RFDevice:supportsSpectrumSensing  ?CR_0
      { ?Var0     a                     Nuvio:Entity .
        ?Process_0  Nuvio:expresses     ?Var0
        { ?Var0  RFDevice:hasPositiveIntegerValue  ?DataValue0
          FILTER ( ! ( ?DataValue0 <= 3.14 ) )
          {   { ?Var0  a                     RFDevice:Weight }
            UNION
              { ?Var0  Nuvio:hasValue  ?Var1
                { ?Var1  Nuvio:hasUnitOfMeasure  ?WeightUnit_0
                  { ?WeightUnit_0
                              a                     RFDevice:WeightUnit
                  }
                  { ?Var1  RFDevice:hasDecimalValue  ?DataValue1 }
                }
              }
          }
          OPTIONAL
            { ?Var0  Nuvio:informationSource  ?Var2
              { ?Var2  RFDevice:supportsSpectrumSensing  ObjectDescription:Moving_instance16 }
            }
        }
        { ?Process_0  a                   Nuvio:Process }
      }
    }
  }
