PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseDopplerRadar_0
WHERE
  { ?PulseDopplerRadar_0
              a                     RFDevice:PulseDopplerRadar
    { ?Var0  RFDevice:supportsTransmitting  ?PulseDopplerRadar_0
      { ?Var0  a                     RFDevice:SpectrumSensing
        { ?Entity_0  RFDevice:hasBandwidthRange  ?Var0
          {   { ?Entity_0  a                    Nuvio:Entity }
            UNION
              { ?Entity_0  a                    RFDevice:FrequencyUnit
                { ?Entity_0  Nuvio:hasDataValue  ?DataValue0
                  FILTER ( ?DataValue0 <= -19.13 )
                }
                { ?Entity_0  a                    Nuvio:UnitOfMeasure
                  { ?Entity_0  a                    Nuvio:InformationRepresentation }
                }
              }
          }
        }
        { ?USRPB205mini_i_0
                    Nuvio:hasParticipant  ?Var0
          { ?USRPB205mini_i_0
                      a                     SDR:USRPB205mini-i
            { ?Var1  RFDevice:hasVoltage  ?USRPB205mini_i_0 }
          }
        }
      }
    }
  }
