PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?Modulation_0
                RFDevice:hasCapability  ?SurveillanceRadar_0
      { ?Modulation_0
                  a                     RFDevice:Modulation
      }
    }
  }
