PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarWarningReceiver_0
WHERE
  { ?RadarWarningReceiver_0
              a                     RFDevice:RadarWarningReceiver
    { ?Entity_0  Nuvio:compositeOf  ?RadarWarningReceiver_0
      {   { ?UnitOfMeasure_0
                      Nuvio:isExpressedBy  ?Entity_0
          }
        UNION
          {   { ?Entity_0  a                    Nuvio:Value }
            UNION
              { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 < 1428434318 )
              }
            { ?UnitOfMeasure_0
                        a                     Nuvio:UnitOfMeasure
            }
          }
      }
    }
  }
