PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RFSystem_0
WHERE
  { ?RFSystem_0  a                  RFDevice:RFSystem
    { ?RFSystem_0  Nuvio:partOf  ?RadioComponent_0
      { ?RadioComponent_0
                  RFDevice:isProducerOf  ?Entity_0
        { ?Entity_0  a                    Nuvio:Entity .
          ?Attribute_0  Nuvio:expresses   ?Entity_0
          OPTIONAL
            { ?Entity_0  a                    Nuvio:Object
              { ?Entity_0  a                    RFDevice:ElectricChargeUnit
                {   { ?Entity_0  a                    RFDevice:FloatValue }
                  UNION
                    { ?Entity_0  RFDevice:hasDecimalValue  ?DataValue0
                      FILTER ( ?DataValue0 >= "22.74604"^^xsd:double )
                    }
                  { ?Entity_0  a                    Nuvio:Value .
                    ?VelocityUnit_0
                              Nuvio:hasUnitOfMeasure  ?Entity_0
                    { ?VelocityUnit_0
                                a                     RFDevice:VelocityUnit
                    }
                  }
                }
              }
              { ?Attribute_0  a                 Nuvio:Attribute }
            }
        }
      }
    }
  }
