PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB200_210_0
WHERE
  { ?USRPB200_210_0
              a                     SDR:USRPB200-210
    { ?Var0  RFDevice:supportsSpectrumSensing  ?USRPB200_210_0
      { ?Var0  a                     RFDevice:CrossPolarizationJamming
        { ObjectDescription:Instance1799
                    Nuvio:hasProcessQuantity  ?Var0
        }
        { ?Var0  a                     Nuvio:Attribute }
      }
    }
  }
