PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?Entity_0  RFDevice:isProducerOf  ?ElectronicAttackSystem_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_1  RFDevice:hasEffectiveRadiatedPower  ?Entity_0
          { ?Entity_0  a                    RFDevice:Weight
            OPTIONAL
              { ?Entity_0  Nuvio:hasValue  ?Var0
                { ?Var0  a                     Nuvio:Value ;
                         Nuvio:hasUnitOfMeasure  ?TimeUnit_0
                  { ?Var0  Nuvio:hasPrecision  ?DataValue0
                    FILTER ( ?DataValue0 != 1364556057 )
                  }
                }
              }
          }
        }
      }
    }
  }
