PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?Entity_0  RFDevice:isDeployedOn  ?ElectronicAttackSystem_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?Entity_1  Nuvio:isExpressedBy  ?Entity_0
        {   { ?Entity_0  a                    RFDevice:InstantaneousFrequencyMeasurementReceiver }
          UNION
            { ?Entity_0  a                    RFDevice:Moving
              { ?Entity_0  a                    Nuvio:Attribute }
            }
          { ?NoiseFigure_0
                      RFDevice:hasTransmitPowerRange  ?Entity_0
          }
        }
      }
    }
  }
