PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    OPTIONAL
      { ?Full_DuplexCommunicationsSystem_0
                  RFDevice:supportsTuning  ?Var0
        { ?Var0     a                     Nuvio:Entity .
          ?Object_0  Nuvio:expresses      ?Var0
          { ?Var1  RFDevice:hasGain  ?Var0
            { ?Var0  a                     Nuvio:DimensionlessUnit
              OPTIONAL
                { ?Var0  a                     RFDevice:DoubleValue }
            }
            { ?Object_0  a                    Nuvio:Object .
              ?RangeGatePullOffJamming_0
                        Nuvio:hasParticipant  ?Object_0
              { ?RangeGatePullOffJamming_0
                          a                     RFDevice:RangeGatePullOffJamming
              }
            }
          }
          { ?Var0  a                     RFDevice:Jamming
            { ?Quantity_0  RFDevice:hasTransmitPowerRange  ?Var0
              { ?Quantity_0  a                  Nuvio:Quantity }
            }
          }
        }
      }
  }
