PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?MonostaticRadar_0
WHERE
  { ?MonostaticRadar_0
              a                     RFDevice:MonostaticRadar
    { ?MonostaticRadar_0
                Nuvio:aggregateOf  ?Object_0
      { ?Object_0  a                    Nuvio:Object ;
                  RFDevice:supportsJamming  ?EmitterIdentification_0
        OPTIONAL
          { ?EmitterIdentification_0
                      a                     RFDevice:EmitterIdentification
            { ?Var0  Nuvio:participatesIn  ?EmitterIdentification_0 }
          }
      }
    }
  }
