PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription2000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RFSystem_0
WHERE
  { ?RFSystem_0  a                  RFDevice:RFSystem
    { ?Entity_0  RFDevice:hasProducer  ?RFSystem_0
      {   { ?Entity_0  a                    gml:MultiSurface }
        UNION
          { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
            FILTER ( ?DataValue0 < -2006978212 )
            { ?Var0  Nuvio:hasValue  ?Entity_0
              { ?Var0  Nuvio:hasDataValue  ?DataValue1
                FILTER ( ?DataValue1 <= 1059173146 )
                { ?Var0  a                     RFDevice:DecimalValue }
              }
            }
          }
      }
    }
  }
