PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?Entity_0  RFDevice:hasProducer  ?PulseRadar_0
      { ?InformationRepresentation_0
                  Nuvio:isExpressedBy  ?Entity_0
        {   {   { ?Entity_0  a                    SDR:Spartan6FPGA
                  { ObjectDescription:Producer_instance326
                              RFDevice:isProducerOf  ?Entity_0
                    { ?Producer_0  RFDevice:isProducerOf  ?Entity_0
                      { ?Producer_0  a                  RFDevice:Producer }
                    }
                  }
                  { ?Entity_0  a                    RFDevice:FrequencyModulation }
                }
              UNION
                {   { ?Entity_0  a                    Nuvio:Object }
                  UNION
                    { ?Entity_0  a                    Nuvio:UnitOfMeasure }
                }
            }
          UNION
            { ?Entity_1  Nuvio:representedBy  ?InformationRepresentation_0 }
        }
      }
    }
  }
