PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB200_210_0
WHERE
  { ?USRPB200_210_0
              a                     SDR:USRPB200-210
    OPTIONAL
      { ?Entity_0  Nuvio:aggregateOf  ?USRPB200_210_0
        { ?Entity_0  a                    Nuvio:Value ;
                    Nuvio:hasUnitOfMeasure  ?Entity_0
          { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
            FILTER ( ?DataValue0 <= 1350738749 )
          }
        }
      }
  }
