PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB210_0
WHERE
  { ?USRPB210_0  a                  SDR:USRPB210
    { ?Var0  RFDevice:hasNoiseFigure  ?USRPB210_0
      { ?Var0  Nuvio:hasValue  ?Var1
        { ?Var1  Nuvio:hasUnitOfMeasure  ?Var2 }
        OPTIONAL
          { ?Var0     a                     Nuvio:Entity .
            ?Process_0  Nuvio:expresses     ?Var0
            { ?Var0  a                     RFDevice:OmnidirectionalAntenna
              { ?Var0  a                     RFDevice:AdjustableBandwidthSensing
                { ?Var0  a                     RFDevice:TimeInstant }
              }
              { ?Var0     a                     Nuvio:Object .
                ?Quality_0  RFDevice:hasPolarization  ?Var0
                { ?Quality_0  a                   Nuvio:Quality }
              }
              { ?Process_0  a                   Nuvio:Process .
                ObjectDescription:MannedPlatform_instance20
                          Nuvio:participatesIn  ?Process_0
              }
            }
          }
      }
    }
  }
