PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarSystem_0
WHERE
  { ?RadarSystem_0
              a                     RFDevice:RadarSystem
    { ?RadarSystem_0
                Nuvio:compositeOf  ?SuperheterodyneReceiver_0
      { ?SuperheterodyneReceiver_0
                  a                     RFDevice:SuperheterodyneReceiver
        { ?PhasedArrayAntenna_0
                    Nuvio:partOf  ?SuperheterodyneReceiver_0
          { ?PhasedArrayAntenna_0
                      a                     RFDevice:PhasedArrayAntenna
          }
        }
      }
    }
  }
