PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN200_0
WHERE
  { ?USRPN200_0  a                  SDR:USRPN200
    { ?Entity_0  RFDevice:hasWeight  ?USRPN200_0
      { ?Object_0  Nuvio:isExpressedBy  ?Entity_0
        { ?Entity_0  a                    RFDevice:AutomaticGainControl
          { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
            FILTER ( ?DataValue0 >= 1513784841 )
            { ?Entity_0  a                    Nuvio:InformationContent }
          }
        }
        OPTIONAL
          { ?FrequencyScanRate_0
                      RFDevice:hasChargingTime  ?Object_0
            { ?FrequencyScanRate_0
                        a                     RFDevice:FrequencyScanRate
            }
          }
      }
    }
  }
