PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?SuperheterodyneReceiver_0
                Nuvio:partOf  ?Half_DuplexCommunicationsSystem_0
      {   { ?SuperheterodyneReceiver_0
                      a                     RFDevice:SuperheterodyneReceiver
          }
        UNION
          { ?SuperheterodyneReceiver_0
                      RFDevice:isProducerOf  ?Object_0
            { ?Object_0  a                    Nuvio:Object .
              ?Entity_0  RFDevice:supportsJamming  ?Object_0
              {   { ?Entity_0  a                    SDR:USRPN300 }
                UNION
                  { ?Entity_0  a                    Nuvio:Value ;
                              Nuvio:hasUnitOfMeasure  ?VelocityUnit_0
                    { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                      FILTER ( ?DataValue0 != -926342486 )
                    }
                  }
              }
            }
          }
      }
    }
  }
