PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CommunicationsSystem_0
WHERE
  { ?CommunicationsSystem_0
              a                     RFDevice:CommunicationsSystem
    OPTIONAL
      { ?Entity_0  RFDevice:hasProducer  ?CommunicationsSystem_0
        { ?Process_0  Nuvio:expresses  ?Entity_0
          { ?Entity_0  a                    SDR:XC7K325TFPGA
            { ?Entity_0  a                    RFDevice:TerrainBounceJamming
              { ?Quantity_0  RFDevice:hasPulseWidth  ?Entity_0
                { ?Quantity_0  a                  Nuvio:Quantity }
              }
            }
            { ?Process_0  Nuvio:subprocessOf  ?Value_0
              OPTIONAL
                { ?Value_0  a                     Nuvio:Value
                  { ?Value_0  Nuvio:hasPrecision  ?DataValue0
                    FILTER ( ?DataValue0 > 1469893560 )
                  }
                }
            }
          }
        }
      }
  }
