PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?Var0  RFDevice:supportsTuning  ?PulseRadar_0
      { ?Var0  a                     Nuvio:Entity ;
               Nuvio:isExpressedBy   ?Value_0
        { ?Var0  a                     SDR:XilinxZynq7000Family
          { ?ARMProcessor_0
                      Nuvio:aggregateOf  ?Var0
            { ?Object_0  RFDevice:hasProducer  ?ARMProcessor_0
              { ?Object_0  a                    Nuvio:Object .
                ?AntennaPolarization_0
                          Nuvio:hasObjectQuality  ?Object_0
                { ?AntennaPolarization_0
                            a                     RFDevice:AntennaPolarization
                }
              }
            }
          }
          OPTIONAL
            { ?VoltageUnit_0
                        Nuvio:hasUnitOfMeasure  ?Var0
              { ?Var0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 < -2120475686 )
              }
              { ?VoltageUnit_0
                          a                     RFDevice:VoltageUnit
              }
            }
        }
      }
    }
  }
