PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SearchRadar_0
WHERE
  { ?SearchRadar_0
              a                     RFDevice:SearchRadar
    { ?SearchRadar_0
                RFDevice:isProducerOf  ?Object_0
      { ?TimeInterval_0
                  RFDevice:hasVoltage  ?Object_0
        { ?TimeInterval_0
                    a                     RFDevice:TimeInterval
          { ?Var0  Nuvio:hasValue  ?TimeInterval_0
            { ?Entity_0  Nuvio:hasUnitOfMeasure  ?Var0
              { ?Entity_0  a                    RFDevice:StandoffJamming
                { ?Attribute_0  Nuvio:hasProcessQuantity  ?Entity_0 }
                { ?Entity_0  a                    Nuvio:InformationEntity ;
                            Nuvio:isExpressedBy   ?CompositeSurface_0
                  { ?Entity_0  a                    RFDevice:NonNegativeDecimalValue }
                }
                { ?Entity_0  a                    RFDevice:AntennaPolarization }
              }
            }
          }
        }
      }
    }
  }
