PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB205mini_i_0
WHERE
  { ?USRPB205mini_i_0
              a                     SDR:USRPB205mini-i
    { ?Entity_0  RFDevice:hasWeight  ?USRPB205mini_i_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?UnitOfMeasure_0
                  Nuvio:expresses       ?Entity_0
        OPTIONAL
          { ?Entity_0  a                    RFDevice:Transmitting
            { ?Attribute_0  RFDevice:hasPulseRepetitionInterval  ?Entity_0 }
            { ?Entity_0  a                    RFDevice:SpatialUnit }
            {   { ?Quantity_0  RFDevice:hasPolarization  ?Entity_0
                  { ?Quantity_0  a                  Nuvio:Quantity }
                }
              UNION
                {   { ?CyclostationaryDetection_0
                                Nuvio:hasSubprocess  ?Entity_0
                    }
                  UNION
                    { ?CyclostationaryDetection_0
                                a                     RFDevice:CyclostationaryDetection
                    }
                  { ?Entity_0  a                    Nuvio:Situation
                    OPTIONAL
                      { ?MultiPolygon_0
                                  Nuvio:relevantIndividual  ?Entity_0
                      }
                  }
                }
            }
          }
      }
    }
  }
