PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { ?Jamming_0  RFDevice:supportsJamming  ?JammingSystem_0
      { ?Jamming_0  RFDevice:hasPulseRepetitionFrequency  ?Entity_0
        {   { ?Entity_0  a                    Nuvio:Entity }
          UNION
            { ?Entity_0  a                    RFDevice:Detection
              { ?Entity_0  a                    RFDevice:NonNegativeDecimalValue }
              { ?Entity_0  a                    Nuvio:InformationContent .
                ?InformationEntity_0
                          Nuvio:represents      ?Entity_0
                { ?InformationEntity_0
                            a                     Nuvio:InformationEntity
                }
              }
            }
        }
      }
    }
  }
