PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SDR_0
WHERE
  { ?SDR_0  a                     SDR:SDR
    { ?SDR_0  RFDevice:hasProducer  ?Entity_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?InformationEntity_0
                  Nuvio:isExpressedBy   ?Entity_0
        { ?Entity_0  a                    RFDevice:Jammer
          { ?Entity_0  a                    RFDevice:BlinkingJamming }
          OPTIONAL
            { ?Entity_0  a                    RFDevice:PowerUnit
              { ?DataSize_0  Nuvio:isExpressedBy  ?Entity_0
                { ?DataSize_0  a                  RFDevice:DataSize
                  { ?Var0  Nuvio:hasValue  ?DataSize_0
                    { ?Var0  RFDevice:hasIntegerValue  ?DataValue0
                      FILTER ( ?DataValue0 != 495024987 )
                    }
                  }
                }
                OPTIONAL
                  {   { ?Entity_0  a                    Nuvio:Value }
                    UNION
                      { ?Entity_0  Nuvio:hasPrecision  ?DataValue1
                        FILTER ( ?DataValue1 >= 1668191285 )
                      }
                  }
              }
            }
        }
      }
    }
  }
