PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    OPTIONAL
      { ?Ship_0  RFDevice:isDeployedOn  ?PulseRadar_0
        { ObjectDescription:Moving_instance58
                    RFDevice:hasCapability  ?Ship_0
        }
      }
  }
