PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    { ?Full_DuplexCommunicationsSystem_0
                RFDevice:isDeployedOn  ?Ship_0
      {   { ?Ship_0  a                     RFDevice:Ship }
        UNION
          { ?Process_0  RFDevice:supportsTuning  ?Ship_0
            { ?Process_0  a                   Nuvio:Process .
              ?Quantity_0  Nuvio:hasProcessQuality  ?Process_0
              { ?Quantity_0  a                  Nuvio:Quantity }
            }
          }
      }
    }
  }
