PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?Entity_0  RFDevice:hasProducer  ?ElectronicAttackSystem_0
      { ?InformationContent_0
                  Nuvio:isExpressedBy  ?Entity_0
        {   { ?Entity_0  a                    RFDevice:CommunicationsJamming
              { ?Quantity_0  RFDevice:hasPulseRepetitionFrequency  ?Entity_0
                { ?Quantity_0  a                  Nuvio:Quantity }
              }
            }
          UNION
            { ?Entity_0  a                    Nuvio:Attribute }
        }
      }
    }
  }
