PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?MonostaticRadar_0
WHERE
  { ?MonostaticRadar_0
              a                     RFDevice:MonostaticRadar
    { ?Entity_0  RFDevice:supportsJamming  ?MonostaticRadar_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?Attribute_0  Nuvio:expresses   ?Entity_0
        { ?Entity_0  a                    RFDevice:Receiving
          { ?Situation_0  Nuvio:hasUnitOfMeasure  ?Entity_0
            { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
              FILTER ( ?DataValue0 > 142218525 )
            }
          }
        }
      }
    }
  }
