PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    OPTIONAL
      { ?Entity_0  RFDevice:hasVoltage  ?Half_DuplexCommunicationsSystem_0
        { ?Entity_0  a                    Nuvio:Entity .
          ?InformationRepresentation_0
                    Nuvio:isExpressedBy   ?Entity_0
          { ?Entity_0  a                    SDR:USRPB200
            { ?Var0  RFDevice:hasGain  ?Entity_0 }
            { ?Var1  Nuvio:hasValue  ?Entity_0
              { ?Var1  a                     RFDevice:NonNegativeDecimalValue
                { ?Var1  RFDevice:hasFloatValue  ?DataValue0
                  FILTER ( ?DataValue0 != -78.69 )
                }
              }
            }
            {   { ?Entity_0  a                    Nuvio:Object .
                  ?Quantity_0  RFDevice:hasPolarization  ?Entity_0
                }
              UNION
                { ?Quantity_0  a                  Nuvio:Quantity }
            }
            { ?Entity_0  a                    Nuvio:Attribute }
          }
        }
      }
  }
