PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CR_0
WHERE
  { ?CR_0  a                     SDR:CR
    { ?Weight_0  Nuvio:hasObjectQuantity  ?CR_0
      { ?Weight_0  a                    RFDevice:Weight
        { ?Weight_0  Nuvio:hasValue  ?Var0
          { ?Var0  a                     RFDevice:FloatValue
            { ?Var0  RFDevice:hasFloatValue  ?DataValue0
              FILTER ( ! ( ?DataValue0 > "0.0"^^xsd:double ) )
            }
          }
        }
      }
    }
  }
