PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB205mini_i_0
WHERE
  { ?USRPB205mini_i_0
              a                     SDR:USRPB205mini-i
    OPTIONAL
      { ?Entity_0  RFDevice:isProducerOf  ?USRPB205mini_i_0
        { ?Entity_0  a                    Nuvio:Entity .
          ?Object_0  Nuvio:expresses      ?Entity_0
          { ?Entity_0  RFDevice:hasDecimalValue  ?DataValue0
            FILTER ( ?DataValue0 >= -34.44 )
            { ?Quantity_0  RFDevice:hasPolarization  ?Object_0
              { ?Quantity_0  a                  Nuvio:Quantity }
            }
          }
        }
      }
  }
