PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX310_0
WHERE
  { ?USRPX310_0  a                  SDR:USRPX310
    { ?Var0  Nuvio:aggregateOf  ?USRPX310_0
      { SDR:Freq_200MHz
                  RFDevice:hasGain  ?Var0
        OPTIONAL
          { ?Var0  a                     Nuvio:Entity
            { ?Var0  a                     RFDevice:Port
              OPTIONAL
                { ?Var0  a                     RFDevice:PositiveIntegerValue }
            }
          }
      }
    }
  }
