PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicSupportSystem_0
WHERE
  { ?ElectronicSupportSystem_0
              a                     RFDevice:ElectronicSupportSystem
    { ?Var0  RFDevice:hasCapability  ?ElectronicSupportSystem_0
      {   { ?Var0  a                     Nuvio:Entity ;
                   Nuvio:isExpressedBy   ?InformationRepresentation_0
          }
        UNION
          { ?Var0  a                     RFDevice:CoverPulsesJamming
            { ?Power_0  RFDevice:hasEffectiveRadiatedPower  ?Var0
              { ?Var1  Nuvio:hasValue  ?Power_0
                { ?Var1  Nuvio:hasUnitOfMeasure  ObjectDescription:PowerUnit_instance3 }
              }
            }
            { ?Var0  a                     Nuvio:Object }
            { ?Var2  Nuvio:hasValue  ?Var0
              { ?Entity_0  Nuvio:representedBy  ?Var0 }
            }
          }
      }
    }
  }
