PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?USRPE312_0
WHERE
  { ?USRPE312_0  a                  SDR:USRPE312
    { ?Entity_0  Nuvio:aggregateOf  ?USRPE312_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?Attribute_0  Nuvio:isExpressedBy  ?Entity_0
        OPTIONAL
          {   { ?Entity_0  a                    RFDevice:Jamming
                { ?Power_0  RFDevice:hasPulseWidth  ?Entity_0
                  { ?Power_0  a                     RFDevice:Power }
                }
              }
            UNION
              { ?Entity_0  a                    RFDevice:VelocityUnit
                { ?Shell_0  Nuvio:relevantIndividual  ?Entity_0
                  { ?Entity_0  Nuvio:relevantIndividual  ?Submarine_0
                    { ?Moving_0  RFDevice:supportsTuning  ?Submarine_0
                      { ?Moving_0  a                    RFDevice:Moving }
                    }
                  }
                  { ?Shell_0  a                     gml:Shell }
                }
              }
          }
      }
    }
  }
