PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX300_0
WHERE
  { ?USRPX300_0  a                  SDR:USRPX300
    { ?Var0  RFDevice:supportsJamming  ?USRPX300_0
      { ?Var1  RFDevice:hasPulseRepetitionInterval  ?Var0
        { ?Var1  a                     Nuvio:Entity
          { ?Var1     a                     Nuvio:Situation .
            ?MultiLineString_0
                      Nuvio:relevantIndividual  ?Var1
            OPTIONAL
              { ObjectDescription:Instance1541
                          Nuvio:relevantIndividual  ?Var1
              }
            { ?Var1  Nuvio:hasPrecision  ?DataValue0
              FILTER ( ?DataValue0 != 2098236496 )
            }
          }
        }
      }
    }
  }
