PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?Entity_0  Nuvio:compositeOf  ?SurveillanceRadar_0
      { ?Entity_0  Nuvio:isExpressedBy  ?Attribute_0
        { ?Entity_0  RFDevice:hasProducer  ?Entity_0
          { ?Entity_0  a                    RFDevice:DataSize
            { ?Entity_0  Nuvio:hasValue  ?Var0
              { ?Var0  RFDevice:hasDecimalValue  ?DataValue0
                FILTER ( ?DataValue0 < 1232976072 )
                { ?Var0  a                     Nuvio:Value ;
                         Nuvio:hasUnitOfMeasure  ObjectDescription:FrequencyUnit_instance12
                  { ?Var0  Nuvio:hasPrecision  ?DataValue1
                    FILTER ( ?DataValue1 = -607383437 )
                  }
                }
              }
            }
          }
        }
      }
    }
  }
