PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX310_0
WHERE
  { ?USRPX310_0  a                  SDR:USRPX310
    { ?Entity_0  RFDevice:isProducerOf  ?USRPX310_0
      { ?Situation_0  Nuvio:expresses  ?Entity_0
        { ?Entity_0  a                    gml:LineStringSegment
          { ?Entity_0  a                    Nuvio:Situation .
            ?ArcByCenterPoint_0
                      Nuvio:relevantIndividual  ?Entity_0
            { ?Entity_0  Nuvio:relevantIndividual  ?Submarine_0
              { ?Submarine_0  a                 RFDevice:Submarine }
            }
          }
          { ?Entity_0  a                    Nuvio:Attribute }
        }
      }
    }
  }
