PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Half_DuplexCommunicationsSystem_0
                RFDevice:hasCapability  ?Entity_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?InformationEntity_0
                  Nuvio:isExpressedBy   ?Entity_0
        {   { ?Entity_0  a                    RFDevice:IntValue
              OPTIONAL
                { ?Entity_0  RFDevice:hasNonNegativeIntegerValue  ?DataValue0 }
              { ?Entity_0  a                    RFDevice:Length
                OPTIONAL
                  { ?Entity_0  Nuvio:hasValue  ?Var0 }
              }
            }
          UNION
            { ?InformationEntity_0
                        a                     Nuvio:InformationEntity
            }
        }
      }
    }
  }
