PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    { ?Transceiving_0
                RFDevice:supportsTransmitting  ?Full_DuplexCommunicationsSystem_0
      { ?Transceiving_0
                  a                     RFDevice:Transceiving
        { ObjectDescription:Weight_instance157
                    RFDevice:hasPulseWidth  ?Transceiving_0
        }
      }
    }
  }
