PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?Entity_0  RFDevice:isProducerOf  ?PulseRadar_0
      {   { ?Entity_0  a                    Nuvio:Entity }
        UNION
          { ?Entity_0  a                    Nuvio:Situation
            { ?ArcByCenterPoint_0
                        Nuvio:relevantIndividual  ?Entity_0
              { ?ArcByCenterPoint_0
                          a                     gml:ArcByCenterPoint
              }
            }
          }
      }
    }
  }
