PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ContinuousWaveRadar_0
WHERE
  { ?ContinuousWaveRadar_0
              a                     RFDevice:ContinuousWaveRadar
    { ?Process_0  RFDevice:supportsSpectrumSensing  ?ContinuousWaveRadar_0
      { ?Process_0  a                   Nuvio:Process .
        ?AmplitudeModulation_0
                  Nuvio:subprocessOf    ?Process_0
        { ?AmplitudeModulation_0
                    a                     RFDevice:AmplitudeModulation
        }
      }
    }
  }
