PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN310_0
WHERE
  { ?USRPN310_0  a                  SDR:USRPN310
    { ?USRPN310_0  RFDevice:hasSamplingRate  ?Entity_0
      { ?Entity_0  a                    Nuvio:Entity ;
                  Nuvio:expresses       ?Attribute_0
        { ?Entity_0  a                    Nuvio:Situation
          OPTIONAL
            { ?RFSystem_0  Nuvio:relevantIndividual  ?Entity_0
              { ?RFSystem_0  a                  RFDevice:RFSystem }
            }
          { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
            FILTER ( ?DataValue0 > 327865862 )
          }
        }
        { ?Attribute_0  a                 Nuvio:Attribute }
      }
    }
  }
