PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX3xx_0
WHERE
  { ?USRPX3xx_0  a                  SDR:USRPX3xx
    { ?Var0  RFDevice:supportsSpectrumSensing  ?USRPX3xx_0
      { ?Var1  RFDevice:hasMaxOutputPower  ?Var0
        { ?Var2  Nuvio:hasValue  ?Var1
          { ?Var2  RFDevice:hasDoubleValue  ?DataValue0
            FILTER ( ?DataValue0 != 2.78 )
          }
        }
      }
    }
  }
