PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN200_0
WHERE
  { ?USRPN200_0  a                  SDR:USRPN200
    { ?Var0  RFDevice:supportsTransmitting  ?USRPN200_0
      { ?Var0  Nuvio:hasProcessQuantity  ?Power_0
        { ?Power_0  a                     RFDevice:Power
          { ?Var1  Nuvio:hasValue  ?Power_0
            { ?Var1  a                     RFDevice:NonNegativeIntegerValue
              { ?Var1  RFDevice:hasNonNegativeIntegerValue  ?DataValue0
                FILTER ( ?DataValue0 <= 2115654635 )
              }
            }
          }
        }
        { ?Var0  a                     Nuvio:Process }
      }
    }
  }
