PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CR_0
WHERE
  { ?CR_0  a                     SDR:CR
    OPTIONAL
      { ?CR_0  RFDevice:supportsJamming  ?Var0
        { ?Var0     a                     Nuvio:Entity .
          ?Object_0  Nuvio:isExpressedBy  ?Var0
          {   {   { ?Spartan3ADSPFPGA_0
                              Nuvio:partOf  ?Var0
                    {   { ?Spartan3ADSPFPGA_0
                                    a                     SDR:Spartan3ADSPFPGA
                        }
                      UNION
                        { ?Var1  RFDevice:hasProducer  ?Spartan3ADSPFPGA_0 }
                    }
                  }
                UNION
                  { ?Var0  a                     RFDevice:LongitudeValue }
              }
            UNION
              { ?Var0  a                     RFDevice:FrequencyScanRate
                { ?Var0  Nuvio:hasPrecision  ?DataValue0
                  FILTER ( ?DataValue0 != -538749860 )
                }
              }
            { ?Object_0  a                    Nuvio:Object .
              ?CumulativeDetection_0
                        RFDevice:supportsTransmitting  ?Object_0
            }
          }
          OPTIONAL
            { ?Var0  a                     RFDevice:CoverPulsesJamming }
        }
      }
  }
