PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?CR_0
WHERE
  { ?CR_0  a                     SDR:CR
    { ?CR_0  Nuvio:compositeOf  ?Entity_0
      { ?Entity_0  a                    Nuvio:Situation .
        ?AbstractGeometry_0
                  Nuvio:relevantIndividual  ?Entity_0
        { ?RadarFrequencyBand_0
                    Nuvio:relevantIndividual  ?Entity_0
          { ?AbstractGeometry_0
                      a                     gml:AbstractGeometry
          }
        }
        { ?Entity_0  a                    Nuvio:Value .
          ?InformationUnit_0
                    Nuvio:hasUnitOfMeasure  ?Entity_0
          { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
            FILTER ( ?DataValue0 < -76102582 )
            OPTIONAL
              { ?InformationUnit_0
                          a                     RFDevice:InformationUnit
              }
          }
        }
        OPTIONAL
          { ?Entity_0  a                    Nuvio:Process .
            ?Quantity_0  Nuvio:hasProcessQuality  ?Entity_0
            { ?Quantity_0  a                  Nuvio:Quantity }
          }
      }
    }
  }
