PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?TrackingRadar_0
WHERE
  { ?TrackingRadar_0
              a                     RFDevice:TrackingRadar
    OPTIONAL
      { ?TrackingRadar_0
                  RFDevice:hasCapability  ?Var0
        { ?Var0  a                     RFDevice:BlinkingJamming
          { ?Var0  a                     Nuvio:Entity
            { ?Var0  Nuvio:participatesIn  ?SpotJamming_0
              { ?SpotJamming_0
                          a                     RFDevice:SpotJamming
                { ?Power_0  RFDevice:hasTransmitPowerRange  ?SpotJamming_0
                  { ?Power_0  a                     RFDevice:Power }
                }
              }
              { ?Var0  a                     Nuvio:Situation }
            }
          }
        }
      }
  }
