PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE310_0
WHERE
  { ?USRPE310_0  a                  SDR:USRPE310
    { ?USRPE310_0  RFDevice:hasProducer  ?Entity_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?InformationContent_0
                  Nuvio:expresses       ?Entity_0
        {   { ?Entity_0  a                    RFDevice:CoverPulsesJamming
              { ?Quantity_0  RFDevice:hasTransmitPowerRange  ?Entity_0
                { ?Quantity_0  a                  Nuvio:Quantity }
              }
            }
          UNION
            {   { ?Entity_0  a                    Nuvio:Value .
                  ?Object_0  Nuvio:hasUnitOfMeasure  ?Entity_0
                }
              UNION
                { ?Object_0  a                    Nuvio:Object .
                  ObjectDescription:AntennaPolarization_instance1
                            Nuvio:hasObjectQuality  ?Object_0
                }
            }
          { ?Entity_0  Nuvio:representedBy  ?InformationContent_0 }
        }
      }
    }
  }
