PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Entity_0  RFDevice:hasProducer  ?Half_DuplexCommunicationsSystem_0
      {   { ?Entity_0  a                    Nuvio:Entity }
        UNION
          { ?Var0  RFDevice:hasNoiseFigure  ?Entity_0
            { ?Entity_0  RFDevice:hasMaxOutputPower  SDR:Power_45W }
            { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
              FILTER ( ?DataValue0 = -452364511 )
              { ?Entity_0  a                    RFDevice:FrequencyScanRate
                { ?Var1  Nuvio:hasValue  ?Entity_0 }
                OPTIONAL
                  { ?Entity_0  a                    Nuvio:Situation }
              }
            }
          }
      }
    }
  }
