PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?MonostaticRadar_0
WHERE
  { ?MonostaticRadar_0
              a                     RFDevice:MonostaticRadar
    OPTIONAL
      { ?Entity_0  RFDevice:supportsTuning  ?MonostaticRadar_0
        { ?Entity_0  a                    Nuvio:Entity
          OPTIONAL
            { ?Entity_0  a                    RFDevice:AmplitudeShiftKeyingModulation }
        }
      }
  }
