PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?GNURadio_0
WHERE
  { ?GNURadio_0  rdf:type  SDR:GNURadio
    { ?Entity_0  RFDevice:isProducerOf  ?GNURadio_0
      { ?Entity_0  rdf:type  rdf:List
        { ?Entity_0  rdf:type  RFDevice:Frequency
          { ?Entity_0  rdf:type  Nuvio:InformationContent }
        }
      }
    }
  }
