PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CR_0
WHERE
  { ?CR_0  a                     SDR:CR
    { ?Entity_0  RFDevice:hasWidth  ?CR_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?InformationContent_0
                  Nuvio:isExpressedBy   ?Entity_0
        { ?Entity_0  a                    RFDevice:CumulativeDetection
          {   { ?Entity_0  a                    RFDevice:TimeInstant }
            UNION
              { ?Var0  Nuvio:hasValue  ?Entity_0
                {   { ?Var0  Nuvio:hasPrecision  ?DataValue0
                      FILTER ( ?DataValue0 <= -1092861919 )
                    }
                  UNION
                    { ?Entity_0  Nuvio:hasUnitOfMeasure  ?Var0 }
                }
              }
            { ?Entity_0  a                    Nuvio:Situation ;
                        Nuvio:relevantIndividual  ?Situation_0
            }
          }
        }
        OPTIONAL
          { ?InformationContent_0
                      a                     Nuvio:InformationContent
          }
      }
    }
  }
