PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?GNURadio_0
WHERE
  { ?GNURadio_0  a                  SDR:GNURadio
    { ?GNURadio_0  RFDevice:isProducerOf  ?Object_0
      { ?Object_0  a                    Nuvio:Object .
        ?FrequencyScanRate_0
                  RFDevice:hasBeamwidth  ?Object_0
        { ?FrequencyScanRate_0
                    a                     RFDevice:FrequencyScanRate
          { ?FrequencyScanRate_0
                      Nuvio:hasValue  ?Var0
            { ?Var0  a                     RFDevice:IntegerValue
              { ?Var0  RFDevice:hasDoubleValue  ?DataValue0
                FILTER ( ?DataValue0 < -1863862303 )
              }
            }
          }
        }
      }
    }
  }
