PREFIX  geosparql: <http://www.opengis.net/ont/geosparql#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { ?Entity_0  RFDevice:hasWidth  ?JammingSystem_0
      { ?Entity_0  a                    geosparql:Geometry
        { ?Entity_0  a                    RFDevice:PositiveFloatValue
          OPTIONAL
            { ?Entity_0  a                    Nuvio:Value }
        }
      }
    }
  }
