PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN210_0
WHERE
  { ?USRPN210_0  a                  SDR:USRPN210
    OPTIONAL
      { ?USRPN210_0  RFDevice:supportsTransmitting  ?Var0
        { ?Var0     a                     Nuvio:Entity .
          ?Object_0  Nuvio:expresses      ?Var0
          {   { ?Var0  a                     RFDevice:AngleValue }
            UNION
              { ?Var0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 <= -87961661 )
              }
            { ?Var0  Nuvio:hasValue  ?Var1 }
            { RFDevice:Decibel_milliwatts
                        Nuvio:hasUnitOfMeasure  ?Var0
            }
          }
          { ?Object_0  a                    Nuvio:Object .
            ?Var0     RFDevice:hasChargingTime  ?Object_0
          }
        }
      }
  }
