PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE312_0
WHERE
  { ?USRPE312_0  a                  SDR:USRPE312
    { ?Entity_0  Nuvio:aggregateOf  ?USRPE312_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?InformationContent_0
                  Nuvio:isExpressedBy   ?Entity_0
        {   { ?Entity_0  a                    Nuvio:Value }
          UNION
            { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
              FILTER ( ?DataValue0 != -1405204054 )
            }
          { ?Entity_0  a                    Nuvio:Process ;
                      Nuvio:hasSubprocess   ?SweepJamming_0
          }
        }
      }
    }
  }
