PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?TrackingRadar_0
WHERE
  { ?TrackingRadar_0
              a                     RFDevice:TrackingRadar
    OPTIONAL
      { ?TrackingRadar_0
                  RFDevice:supportsJamming  ?Var0
        { ?Var0  a                     Nuvio:Process
          {   { ?Var0  a                     RFDevice:SweptSpotJamming }
            UNION
              { ?Power_0  RFDevice:hasPulseRepetitionInterval  ?Var0
                { ?Power_0  a                     RFDevice:Power }
              }
          }
        }
      }
  }
