PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseDopplerRadar_0
WHERE
  { ?PulseDopplerRadar_0
              a                     RFDevice:PulseDopplerRadar
    { ?PulseDopplerRadar_0
                RFDevice:supportsSpectrumSensing  ?Entity_0
      { ?Entity_0  a                    Nuvio:Entity ;
                  Nuvio:expresses       ?Process_0
        {   { ?Entity_0  a                    RFDevice:CumulativeDetection
              { ?Entity_0  a                    RFDevice:FrequencyScanRateUnit }
            }
          UNION
            { ?Entity_0  a                    RFDevice:Time
              {   { ?Entity_0  a                    Nuvio:Value .
                    ObjectDescription:WeightUnit_instance15
                              Nuvio:hasUnitOfMeasure  ?Entity_0
                  }
                UNION
                  { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                    FILTER ( ?DataValue0 > 830669842 )
                  }
              }
            }
        }
        { ?Process_0  a                   Nuvio:Process .
          ?Quality_0  Nuvio:hasProcessQuality  ?Process_0
          { ?Quality_0  a                   Nuvio:Quality }
        }
      }
    }
  }
