PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Entity_0  RFDevice:isProducerOf  ?Half_DuplexCommunicationsSystem_0
      { ?Entity_0  Nuvio:isExpressedBy  ?InformationContent_0
        { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
          FILTER ( ?DataValue0 <= 1200710428 )
          {   { ?InformationEntity_0
                          RFDevice:supportsTuning  ?Entity_0
              }
            UNION
              { ?InformationEntity_0
                          a                     Nuvio:InformationEntity .
                ObjectDescription:Instance1650
                          Nuvio:expresses       ?InformationEntity_0
              }
          }
        }
        { ?InformationRepresentation_0
                    Nuvio:representedBy  ?InformationContent_0
          { ?InformationRepresentation_0
                      a                     Nuvio:InformationRepresentation
          }
        }
      }
    }
  }
