PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB205mini_i_0
WHERE
  { ?USRPB205mini_i_0
              a                     SDR:USRPB205mini-i
    { ?USRPB205mini_i_0
                RFDevice:hasCapability  ?Var0
      { ?Var0     a                     Nuvio:Process .
        ?Situation_0  Nuvio:hasSubprocess  ?Var0
        { ?Situation_0  a                 Nuvio:Situation ;
                    Nuvio:relevantIndividual  ?OnOffKeyingModulation_0
          { ?OnOffKeyingModulation_0
                      a                     RFDevice:OnOffKeyingModulation
          }
        }
      }
    }
  }
