PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ModelX_0
WHERE
  { ?ModelX_0  a                    RFDevice:ModelX
    { ?RadioComponent_0
                Nuvio:aggregateOf  ?ModelX_0
      {   { ?RadioComponent_0
                      a                     RFDevice:RadioComponent
          }
        UNION
          {   { ?RadioComponent_0
                          RFDevice:hasProducer  ObjectDescription:Producer_instance663
              }
            UNION
              { ?Producer_0  RFDevice:hasProducer  ?RadioComponent_0 }
          }
      }
    }
  }
