PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB2xxmini_0
WHERE
  { ?USRPB2xxmini_0
              a                     SDR:USRPB2xxmini
    { ?Var0  RFDevice:supportsTuning  ?USRPB2xxmini_0
      { ?Var0  a                     RFDevice:TerrainBounceJamming
        { ?Entity_0  RFDevice:hasPulseWidth  ?Var0
          { ?Entity_0  a                    Nuvio:Entity
            { ?Entity_0  a                    RFDevice:Jamming
              OPTIONAL
                { ObjectDescription:Power_instance35
                            RFDevice:hasPulseWidth  ?Entity_0
                }
              { ?Entity_0  a                    Nuvio:InformationEntity }
            }
          }
        }
      }
    }
  }
