PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    { ?Var0  RFDevice:supportsSpectrumSensing  ?Full_DuplexCommunicationsSystem_0
      { ?Var0     a                     Nuvio:Process .
        ?Object_0  Nuvio:subprocessOf   ?Var0
        OPTIONAL
          { ?EmitterIdentification_0
                      Nuvio:hasParticipant  ?Object_0
            OPTIONAL
              { ?EmitterIdentification_0
                          a                     RFDevice:EmitterIdentification
              }
          }
      }
    }
  }
