PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?Entity_0  Nuvio:aggregateOf  ?SurveillanceRadar_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?InformationContent_0
                  Nuvio:expresses       ?Entity_0
        {   { ?Entity_0  a                    SDR:FPGA
              {   { ?Entity_0  a                    RFDevice:SpatialAreaUnit }
                UNION
                  {   { ?Entity_0  a                    RFDevice:IntegerValue }
                    UNION
                      { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                        FILTER ( ?DataValue0 > -1697337238 )
                      }
                  }
              }
            }
          UNION
            { ?Entity_0  a                    RFDevice:Percentage }
        }
        { ?InformationContent_0
                    a                     Nuvio:InformationContent
        }
      }
    }
  }
