PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?MonostaticRadar_0
WHERE
  { ?MonostaticRadar_0
              a                     RFDevice:MonostaticRadar
    { ?Var0  RFDevice:supportsJamming  ?MonostaticRadar_0
      { ?Var0  a                     RFDevice:CrossEyeJamming
        { ObjectDescription:Power_instance40
                    RFDevice:hasPulseWidth  ?Var0
        }
        { ?Var0  a                     RFDevice:Receiving }
      }
    }
  }
