PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB2xx_0
WHERE
  { ?USRPB2xx_0  a                  SDR:USRPB2xx
    { ?Quantity_0  RFDevice:hasSamplingRate  ?USRPB2xx_0
      { ?Quantity_0  a                  Nuvio:Quantity }
    }
  }
