PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB200mini_0
WHERE
  { ?USRPB200mini_0
              a                     SDR:USRPB200mini
    OPTIONAL
      { ?Entity_0  RFDevice:isProducerOf  ?USRPB200mini_0
        { ?Entity_0  a                    Nuvio:Entity .
          ?Process_0  Nuvio:isExpressedBy  ?Entity_0
          { ?DimensionlessUnit_0
                      Nuvio:hasUnitOfMeasure  ?Entity_0
            { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
              FILTER ( ?DataValue0 = 1638141342 )
            }
            { ?DimensionlessUnit_0
                        a                     Nuvio:DimensionlessUnit
            }
          }
          { ?Process_0  a                   Nuvio:Process .
            ?AbstractParametricCurveSurface_0
                      Nuvio:hasParticipant  ?Process_0
          }
        }
      }
  }
