PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { ?CrossEyeJamming_0
                RFDevice:supportsJamming  ?JammingSystem_0
      { ?CrossEyeJamming_0
                  a                     RFDevice:CrossEyeJamming
        { ?Quantity_0  RFDevice:hasPulseRepetitionInterval  ?CrossEyeJamming_0
          { ?Quantity_0  a                  Nuvio:Quantity }
        }
      }
    }
  }
