PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RFSystem_0
WHERE
  { ?RFSystem_0  a                  RFDevice:RFSystem
    { ?Entity_0  RFDevice:hasWeight  ?RFSystem_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?Process_0  Nuvio:expresses     ?Entity_0
        { ?SDR_0  RFDevice:hasTarget  ?Process_0
          { ?SDR_0  a                     SDR:SDR }
        }
      }
    }
  }
