PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?MonostaticRadar_0
WHERE
  { ?MonostaticRadar_0
              a                     RFDevice:MonostaticRadar
    { ?InstantaneousFrequencyMeasurementReceiver_0
                Nuvio:compositeOf  ?MonostaticRadar_0
      { ?InstantaneousFrequencyMeasurementReceiver_0
                  a                     RFDevice:InstantaneousFrequencyMeasurementReceiver
        { ObjectDescription:ADC_instance8
                    Nuvio:partOf  ?InstantaneousFrequencyMeasurementReceiver_0
        }
      }
    }
  }
