PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CR_0
WHERE
  { ?CR_0  a                     SDR:CR
    OPTIONAL
      { ?Entity_0  RFDevice:hasChargingTime  ?CR_0
        {   { ?Entity_0  a                    Nuvio:Entity .
              ?InformationRepresentation_0
                        Nuvio:expresses       ?Entity_0
            }
          UNION
            { ?Entity_0  a                    RFDevice:Detection
              { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 < 291728549 )
              }
              { ?InformationRepresentation_0
                          a                     Nuvio:InformationRepresentation
              }
            }
        }
      }
  }
