PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  sf:   <http://www.opengis.net/ont/sf#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE310_0
WHERE
  { ?USRPE310_0  a                  SDR:USRPE310
    { ?Entity_0  RFDevice:isProducerOf  ?USRPE310_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?Situation_0  Nuvio:expresses   ?Entity_0
        { ?Entity_0  a                    sf:MultiLineString
          { ObjectDescription:SuperheterodyneReceiver_instance111
                      Nuvio:relevantIndividual  ?Situation_0
          }
        }
      }
    }
  }
