PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB205mini_i_0
WHERE
  { ?USRPB205mini_i_0
              a                     SDR:USRPB205mini-i
    { ?USRPB205mini_i_0
                RFDevice:hasProducer  ?Entity_0
      {   { ?Entity_0  a                    Nuvio:Entity .
            ?Situation_0  Nuvio:expresses   ?Entity_0
          }
        UNION
          { ?Situation_0  a                 Nuvio:Situation .
            ?CoverJamming_0
                      Nuvio:relevantIndividual  ?Situation_0
            { ?CoverJamming_0
                        RFDevice:hasPulseWidth  ?Quantity_0
              { ?Quantity_0  a                  Nuvio:Quantity }
            }
          }
      }
    }
  }
