PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB2xxmini_0
WHERE
  { ?USRPB2xxmini_0
              a                     SDR:USRPB2xxmini
    OPTIONAL
      { ?USRPB2xxmini_0
                  RFDevice:supportsTransmitting  ?Var0
        { ?Var0  a                     RFDevice:CoverPulsesJamming
          { ?Entity_0  RFDevice:hasMaxOutputPower  ?Var0
            { ?Entity_0  a                    Nuvio:Entity
              {   { ?Entity_0  a                    RFDevice:SpatialAreaUnit
                    { ?Entity_0  a                    RFDevice:Time
                      { ?Var1  Nuvio:hasValue  ?Entity_0 }
                    }
                  }
                UNION
                  { ?Entity_0  a                    Nuvio:Situation ;
                              Nuvio:relevantIndividual  ?NonNegativeDecimalValue_0
                    { ?MultiSurface_0
                                Nuvio:relevantIndividual  ?Entity_0
                      { ?NonNegativeDecimalValue_0
                                  RFDevice:hasDoubleValue  ?DataValue0
                        FILTER ( ! ( ?DataValue0 >= "0"^^xsd:decimal ) )
                      }
                    }
                  }
              }
            }
          }
        }
      }
  }
