PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Half_DuplexCommunicationsSystem_0
                RFDevice:isProducerOf  ?Object_0
      { ?Object_0  a                    Nuvio:Object .
        ?Value_0  Nuvio:participatesIn  ?Object_0
        { ?Value_0  a                     Nuvio:Value ;
                    Nuvio:hasUnitOfMeasure  ?InformationUnit_0
          { ?Value_0  Nuvio:hasPrecision  ?DataValue0
            FILTER ( ?DataValue0 < 189492389 )
            OPTIONAL
              { ?InformationUnit_0
                          a                     RFDevice:InformationUnit
              }
          }
        }
      }
    }
  }
