PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarWarningReceiver_0
WHERE
  { ?RadarWarningReceiver_0
              a                     RFDevice:RadarWarningReceiver
    OPTIONAL
      { ?Var0  RFDevice:supportsSpectrumSensing  ?RadarWarningReceiver_0
        { ?Var0  a                     Nuvio:Process
          { ?Value_0  Nuvio:hasValue  ?Var0
            { ?Value_0  Nuvio:hasPrecision  ?DataValue0
              FILTER ( ?DataValue0 != 378385845 )
            }
          }
        }
      }
  }
