PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?Var0  RFDevice:supportsSpectrumSensing  ?SurveillanceRadar_0
      { ?Object_0  Nuvio:expresses  ?Var0
        {   { ?Var0  a                     Nuvio:Process ;
                     Nuvio:subprocessOf    ?BarrageJamming_0
              { ?BarrageJamming_0
                          a                     RFDevice:BarrageJamming
                { ?Quantity_0  RFDevice:hasMaxOutputPower  ?BarrageJamming_0 }
              }
              { ?Var0  a                     Nuvio:Attribute }
            }
          UNION
            { ?Object_0  a                    Nuvio:Object }
        }
        OPTIONAL
          { ?Var0  a                     RFDevice:FormationJamming }
      }
    }
  }
