PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX310_0
WHERE
  { ?USRPX310_0  a                  SDR:USRPX310
    { ?Entity_0  RFDevice:hasProducer  ?USRPX310_0
      { ?Entity_0  a                    Nuvio:Entity ;
                  Nuvio:isExpressedBy   ?Entity_0
        {   { ?Entity_0  a                    RFDevice:CommunicationsSystem
              { ?Entity_1  RFDevice:isDeployedOn  ?Entity_0 }
            }
          UNION
            { ?Entity_0  a                    RFDevice:SpatialLinearUnit }
          { ?Entity_0  a                    Nuvio:Object
            { ?Var0  Nuvio:hasValue  ?Entity_0
              { ?Var0  RFDevice:hasDecimalValue  ?DataValue0
                FILTER ( ?DataValue0 <= "100"^^xsd:decimal )
                { ?Var0  a                     RFDevice:NonNegativeDecimalValue }
              }
            }
          }
        }
      }
    }
  }
