PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    { ?Entity_0  Nuvio:hasObjectQuantity  ?Full_DuplexCommunicationsSystem_0
      { ?Entity_0  a                    Nuvio:Entity ;
                  Nuvio:expresses       ?Situation_0
        OPTIONAL
          {   { ?Entity_0  a                    RFDevice:Jamming
                { ?Quantity_0  RFDevice:hasMaxOutputPower  ?Entity_0
                  { ?Quantity_0  a                  Nuvio:Quantity }
                }
              }
            UNION
              { ?Entity_0  a                    RFDevice:SpatialVolumeUnit }
            { ?Triangle_0  Nuvio:relevantIndividual  ?Entity_0
              { ?Rectangle_0  Nuvio:relevantIndividual  ?Entity_0 }
            }
          }
      }
    }
  }
