PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB205mini_i_0
WHERE
  { ?USRPB205mini_i_0
              a                     SDR:USRPB205mini-i
    { ?Spartan6FPGA_0
                Nuvio:compositeOf  ?USRPB205mini_i_0
      { ?Spartan6FPGA_0
                  a                     SDR:Spartan6FPGA
        { ?Var0  RFDevice:hasProducer  ?Spartan6FPGA_0 }
      }
    }
  }
