PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicSupportSystem_0
WHERE
  { ?ElectronicSupportSystem_0
              a                     RFDevice:ElectronicSupportSystem
    { ?Weight_0  RFDevice:hasMaxPowerConsumption  ?ElectronicSupportSystem_0
      { ?Weight_0  a                    RFDevice:Weight
        OPTIONAL
          { ?Weight_0  Nuvio:hasValue  ?Var0
            { ?Entity_0  Nuvio:hasUnitOfMeasure  ?Var0
              { ObjectDescription:Frequency_instance205
                          RFDevice:hasBandwidth  ?Entity_0
                { ?FreqencyRange_0
                            RFDevice:hasBandwidthRange  ?Entity_0
                  { ?FreqencyRange_0
                              a                     RFDevice:FreqencyRange
                    { ?Ratio_0  RFDevice:hasMin  ?FreqencyRange_0
                      { ?Ratio_0  a                     RFDevice:Ratio }
                    }
                  }
                }
                { ?Entity_0  a                    RFDevice:TimeInstant }
                { ?Entity_0  a                    Nuvio:Situation
                  { ObjectDescription:USRPE312_instance18
                              Nuvio:relevantIndividual  ?Entity_0
                  }
                }
              }
              OPTIONAL
                { ?Var0  RFDevice:hasFloatValue  ?DataValue0
                  FILTER ( ?DataValue0 > "0.0"^^xsd:double )
                }
            }
          }
      }
    }
  }
