PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ContinuousWaveRadar_0
WHERE
  { ?ContinuousWaveRadar_0
              a                     RFDevice:ContinuousWaveRadar
    OPTIONAL
      { ?IEDTrigger_0
                  Nuvio:aggregateOf  ?ContinuousWaveRadar_0
        { ?IEDTrigger_0
                    a                     RFDevice:IEDTrigger
          { ?Entity_0  RFDevice:supportsTransmitting  ?IEDTrigger_0
            { ?Entity_0  a                    Nuvio:Entity
              OPTIONAL
                { ?Entity_0  a                    RFDevice:DoubleValue
                  { ?Entity_0  a                    Nuvio:Value ;
                              Nuvio:hasUnitOfMeasure  ?Entity_0
                    OPTIONAL
                      { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                        FILTER ( ?DataValue0 < -29377461 )
                      }
                  }
                }
            }
          }
        }
      }
  }
