PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE312_0
WHERE
  { ?USRPE312_0  a                  SDR:USRPE312
    { ?Var0  RFDevice:supportsJamming  ?USRPE312_0
      { ?Power_0  RFDevice:hasMaxOutputPower  ?Var0
        { ?Power_0  a                     RFDevice:Power
          { ?Var1  Nuvio:hasValue  ?Power_0
            { ?Var1  a                     RFDevice:NonNegativeIntegerValue
              { ?Var1  RFDevice:hasFloatValue  ?DataValue0
                FILTER ( ?DataValue0 >= -1626400453 )
              }
            }
          }
        }
      }
    }
  }
