PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ContinuousWaveRadar_0
WHERE
  { ?ContinuousWaveRadar_0
              a                     RFDevice:ContinuousWaveRadar
    { ?Entity_0  RFDevice:hasCapability  ?ContinuousWaveRadar_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?UnitOfMeasure_0
                  Nuvio:expresses       ?Entity_0
        { ?Entity_0  a                    RFDevice:Distance
          { ?Var0  Nuvio:hasValue  ?Entity_0
            { ?Var0  a                     Nuvio:Value
              { ?Var0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 < -580322676 )
              }
            }
          }
          { ?Entity_0  a                    Nuvio:Process .
            ?Receiver_0  RFDevice:hasTarget  ?Entity_0
            { ?Receiver_0  a                  RFDevice:Receiver
              { ?Transceiving_0
                          RFDevice:supportsTransmitting  ?Receiver_0
                { ?Transceiving_0
                            a                     RFDevice:Transceiving
                }
              }
            }
          }
        }
      }
    }
  }
