PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?CommunicationsSystem_0
WHERE
  { ?CommunicationsSystem_0
              a                     RFDevice:CommunicationsSystem
    { ?Var0  RFDevice:hasCapability  ?CommunicationsSystem_0
      { ?Var0  a                     Nuvio:Entity
        { ?Var0  a                     gml:PolyhedralSurface
          { ?Var0  a                     Nuvio:Situation }
          OPTIONAL
            { ?Var1  Nuvio:hasValue  ?Var0
              OPTIONAL
                { ?Var0  a                     Nuvio:InformationRepresentation }
            }
        }
      }
    }
  }
