PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?PulseDopplerRadarModulation_0
                RFDevice:hasCapability  ?PulseRadar_0
      { ?PulseDopplerRadarModulation_0
                  a                     RFDevice:PulseDopplerRadarModulation
        { ?Frequency_0  RFDevice:hasTransmitPowerRange  ?PulseDopplerRadarModulation_0 }
      }
    }
  }
