PREFIX  sf:   <http://www.opengis.net/ont/sf#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    { ?Entity_0  RFDevice:hasProducer  ?Full_DuplexCommunicationsSystem_0
      { ?UnitOfMeasure_0
                  Nuvio:isExpressedBy  ?Entity_0
        { ?Entity_0  a                    sf:Line
          { ?Entity_1  Nuvio:representedBy  ?Entity_0 }
        }
      }
    }
  }
