PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Half_DuplexCommunicationsSystem_0
                Nuvio:aggregateOf  ?Entity_0
      { ?Value_0  Nuvio:expresses  ?Entity_0
        {   { ?ElectronicSupportSystem_0
                        Nuvio:expresses  ?Entity_0
            }
          UNION
            { ?ElectronicSupportSystem_0
                        a                     RFDevice:ElectronicSupportSystem
            }
        }
        { ?Value_0  a                     Nuvio:Value }
      }
    }
  }
