PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarSystem_0
WHERE
  { ?RadarSystem_0
              a                     RFDevice:RadarSystem
    { ?RadarSystem_0
                RFDevice:hasSamplingRate  ?Entity_0
      { ?Object_0  Nuvio:isExpressedBy  ?Entity_0
        { ?Entity_0  a                    RFDevice:PositiveIntegerValue
          OPTIONAL
            { ?Entity_0  a                    Nuvio:Situation }
        }
        OPTIONAL
          { ?ElectronicAttack_0
                      Nuvio:hasParticipant  ?Object_0
            { ?ElectronicAttack_0
                        a                     RFDevice:ElectronicAttack
            }
          }
      }
    }
  }
