PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarSystem_0
WHERE
  { ?RadarSystem_0
              a                     RFDevice:RadarSystem
    { ?Entity_0  RFDevice:isDeployedOn  ?RadarSystem_0
      {   { ?Entity_0  a                    Nuvio:Entity }
        UNION
          { ?Entity_0  RFDevice:isProducerOf  ?Entity_0
            { ?Quantity_0  RFDevice:hasMaxOutputPower  ?Entity_0
              { ?Entity_0  RFDevice:hasDoubleValue  ?DataValue0
                FILTER ( ?DataValue0 != 2.88 )
                OPTIONAL
                  { ?Entity_0  a                    RFDevice:Angle
                    { ?Entity_0  Nuvio:hasValue  ?Entity_0 }
                  }
              }
              { ?Entity_0  a                    Nuvio:UnitOfMeasure
                OPTIONAL
                  { ?Entity_0  a                    Nuvio:Value .
                    ?TimeUnit_0  Nuvio:hasUnitOfMeasure  ?Entity_0
                    {   { ?Entity_0  Nuvio:hasPrecision  ?DataValue1
                          FILTER ( ?DataValue1 >= -1829361611 )
                        }
                      UNION
                        { ?TimeUnit_0  a                  RFDevice:TimeUnit }
                    }
                  }
              }
            }
          }
      }
    }
  }
