PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?Entity_0  RFDevice:isProducerOf  ?SurveillanceRadar_0
      { ?InformationContent_0
                  Nuvio:expresses  ?Entity_0
        { ?Entity_0  RFDevice:hasEffectiveRadiatedPower  ?Power_0
          { ?Power_0  a                     RFDevice:Power
            { ?Power_0  Nuvio:hasValue  ?Var0 }
          }
          { ?Entity_0  a                    RFDevice:ShortValue
            { ?Entity_0  RFDevice:hasFloatValue  ?DataValue0 }
          }
        }
        { ?InformationContent_0
                    a                     Nuvio:InformationContent
        }
      }
    }
  }
