PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { ?Transmitting_0
                RFDevice:hasCapability  ?JammingSystem_0
      { ?Transmitting_0
                  a                     RFDevice:Transmitting
      }
    }
  }
