PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicSupportSystem_0
WHERE
  { ?ElectronicSupportSystem_0
              a                     RFDevice:ElectronicSupportSystem
    { ?Var0  RFDevice:supportsSpectrumSensing  ?ElectronicSupportSystem_0
      { ?InformationContent_0
                  Nuvio:isExpressedBy  ?Var0
        { ?Var0  a                     RFDevice:FrequencyScanRateUnit
          { ?Var1  Nuvio:hasValue  ?Var0 }
          { ?InformationContent_0
                      a                     Nuvio:InformationContent
          }
        }
      }
    }
  }
