PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SDR_0
WHERE
  { ?SDR_0  a                     SDR:SDR
    { ?SDR_0  Nuvio:compositeOf  ObjectDescription:RadarJammer_instance143 }
  }
