PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX310_0
WHERE
  { ?USRPX310_0  a                  SDR:USRPX310
    { ?Var0  Nuvio:compositeOf  ?USRPX310_0
      { ?Var0     a                     Nuvio:Object .
        ?Quality_0  Nuvio:hasObjectQuality  ?Var0
        { ?Quality_0  a                   Nuvio:Quality }
      }
    }
  }
