PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE3xx_0
WHERE
  { ?USRPE3xx_0  a                  SDR:USRPE3xx
    { ?Var0  RFDevice:hasCapability  ?USRPE3xx_0
      { ?Var0  a                     RFDevice:AdjustableBandwidthSensing
        { ?Var0  a                     Nuvio:Situation
          OPTIONAL
            { ?AdjustableBandwidthSensing_0
                        Nuvio:relevantIndividual  ?Var0
            }
          OPTIONAL
            { ?QuantityRange_0
                        RFDevice:hasBandwidthRange  ?Var0
              { ?QuantityRange_0
                          a                     RFDevice:QuantityRange
              }
            }
        }
      }
    }
  }
