PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ContinuousWaveRadar_0
WHERE
  { ?ContinuousWaveRadar_0
              a                     RFDevice:ContinuousWaveRadar
    { ?Entity_0  RFDevice:isProducerOf  ?ContinuousWaveRadar_0
      { ?Entity_0  a                    Nuvio:Entity ;
                  Nuvio:expresses       ?Attribute_0
        { ?Entity_0  a                    Nuvio:Value .
          ?Value_0  Nuvio:hasUnitOfMeasure  ?Entity_0
          { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
            FILTER ( ?DataValue0 > 1446374699 )
          }
          { ?Entity_0  Nuvio:hasDataValue  ?DataValue1
            FILTER ( ?DataValue1 > "93.19609"^^xsd:double )
          }
        }
      }
    }
  }
