PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX300_0
WHERE
  { ?USRPX300_0  a                  SDR:USRPX300
    { ?Transmitter_0
                Nuvio:compositeOf  ?USRPX300_0
      { ?Transmitter_0
                  a                     RFDevice:Transmitter
        { ?FreqencyRange_0
                    RFDevice:hasFrequencyRange  ?Transmitter_0
        }
      }
    }
  }
