PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB205mini_i_0
WHERE
  { ?USRPB205mini_i_0
              a                     SDR:USRPB205mini-i
    { ?Entity_0  RFDevice:hasHeight  ?USRPB205mini_i_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?InformationEntity_0
                  Nuvio:isExpressedBy   ?Entity_0
        OPTIONAL
          { ?Entity_0  a                    Nuvio:UnitOfMeasure
            { ?Entity_0  a                    Nuvio:Process .
              ?AntennaPolarization_0
                        Nuvio:hasProcessQuality  ?Entity_0
              { ?AntennaPolarization_0
                          a                     RFDevice:AntennaPolarization
              }
            }
          }
      }
    }
  }
