PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarWarningReceiver_0
WHERE
  { ?RadarWarningReceiver_0
              a                     RFDevice:RadarWarningReceiver
    { ?IEDTrigger_0
                Nuvio:compositeOf  ?RadarWarningReceiver_0
      { ?IEDTrigger_0
                  a                     RFDevice:IEDTrigger
        { ?Process_0  RFDevice:hasCapability  ?IEDTrigger_0
          { ?Process_0  a                   Nuvio:Process ;
                      Nuvio:participatesIn  ?Process_0
          }
        }
      }
    }
  }
