PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RFSystem_0
WHERE
  { ?RFSystem_0  a                  RFDevice:RFSystem
    { ?RFSystem_0  RFDevice:hasCapability  ?Var0
      { ?Var0     a                     Nuvio:Entity .
        ?Process_0  Nuvio:isExpressedBy  ?Var0
        { ?Var0  Nuvio:hasPrecision  ?DataValue0
          FILTER ( ?DataValue0 = 1392657794 )
          { ?Var0  a                     Nuvio:Attribute
            { ?Var0  a                     Nuvio:InformationRepresentation }
          }
        }
        { ?Process_0  a                   Nuvio:Process }
      }
    }
  }
