PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?USRPB2xx_0
WHERE
  { ?USRPB2xx_0  a                  SDR:USRPB2xx
    { ?Var0  RFDevice:supportsJamming  ?USRPB2xx_0
      { ?Var0  a                     RFDevice:RadarJamming
        { ObjectDescription:Power_instance31
                    RFDevice:hasTransmitPowerRange  ?Var0
        }
        { ObjectDescription:RadioFrequencyBand_instance119
                    RFDevice:hasBandwidthRange  ?Var0
        }
      }
    }
  }
