PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?RadarSystem_0
WHERE
  { ?RadarSystem_0
              a                     RFDevice:RadarSystem
    OPTIONAL
      { ?Modulation_0
                  RFDevice:hasCapability  ?RadarSystem_0
        { ?Modulation_0
                    a                     RFDevice:Modulation
        }
      }
  }
