PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { ?Entity_0  RFDevice:isProducerOf  ?JammingSystem_0
      {   { ?Entity_0  a                    Nuvio:Entity ;
                      Nuvio:expresses       ?InformationContent_0
          }
        UNION
          { ?Entity_0  a                    Nuvio:UnitOfMeasure }
      }
    }
  }
