PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN3xx_0
WHERE
  { ?USRPN3xx_0  a                  SDR:USRPN3xx
    { ?MobilePlatform_0
                RFDevice:isDeployedOn  ?USRPN3xx_0
      { ?MobilePlatform_0
                  a                     RFDevice:MobilePlatform
        { ?MobilePlatform_0
                    RFDevice:supportsSpectrumSensing  ?Entity_0
          {   { ?InformationEntity_0
                          Nuvio:isExpressedBy  ?Entity_0
              }
            UNION
              { ?Entity_0  a                    RFDevice:ElectricChargeUnit
                OPTIONAL
                  { ?Entity_0  a                    Nuvio:Object .
                    ?DeceptiveCommunicationsJamming_0
                              Nuvio:participatesIn  ?Entity_0
                  }
              }
            { ?InformationEntity_0
                        a                     Nuvio:InformationEntity
            }
          }
        }
      }
    }
  }
