PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SearchRadar_0
WHERE
  { ?SearchRadar_0
              a                     RFDevice:SearchRadar
    { ?Entity_0  RFDevice:hasProducer  ?SearchRadar_0
      {   { ?Entity_0  a                    RFDevice:Percentage }
        UNION
          { ?Var0  Nuvio:hasValue  ?Entity_0
            { ?Var0  a                     RFDevice:NonNegativeDecimalValue
              OPTIONAL
                { ?Var0  RFDevice:hasPositiveIntegerValue  ?DataValue0
                  FILTER ( ?DataValue0 >= "0"^^xsd:decimal )
                }
            }
          }
      }
    }
  }
