PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?MonostaticRadar_0
WHERE
  { ?MonostaticRadar_0
              a                     RFDevice:MonostaticRadar
    { ?Entity_0  Nuvio:aggregateOf  ?MonostaticRadar_0
      { ?InformationContent_0
                  Nuvio:expresses  ?Entity_0
        { ?Entity_0  a                    RFDevice:SpatialAreaUnit
          { ?Entity_0  a                    Nuvio:UnitOfMeasure }
        }
        { ?InformationContent_0
                    a                     Nuvio:InformationContent ;
                    Nuvio:representedBy   ?InformationRepresentation_0
          { ?InformationEntity_0
                      Nuvio:representedBy  ?InformationRepresentation_0
          }
        }
      }
    }
  }
