PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Process_0  RFDevice:supportsJamming  ?Half_DuplexCommunicationsSystem_0
      { ?AbstractCurveSegment_0
                  RFDevice:hasTarget  ?Process_0
        { ?AbstractCurveSegment_0
                    a                     gml:AbstractCurveSegment
        }
      }
    }
  }
