PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?MonostaticRadar_0
WHERE
  { ?MonostaticRadar_0
              a                     RFDevice:MonostaticRadar
    { ?Transmitter_0
                Nuvio:compositeOf  ?MonostaticRadar_0
      { ?Transmitter_0
                  a                     RFDevice:Transmitter
        { ?XC3SD1800AFPGA_0
                    Nuvio:partOf  ?Transmitter_0
        }
      }
    }
  }
