PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB200_210_0
WHERE
  { ?USRPB200_210_0
              a                     SDR:USRPB200-210
    { ?XC6SLX75FPGA_0
                Nuvio:compositeOf  ?USRPB200_210_0
      { ?XC6SLX75FPGA_0
                  a                     SDR:XC6SLX75FPGA
        { ?Spartan6FPGA_0
                    Nuvio:aggregateOf  ?XC6SLX75FPGA_0
          {   { ?Producer_0  RFDevice:hasProducer  ?Spartan6FPGA_0 }
            UNION
              { ?Producer_0  RFDevice:hasProducer  ?Spartan6FPGA_0 }
          }
        }
      }
    }
  }
