PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?MonostaticRadar_0
WHERE
  { ?MonostaticRadar_0
              a                     RFDevice:MonostaticRadar
    { ?DirectConversionReceiver_0
                Nuvio:compositeOf  ?MonostaticRadar_0
      { ?DirectConversionReceiver_0
                  RFDevice:supportsSpectrumSensing  ?Entity_0
        { ?Entity_0  a                    Nuvio:Situation .
          ObjectDescription:SDR_instance50
                    Nuvio:relevantIndividual  ?Entity_0
          OPTIONAL
            { ?Entity_0  a                    Nuvio:Quantity }
        }
      }
    }
  }
