PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?Var0  RFDevice:supportsTuning  ?SurveillanceRadar_0
      { ?Var0  a                     RFDevice:SpectrumSensing
        { ?Var0  a                     RFDevice:Transceiving }
      }
    }
  }
