PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CommunicationsSystem_0
WHERE
  { ?CommunicationsSystem_0
              a                     RFDevice:CommunicationsSystem
    { ?Weight_0  RFDevice:hasLevel  ?CommunicationsSystem_0
      { ?Weight_0  a                    RFDevice:Weight
        { ?Var0  Nuvio:hasValue  ?Weight_0
          { ?Var0     a                     Nuvio:Value .
            ObjectDescription:TimeUnit_instance2
                      Nuvio:hasUnitOfMeasure  ?Var0
            { ?Var0  Nuvio:hasPrecision  ?DataValue0
              FILTER ( ?DataValue0 != 121816987 )
            }
            { ?Var0  RFDevice:hasDoubleValue  ?DataValue1
              FILTER ( ?DataValue1 > "0.0"^^xsd:double )
            }
          }
        }
      }
    }
  }
