PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SDR_0
WHERE
  { ?SDR_0  a                     SDR:SDR
    { ?Object_0  RFDevice:hasProducer  ?SDR_0
      { ?Object_0  a                    Nuvio:Object .
        ?Time_0   RFDevice:hasWidth     ?Object_0
        { ?Var0  Nuvio:hasValue  ?Time_0 }
      }
    }
  }
