PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?Entity_0  RFDevice:supportsSpectrumSensing  ?PulseRadar_0
      { ?Process_0  Nuvio:expresses  ?Entity_0
        {   { ?Entity_0  a                    Nuvio:Situation .
              ObjectDescription:IEDTrigger_instance129
                        Nuvio:relevantIndividual  ?Entity_0
              { ObjectDescription:RadioFrequencyBand_instance73
                          Nuvio:relevantIndividual  ?Entity_0
              }
              { ?Entity_0  a                    RFDevice:AngleValue
                { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                  FILTER ( ?DataValue0 <= 710344425 )
                }
              }
              { ?Entity_0  a                    Nuvio:Attribute }
            }
          UNION
            { ?CumulativeDetection_0
                        Nuvio:hasSubprocess  ?Process_0
            }
        }
      }
    }
  }
