PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB2xxmini_0
WHERE
  { ?USRPB2xxmini_0
              a                     SDR:USRPB2xxmini
    OPTIONAL
      { ?Jammer_0  Nuvio:aggregateOf  ?USRPB2xxmini_0
        { ?Jammer_0  a                    RFDevice:Jammer
          { ?Entity_0  RFDevice:hasProducer  ?Jammer_0
            { ?Value_0  Nuvio:expresses  ?Entity_0
              { ?Entity_0  a                    RFDevice:ModelX
                { ?Entity_0  a                    RFDevice:PhaseModulation
                  {   { ?Entity_0  a                    RFDevice:FrequencyScanRate }
                    UNION
                      { ?Var0  Nuvio:hasValue  ?Entity_0
                        { ?Var0  RFDevice:hasIntegerValue  ?DataValue0
                          FILTER ( ?DataValue0 > 259189975 )
                          OPTIONAL
                            { ?Var0  Nuvio:hasPrecision  ?DataValue1
                              FILTER ( ?DataValue1 <= -1830717729 )
                            }
                        }
                      }
                  }
                }
                OPTIONAL
                  { ?Entity_0  a                    Nuvio:Object .
                    ?Attribute_0  RFDevice:hasLevel  ?Entity_0
                  }
                {   { ?PowerUnit_0  Nuvio:hasUnitOfMeasure  ?Value_0 }
                  UNION
                    { ?PowerUnit_0  a                 RFDevice:PowerUnit }
                }
              }
            }
          }
        }
      }
  }
