PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  geosparql: <http://www.opengis.net/ont/geosparql#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SearchRadar_0
WHERE
  { ?SearchRadar_0
              a                     RFDevice:SearchRadar
    { ?Entity_0  RFDevice:isProducerOf  ?SearchRadar_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_0  a                    geosparql:SpatialObject
          { ?AntennaPolarization_0
                      Nuvio:hasProcessQuality  ?Entity_0
            { ?AntennaPolarization_0
                        a                     RFDevice:AntennaPolarization
            }
          }
          OPTIONAL
            { ?Entity_0  Nuvio:hasDataValue  ?DataValue0
              FILTER ( ?DataValue0 = -40.04 )
              { ?Entity_0  a                    RFDevice:DataSize
                { ?Entity_0  Nuvio:hasValue  ?Var0
                  { ?Var0  Nuvio:hasDataValue  ?DataValue1
                    FILTER ( ?DataValue1 >= 608113416 )
                  }
                }
              }
            }
        }
      }
    }
  }
