PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?RadarJammer_0
                Nuvio:aggregateOf  ?PulseRadar_0
      { ?Entity_0  RFDevice:isProducerOf  ?RadarJammer_0
        { ?Entity_0  a                    Nuvio:Attribute }
        { ObjectDescription:Producer_instance95
                    RFDevice:hasProducer  ?RadarJammer_0
        }
      }
    }
  }
