PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE3xx_0
WHERE
  { ?USRPE3xx_0  a                  SDR:USRPE3xx
    { ?Entity_0  Nuvio:partOf  ?USRPE3xx_0
      { ?Entity_0  a                    Nuvio:Entity
        OPTIONAL
          { ?Entity_0  a                    Nuvio:Situation
            {   { ?Entity_0  a                    RFDevice:TimeInterval }
              UNION
                { ?Var0  Nuvio:hasValue  ?Entity_0
                  { ?Var0  a                     RFDevice:PositiveDecimalValue
                    { ?Var0  RFDevice:hasPositiveIntegerValue  ?DataValue0
                      FILTER ( ?DataValue0 <= 10.73 )
                    }
                    { ObjectDescription:TimeUnit_instance0
                                Nuvio:hasUnitOfMeasure  ?Var0
                    }
                  }
                }
            }
            { ?Entity_0  a                    Nuvio:Object
              OPTIONAL
                { RFDevice:Meter
                            Nuvio:hasUnitOfMeasure  ?Entity_0
                }
            }
          }
      }
    }
  }
