PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseDopplerRadar_0
WHERE
  { ?PulseDopplerRadar_0
              a                     RFDevice:PulseDopplerRadar
    OPTIONAL
      { ?Object_0  RFDevice:isProducerOf  ?PulseDopplerRadar_0
        {   { ?Object_0  a                    Nuvio:Object .
              ?DataSize_0  Nuvio:hasObjectQuantity  ?Object_0
            }
          UNION
            { ?DataSize_0  a                  RFDevice:DataSize }
        }
      }
  }
