PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN3xx_0
WHERE
  { ?USRPN3xx_0  a                  SDR:USRPN3xx
    { ?Entity_0  Nuvio:aggregateOf  ?USRPN3xx_0
      { ?Value_0  Nuvio:expresses  ?Entity_0
        OPTIONAL
          { ?Entity_0  a                    RFDevice:PositiveIntegerValue
            OPTIONAL
              {   { RFDevice:AngleUnit_Degree
                              Nuvio:hasUnitOfMeasure  ?Value_0
                  }
                UNION
                  { ?Value_0  Nuvio:hasPrecision  ?DataValue0
                    FILTER ( ?DataValue0 <= -1238347641 )
                  }
              }
          }
      }
    }
  }
