PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?BistaticRadar_0
WHERE
  { ?BistaticRadar_0
              a                     RFDevice:BistaticRadar
    { ?Var0  RFDevice:supportsTransmitting  ?BistaticRadar_0
      { ?Var0  a                     RFDevice:FixedBandwidthSensing
        { ?Var0     a                     Nuvio:Process .
          ?CoverPulsesJamming_0
                    Nuvio:subprocessOf    ?Var0
          { ?CoverPulsesJamming_0
                      Nuvio:hasProcessQuantity  ?Quantity_0
            { ?Quantity_0  a                  Nuvio:Quantity }
          }
        }
      }
    }
  }
