PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE312_0
WHERE
  { ?USRPE312_0  a                  SDR:USRPE312
    { ?Entity_0  Nuvio:aggregateOf  ?USRPE312_0
      { ?Entity_0  a                    RFDevice:AmplitudeModulation
        { ?Entity_0  a                    RFDevice:PositiveIntegerValue
          { ?Entity_0  RFDevice:hasPositiveIntegerValue  ?DataValue0
            FILTER ( ?DataValue0 <= -19.57 )
          }
        }
      }
    }
  }
