PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SearchRadar_0
WHERE
  { ?SearchRadar_0
              a                     RFDevice:SearchRadar
    OPTIONAL
      { ?Var0  RFDevice:supportsJamming  ?SearchRadar_0
        { ?Var0     a                     Nuvio:Process .
          ?Quality_0  Nuvio:hasProcessQuality  ?Var0
          { ?Quality_0  a                   Nuvio:Quality }
          { ?Var0  RFDevice:hasEffectiveRadiatedPower  ObjectDescription:Instance2315 }
          { ?Var0  a                     RFDevice:Transceiving
            { ?Var0  a                     RFDevice:BarrageJamming }
          }
        }
      }
  }
