PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB210_0
WHERE
  { ?USRPB210_0  a                  SDR:USRPB210
    { ?USRPB210_0  RFDevice:hasMaxPowerConsumption  ?Entity_0
      { ?Value_0  Nuvio:isExpressedBy  ?Entity_0
        { ?Value_0  a                     Nuvio:Value .
          ?VelocityUnit_0
                    Nuvio:hasUnitOfMeasure  ?Value_0
        }
      }
    }
  }
