PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?Entity_0  RFDevice:isProducerOf  ?ElectronicAttackSystem_0
      { ?Entity_0  a                    RFDevice:Component
        { ?Entity_0  a                    RFDevice:SpatialUnit
          { ?Entity_0  a                    Nuvio:UnitOfMeasure }
          { ?Entity_0  a                    RFDevice:Width
            { ?Entity_0  a                    Nuvio:Value .
              ?Attribute_0  Nuvio:hasUnitOfMeasure  ?Entity_0
              { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                FILTER ( ?DataValue0 <= -2012215028 )
              }
              { ?Attribute_0  a                 Nuvio:Attribute }
            }
          }
        }
      }
    }
  }
