PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?BistaticRadar_0
WHERE
  { ?BistaticRadar_0
              a                     RFDevice:BistaticRadar
    { ?BistaticRadar_0
                RFDevice:supportsTransmitting  ?PulseRadarModulation_0
      { ?PulseRadarModulation_0
                  a                     RFDevice:PulseRadarModulation
        OPTIONAL
          { ?Quantity_0  RFDevice:hasMaxOutputPower  ?PulseRadarModulation_0
            { ?Quantity_0  a                  Nuvio:Quantity }
          }
      }
    }
  }
