PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX3xx_0
WHERE
  { ?USRPX3xx_0  a                  SDR:USRPX3xx
    { ?InstantaneousFrequencyMeasurementReceiver_0
                Nuvio:compositeOf  ?USRPX3xx_0
      { ?InstantaneousFrequencyMeasurementReceiver_0
                  a                     RFDevice:InstantaneousFrequencyMeasurementReceiver
        { ?InstantaneousFrequencyMeasurementReceiver_0
                    Nuvio:partOf  ?Entity_0
          { ?Attribute_0  Nuvio:expresses  ?Entity_0
            { ?Entity_0  a                    Nuvio:Attribute }
          }
        }
      }
    }
  }
