PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarSystem_0
WHERE
  { ?RadarSystem_0
              a                     RFDevice:RadarSystem
    { ?Entity_0  RFDevice:hasProducer  ?RadarSystem_0
      { ?Situation_0  Nuvio:isExpressedBy  ?Entity_0
        { ?FormationJamming_0
                    Nuvio:subprocessOf  ?Entity_0
          { ?FormationJamming_0
                      a                     RFDevice:FormationJamming
            { ?FormationJamming_0
                        RFDevice:hasTransmitPowerRange  ?Power_0
              { ?Power_0  a                     RFDevice:Power }
            }
          }
        }
      }
    }
  }
