PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ModelX_0
WHERE
  { ?ModelX_0  a                    RFDevice:ModelX
    { ?ModelX_0  Nuvio:aggregateOf  ?IEDTrigger_0
      { ?IEDTrigger_0
                  a                     RFDevice:IEDTrigger
        { ?Attribute_0  RFDevice:hasNoiseFigure  ?IEDTrigger_0 }
      }
    }
  }
