PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX310_0
WHERE
  { ?USRPX310_0  a                  SDR:USRPX310
    { ?InstantaneousFrequencyMeasurementReceiver_0
                Nuvio:compositeOf  ?USRPX310_0
      {   { ?InstantaneousFrequencyMeasurementReceiver_0
                      a                     RFDevice:InstantaneousFrequencyMeasurementReceiver
          }
        UNION
          { ?InstantaneousFrequencyMeasurementReceiver_0
                      RFDevice:hasNoiseFigure  ?Entity_0
            { ?UnitOfMeasure_0
                        Nuvio:isExpressedBy  ?Entity_0
            }
          }
      }
    }
  }
