PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    { ?Entity_0  RFDevice:hasMaxPowerConsumption  ?Full_DuplexCommunicationsSystem_0
      { ?Value_0  Nuvio:expresses  ?Entity_0
        OPTIONAL
          { ?Entity_0  a                    gml:Solid }
        {   { ?Value_0  a                     Nuvio:Value }
          UNION
            { ?Value_0  Nuvio:hasPrecision  ?DataValue0
              FILTER ( ?DataValue0 = -1521806570 )
            }
        }
      }
    }
  }
