PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RFSystem_0
WHERE
  { ?RFSystem_0  a                  RFDevice:RFSystem
    { ?Var0  RFDevice:supportsJamming  ?RFSystem_0
      { ?Frequency_0  RFDevice:hasBandwidth  ?Var0
        { ?Frequency_0  a                 RFDevice:Frequency
          { ?Var1  Nuvio:hasValue  ?Frequency_0
            { ?Var1  Nuvio:hasPrecision  ?DataValue0
              FILTER ( ?DataValue0 >= -1297140291 )
            }
          }
        }
      }
    }
  }
