PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN310_0
WHERE
  { ?USRPN310_0  a                  SDR:USRPN310
    OPTIONAL
      { ?USRPN310_0  RFDevice:supportsTransmitting  ?Var0
        { ?Var0  a                     RFDevice:SpectrumSensing
          { ObjectDescription:Power_instance55
                      RFDevice:hasEffectiveRadiatedPower  ?Var0
            { ?Var0     a                     Nuvio:Entity .
              ?InformationContent_0
                        Nuvio:isExpressedBy   ?Var0
              { ?InformationContent_0
                          a                     Nuvio:InformationContent .
                ?InformationEntity_0
                          Nuvio:representedBy   ?InformationContent_0
              }
            }
          }
        }
      }
  }
