PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?TrackingRadar_0
WHERE
  { ?TrackingRadar_0
              a                     RFDevice:TrackingRadar
    { ?Entity_0  Nuvio:compositeOf  ?TrackingRadar_0
      { ?Entity_0  a                    RFDevice:EmitterIdentification
        { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
          FILTER ( ?DataValue0 >= -1432098864 )
        }
        { ?Entity_0  a                    Nuvio:Object
          { ?Entity_0  a                    Nuvio:Attribute }
        }
      }
    }
  }
