PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Entity_0  RFDevice:hasCapability  ?Half_DuplexCommunicationsSystem_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?UnitOfMeasure_0
                  Nuvio:isExpressedBy   ?Entity_0
        OPTIONAL
          {   { ?Entity_0  a                    RFDevice:NonNegativeIntegerValue
                { ?Entity_0  RFDevice:hasDecimalValue  ?DataValue0
                  FILTER ( ?DataValue0 >= 828849723 )
                }
              }
            UNION
              { ?Entity_0  Nuvio:hasValue  ?Var0
                { ?Var0  RFDevice:hasFloatValue  ?DataValue1
                  { ?Var0     a                     Nuvio:Value .
                    RFDevice:MilliampereHour
                              Nuvio:hasUnitOfMeasure  ?Var0
                    { ?Var0  Nuvio:hasPrecision  ?DataValue2
                      FILTER ( ?DataValue2 != 1610037126 )
                    }
                  }
                }
              }
            { ?Entity_0  a                    Nuvio:InformationEntity .
              ?USRPB2xxmini_0
                        Nuvio:expresses       ?Entity_0
              { ?USRPB2xxmini_0
                          a                     SDR:USRPB2xxmini
              }
            }
          }
      }
    }
  }
