PREFIX  sf:   <http://www.opengis.net/ont/sf#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?Entity_0  RFDevice:hasProducer  ?ElectronicAttackSystem_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_0  a                    gml:MultiSolid
          { ?Entity_0  a                    Nuvio:Quality }
          { ?Entity_0  a                    Nuvio:Situation ;
                      Nuvio:relevantIndividual  ?Geometry_0
            { ?Geometry_0  a                  sf:Geometry }
          }
        }
      }
    }
  }
