PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE3xx_0
WHERE
  { ?USRPE3xx_0  a                  SDR:USRPE3xx
    { ?Entity_0  RFDevice:isProducerOf  ?USRPE3xx_0
      { ?Entity_0  a                    Nuvio:Entity
        OPTIONAL
          {   { ?Entity_0  a                    SDR:USRPB2xx
                { ?RadioComponent_0
                            Nuvio:compositeOf  ?Entity_0
                  { ?RadioComponent_0
                              a                     RFDevice:RadioComponent
                  }
                }
              }
            UNION
              { ?Entity_0  a                    RFDevice:ElectricChargeUnit
                { ?Entity_0  a                    RFDevice:Voltage
                  OPTIONAL
                    { ?Var0  Nuvio:hasValue  ?Entity_0
                      { ?Var0  RFDevice:hasNonNegativeIntegerValue  ?DataValue0
                        FILTER ( ?DataValue0 >= "77.289856"^^xsd:double )
                      }
                    }
                }
              }
            {   { ?WeightUnit_0
                            Nuvio:hasUnitOfMeasure  ?Entity_0
                }
              UNION
                { ?WeightUnit_0
                            a                     RFDevice:WeightUnit
                }
              { ?QuantityRange_0
                          Nuvio:relevantIndividual  ?Entity_0
                { ?QuantityRange_0
                            a                     RFDevice:QuantityRange
                }
              }
            }
          }
      }
    }
  }
