PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB2xx_0
WHERE
  { ?USRPB2xx_0  a                  SDR:USRPB2xx
    { ?Entity_0  RFDevice:hasChargingTime  ?USRPB2xx_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_0  a                    RFDevice:Platform
          OPTIONAL
            { ?Entity_0  a                    Nuvio:Object
              { ?Value_0  Nuvio:hasUnitOfMeasure  ?Entity_0 }
            }
        }
      }
    }
  }
