PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?TrackingRadar_0
WHERE
  { ?TrackingRadar_0
              a                     RFDevice:TrackingRadar
    { ?IEDJammer_0  Nuvio:compositeOf  ?TrackingRadar_0
      { ?Entity_0  RFDevice:hasFrequencyAccuracy  ?IEDJammer_0
        { ?Entity_0  a                    Nuvio:Situation .
          ?Value_0  Nuvio:relevantIndividual  ?Entity_0
          { ?Value_0  a                     Nuvio:Value }
        }
      }
    }
  }
