PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Jammer_0  Nuvio:compositeOf  ?Half_DuplexCommunicationsSystem_0
      { ?Jammer_0  a                    RFDevice:Jammer
        { ?TerrainBounceJamming_0
                    RFDevice:supportsJamming  ?Jammer_0
          { ?TerrainBounceJamming_0
                      a                     RFDevice:TerrainBounceJamming
          }
        }
      }
    }
  }
