PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SDR_0
WHERE
  { ?SDR_0  a                     SDR:SDR
    { ?Var0  RFDevice:hasCapability  ?SDR_0
      { ?Var0  a                     Nuvio:UnitOfMeasure
        {   { ?Var0  a                     RFDevice:PulseDopplerRadarModulation
              { ?Var0  a                     RFDevice:Time
                { ?Var0  Nuvio:hasValue  ?Var1
                  { ?Var1  a                     RFDevice:PositiveDecimalValue }
                }
              }
            }
          UNION
            { ?Var0  a                     Nuvio:InformationEntity .
              ?Var2  Nuvio:informationSource  ?Var0
              {   { ?Var2  a                     RFDevice:PhasedArrayAntenna
                    OPTIONAL
                      { ?Attribute_0  RFDevice:hasSamplingRate  ?Var2
                        { ?Attribute_0  a                 Nuvio:Attribute }
                      }
                  }
                UNION
                  { ?CyclostationaryDetection_0
                              Nuvio:subprocessOf  ?Var2
                    OPTIONAL
                      { ?CyclostationaryDetection_0
                                  a                     RFDevice:CyclostationaryDetection
                      }
                  }
              }
            }
        }
      }
    }
  }
