PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE313_0
WHERE
  { ?USRPE313_0  a                  SDR:USRPE313
    { ?Receiver_0  Nuvio:compositeOf  ?USRPE313_0
      { ?Receiver_0  a                  RFDevice:Receiver
        { ?Process_0  RFDevice:supportsTuning  ?Receiver_0
          { ?Process_0  a                   Nuvio:Process .
            ?DigitalModulation_0
                      Nuvio:hasSubprocess   ?Process_0
          }
        }
      }
    }
  }
