PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE313_0
WHERE
  { ?USRPE313_0  a                  SDR:USRPE313
    { ?Var0  RFDevice:hasNoiseFigure  ?USRPE313_0
      { ?Var1  Nuvio:hasValue  ?Var0
        { ?Var1  a                     RFDevice:PositiveDecimalValue
          { ?Var1  Nuvio:hasPrecision  ?DataValue0
            FILTER ( ?DataValue0 <= 1955252304 )
          }
        }
      }
    }
  }
