PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?USRPN300_0
WHERE
  { ?USRPN300_0  a                  SDR:USRPN300
    { ?USRPN300_0  Nuvio:compositeOf  ?Var0
      { ?Var0     a                     Nuvio:Entity .
        ?Object_0  Nuvio:isExpressedBy  ?Var0
        {   { ?Var0  a                     gml:BSpline }
          UNION
            { ?Var0  a                     RFDevice:Frequency }
        }
      }
    }
  }
