PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  sf:   <http://www.opengis.net/ont/sf#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB200_210_0
WHERE
  { ?USRPB200_210_0
              a                     SDR:USRPB200-210
    { ?Entity_0  RFDevice:hasSamplingRate  ?USRPB200_210_0
      {   { ?Entity_0  a                    Nuvio:Entity }
        UNION
          {   { ?Entity_0  a                    sf:LinearRing }
            UNION
              { ?Entity_0  a                    RFDevice:PulseRadarModulation }
            { ?Entity_0  a                    RFDevice:Weight }
          }
      }
    }
  }
