PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?Entity_0  RFDevice:hasProducer  ?ElectronicAttackSystem_0
      { ?Process_0  Nuvio:isExpressedBy  ?Entity_0
        { ?Voltage_0  RFDevice:hasEffectiveRadiatedPower  ?Process_0
          { ?Voltage_0  a                   RFDevice:Voltage
            { ?Var0  Nuvio:hasValue  ?Voltage_0 }
          }
        }
      }
    }
  }
