PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { ?JammingSystem_0
                Nuvio:aggregateOf  ?RadarJammer_0
      { ?Transmitting_0
                  RFDevice:supportsTuning  ?RadarJammer_0
        { ?Transmitting_0
                    a                     RFDevice:Transmitting
          { ObjectDescription:Power_instance25
                      RFDevice:hasMaxOutputPower  ?Transmitting_0
          }
        }
      }
    }
  }
