PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?TrackingRadar_0
WHERE
  { ?TrackingRadar_0
              a                     RFDevice:TrackingRadar
    { ?TrackingRadar_0
                RFDevice:hasCapability  ?PulseDopplerRadarModulation_0
      {   { ?PulseDopplerRadarModulation_0
                      a                     RFDevice:PulseDopplerRadarModulation
          }
        UNION
          { ?PulseDopplerRadarModulation_0
                      RFDevice:hasMaxSensedPower  ?Entity_0
            { ?Entity_0  a                    Nuvio:Entity
              { ?Entity_0  a                    gml:Cone }
            }
          }
      }
    }
  }
