PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?Entity_0  RFDevice:hasProducer  ?PulseRadar_0
      { ?Var0  Nuvio:hasValue  ?Entity_0
        { ?Var0  Nuvio:hasUnitOfMeasure  ?TimeUnit_0
          { ?TimeUnit_0  a                  RFDevice:TimeUnit }
        }
        { ?Entity_0  a                    Nuvio:InformationRepresentation .
          ?InformationEntity_0
                    Nuvio:represents      ?Entity_0
        }
      }
    }
  }
