PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarSystem_0
WHERE
  { ?RadarSystem_0
              a                     RFDevice:RadarSystem
    { ?RadarSystem_0
                RFDevice:supportsJamming  ?Var0
      {   { ?Value_0  Nuvio:isExpressedBy  ?Var0 }
        UNION
          { ?Var0  a                     RFDevice:FrequencyModulation
            { ?Var0  Nuvio:informationSource  ?Var1
              {   { ?Var0  a                     RFDevice:TimeInterval }
                UNION
                  { ?Var0  a                     Nuvio:Attribute }
              }
            }
            { ?Value_0  Nuvio:hasPrecision  ?DataValue0
              FILTER ( ?DataValue0 != 1760813085 )
            }
          }
      }
    }
  }
