PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarWarningReceiver_0
WHERE
  { ?RadarWarningReceiver_0
              a                     RFDevice:RadarWarningReceiver
    { ?RadarWarningReceiver_0
                Nuvio:partOf  ?Entity_0
      { ?Entity_0  a                    Nuvio:UnitOfMeasure
        { ?Entity_0  a                    Nuvio:InformationEntity .
          ?MonostaticRadar_0
                    Nuvio:expresses       ?Entity_0
          { ?Object_0  RFDevice:hasProducer  ?MonostaticRadar_0
            { ?Object_0  a                    Nuvio:Object .
              ?ContinuousWaveRadarModulation_0
                        RFDevice:supportsSpectrumSensing  ?Object_0
              { ?ContinuousWaveRadarModulation_0
                          a                     RFDevice:ContinuousWaveRadarModulation
              }
            }
          }
        }
      }
    }
  }
