PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX3xx_0
WHERE
  { ?USRPX3xx_0  a                  SDR:USRPX3xx
    { ?USRPX3xx_0  Nuvio:compositeOf  ObjectDescription:Jammer_instance14 }
  }
