PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Var0  RFDevice:hasCapability  ?Half_DuplexCommunicationsSystem_0
      { ?InboundRangeGatePullOffJamming_0
                  Nuvio:subprocessOf  ?Var0
        OPTIONAL
          { ?InboundRangeGatePullOffJamming_0
                      a                     RFDevice:InboundRangeGatePullOffJamming
          }
      }
    }
  }
