PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB210_0
WHERE
  { ?USRPB210_0  a                  SDR:USRPB210
    { ?Var0  RFDevice:supportsTransmitting  ?USRPB210_0
      { ?Var0  a                     RFDevice:BlinkingJamming
        OPTIONAL
          { ?Entity_0  RFDevice:hasMaxOutputPower  ?Var0
            {   { ?Entity_0  a                    Nuvio:Entity }
              UNION
                { ?Entity_0  a                    RFDevice:CyclostationaryDetection
                  { ?Entity_0  a                    RFDevice:LongitudeValueInRadian }
                  { ?Entity_0  a                    Nuvio:Quality
                    {   { ?Entity_0  a                    Nuvio:InformationEntity .
                          ?FeatureDetection_0
                                    Nuvio:expresses       ?Entity_0
                        }
                      UNION
                        { ?FeatureDetection_0
                                    a                     RFDevice:FeatureDetection
                        }
                    }
                  }
                }
            }
          }
      }
    }
  }
