PREFIX  geosparql: <http://www.opengis.net/ont/geosparql#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?PulseDopplerRadar_0
WHERE
  { ?PulseDopplerRadar_0
              a                     RFDevice:PulseDopplerRadar
    { ?Transmitter_0
                Nuvio:partOf  ?PulseDopplerRadar_0
      { ?Object_0  RFDevice:hasFrequencyAccuracy  ?Transmitter_0
        { ?Object_0  a                    Nuvio:Object .
          ?Entity_0  RFDevice:hasPolarization  ?Object_0
          { ?Entity_0  a                    Nuvio:Entity .
            ?Entity_1  Nuvio:isExpressedBy  ?Entity_0
            { ?Entity_0  a                    RFDevice:RadioComponent
              OPTIONAL
                { ?Entity_0  Nuvio:relevantIndividual  ?GeometricComplex_0
                  OPTIONAL
                    { ?Geometry_0  Nuvio:relevantIndividual  ?Entity_0
                      { ?Geometry_0  geosparql:asWKT  ?DataValue0 }
                    }
                  { ?GeometricComplex_0
                              a                     gml:GeometricComplex
                  }
                }
            }
          }
        }
      }
    }
  }
