PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ContinuousWaveRadar_0
WHERE
  { ?ContinuousWaveRadar_0
              a                     RFDevice:ContinuousWaveRadar
    { ?ContinuousWaveRadar_0
                RFDevice:hasCapability  ?Process_0
      { ?Process_0  Nuvio:hasSubprocess  ?FormationJamming_0
        { ?FormationJamming_0
                    a                     RFDevice:FormationJamming
          { ?Entity_0  RFDevice:hasPulseRepetitionFrequency  ?FormationJamming_0
            {   { ?Situation_0  Nuvio:isExpressedBy  ?Entity_0 }
              UNION
                { ?Situation_0  a                 Nuvio:Situation
                  OPTIONAL
                    { ?IEDTrigger_0
                                Nuvio:relevantIndividual  ?Situation_0
                      { ?IEDTrigger_0
                                  a                     RFDevice:IEDTrigger
                      }
                    }
                }
            }
          }
        }
      }
    }
  }
