PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN3xx_0
WHERE
  { ?USRPN3xx_0  a                  SDR:USRPN3xx
    { ?Var0  RFDevice:hasCapability  ?USRPN3xx_0
      { ?Var0  a                     RFDevice:FixedBandwidthSensing
        { ?Entity_0  RFDevice:hasBandwidth  ?Var0
          { ?Entity_0  a                    Nuvio:Entity .
            ?Attribute_0  Nuvio:isExpressedBy  ?Entity_0
            OPTIONAL
              { ?Entity_0  a                    Nuvio:UnitOfMeasure }
            { ?Attribute_0  a                 Nuvio:Attribute }
          }
          { ?Var0  RFDevice:hasBandwidthRange  ?Entity_1 }
        }
      }
    }
  }
