PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    OPTIONAL
      { ?SuperheterodyneReceiver_0
                  Nuvio:partOf  ?JammingSystem_0
        { ?SuperheterodyneReceiver_0
                    a                     RFDevice:SuperheterodyneReceiver
          { ObjectDescription:Antenna_instance5
                      Nuvio:aggregateOf  ?SuperheterodyneReceiver_0
          }
        }
      }
  }
