PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?TrackingRadar_0
WHERE
  { ?TrackingRadar_0
              a                     RFDevice:TrackingRadar
    { ?Entity_0  RFDevice:hasNoiseFigure  ?TrackingRadar_0
      { ?Process_0  Nuvio:isExpressedBy  ?Entity_0
        { ?Entity_0  a                    gml:AbstractParametricCurveSurface
          { ?Entity_0  a                    Nuvio:Process .
            ObjectDescription:AntennaPolarization_instance18
                      Nuvio:hasProcessQuality  ?Entity_0
          }
        }
      }
    }
  }
