PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CommunicationsSystem_0
WHERE
  { ?CommunicationsSystem_0
              a                     RFDevice:CommunicationsSystem
    { ?Object_0  RFDevice:hasProducer  ?CommunicationsSystem_0
      { ?Object_0  a                    Nuvio:Object .
        ?Process_0  RFDevice:supportsTuning  ?Object_0
        OPTIONAL
          { ?Object_1  Nuvio:subprocessOf  ?Process_0 }
      }
    }
  }
