PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ModelX_0
WHERE
  { ?ModelX_0  a                    RFDevice:ModelX
    OPTIONAL
      { ?Ship_0  RFDevice:isDeployedOn  ?ModelX_0
        { ?Entity_0  RFDevice:supportsSpectrumSensing  ?Ship_0
          { ?Entity_0  a                    Nuvio:Entity .
            ?Entity_1  Nuvio:isExpressedBy  ?Entity_0
            { ?Entity_0  a                    Nuvio:Quality
              {   { ?Entity_0  a                    Nuvio:Situation .
                    ObjectDescription:InstantaneousFrequencyMeasurementReceiver_instance29
                              Nuvio:relevantIndividual  ?Entity_0
                    OPTIONAL
                      { ObjectDescription:Producer_instance207
                                  Nuvio:relevantIndividual  ?Entity_0
                      }
                  }
                UNION
                  { ?PolygonPatch_0
                              Nuvio:expresses  ?Entity_0
                  }
              }
            }
          }
        }
      }
  }
