PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN3xx_0
WHERE
  { ?USRPN3xx_0  a                  SDR:USRPN3xx
    { ?XilinxZynq7100SoC_0
                Nuvio:compositeOf  ?USRPN3xx_0
      { ?XilinxZynq7100SoC_0
                  Nuvio:aggregateOf  ?RadioComponent_0
        { ?Entity_0  RFDevice:hasProducer  ?RadioComponent_0
          { ?UnitOfMeasure_0
                      Nuvio:isExpressedBy  ?Entity_0
          }
        }
      }
    }
  }
