PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB200mini_i_0
WHERE
  { ?USRPB200mini_i_0
              a                     SDR:USRPB200mini-i
    { ?USRPB200mini_i_0
                Nuvio:compositeOf  ?XC6SLX75FPGA_0
      { ?XC6SLX75FPGA_0
                  a                     SDR:XC6SLX75FPGA
      }
    }
  }
