PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?ElectronicAttackSystem_0
                Nuvio:partOf  ?IEDJammer_0
      { ?IEDJammer_0  a                 RFDevice:IEDJammer
        { ObjectDescription:FreqencyRange_instance31
                    RFDevice:hasFrequencyRange  ?IEDJammer_0
        }
      }
    }
  }
