PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicSupportSystem_0
WHERE
  { ?ElectronicSupportSystem_0
              a                     RFDevice:ElectronicSupportSystem
    { ?RadarJammer_0
                Nuvio:partOf  ?ElectronicSupportSystem_0
      { ?RadarJammer_0
                  a                     RFDevice:RadarJammer
        OPTIONAL
          { ?TerrainBounceJamming_0
                      RFDevice:supportsJamming  ?RadarJammer_0
            { ?TerrainBounceJamming_0
                        a                     RFDevice:TerrainBounceJamming
            }
          }
      }
    }
  }
