PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SDR_0
WHERE
  { ?SDR_0  a                     SDR:SDR
    { ?Entity_0  RFDevice:hasProducer  ?SDR_0
      { ?Entity_0  Nuvio:isExpressedBy  ?UnitOfMeasure_0
        { ?Entity_0  a                    Nuvio:UnitOfMeasure
          { ?Entity_0  a                    RFDevice:TimeInstant
            OPTIONAL
              { ?Var0  Nuvio:hasValue  ?Entity_0
                {   { ?Var0  RFDevice:hasFloatValue  ?DataValue0
                      FILTER ( ?DataValue0 > "0"^^xsd:decimal )
                    }
                  UNION
                    { ?Var0  RFDevice:hasDoubleValue  ?DataValue1
                      FILTER ( ?DataValue1 > 86.55 )
                    }
                }
              }
            { ?Entity_0  a                    Nuvio:Process .
              ?ADC_0    RFDevice:hasTarget    ?Entity_0
            }
          }
        }
      }
    }
  }
