PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?IEDTrigger_0
                Nuvio:compositeOf  ?ElectronicAttackSystem_0
      { ?IEDTrigger_0
                  a                     RFDevice:IEDTrigger
        { ?IEDTrigger_0
                    Nuvio:compositeOf  ?DipoleAntenna_0
          { ?DipoleAntenna_0
                      Nuvio:partOf  ?XC3SD3400AFPGA_0
          }
        }
      }
    }
  }
