PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN2xx_0
WHERE
  { ?USRPN2xx_0  a                  SDR:USRPN2xx
    OPTIONAL
      { ?USRPN2xx_0  Nuvio:compositeOf  ?Var0
        { ?Var0  a                     RFDevice:Jamming
          { ?Var0  RFDevice:hasEffectiveRadiatedPower  ?Attribute_0
            { ?Attribute_0  a                 Nuvio:Attribute }
          }
          {   { ?Var0  a                     RFDevice:TimeUnit }
            UNION
              { ?Var1  Nuvio:hasValue  ?Var0
                { ?Var1  Nuvio:hasUnitOfMeasure  ?SpatialUnit_0 }
              }
          }
        }
      }
  }
