PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CommunicationsSystem_0
WHERE
  { ?CommunicationsSystem_0
              a                     RFDevice:CommunicationsSystem
    { ?Weight_0  RFDevice:hasGain  ?CommunicationsSystem_0
      { ?Weight_0  a                    RFDevice:Weight
        OPTIONAL
          { ?Weight_0  Nuvio:hasValue  ?Var0
            { ?UnitOfMeasure_0
                        Nuvio:hasUnitOfMeasure  ?Var0
              OPTIONAL
                { ?Var0  RFDevice:hasDoubleValue  ?DataValue0
                  FILTER ( ! ( ?DataValue0 > "0.0"^^xsd:double ) )
                }
            }
          }
      }
    }
  }
