PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarSystem_0
WHERE
  { ?RadarSystem_0
              a                     RFDevice:RadarSystem
    OPTIONAL
      { ?Entity_0  RFDevice:hasBeamwidth  ?RadarSystem_0
        { ?Entity_0  a                    Nuvio:Entity
          { ?Entity_0  a                    SDR:XC6SLX75FPGA
            { ?Var0  RFDevice:isProducerOf  ?Entity_0 }
            {   { ?Entity_0  a                    RFDevice:DeceptiveJamming
                  { ?Entity_0  a                    RFDevice:DoubleValue }
                }
              UNION
                { ?Entity_0  a                    Nuvio:Situation }
            }
            { ?Entity_0  a                    Nuvio:Attribute }
          }
        }
      }
  }
