PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CR_0
WHERE
  { ?CR_0  a                     SDR:CR
    { ?Entity_0  Nuvio:hasObjectQuantity  ?CR_0
      {   { ?Entity_0  a                    Nuvio:Entity .
            ?Attribute_0  Nuvio:isExpressedBy  ?Entity_0
          }
        UNION
          { ?Var0  RFDevice:isProducerOf  ?Entity_0
            OPTIONAL
              { ?Entity_0  a                    RFDevice:Distance
                { ?Var1  Nuvio:hasValue  ?Entity_0 }
              }
          }
        { ?Attribute_0  a                 Nuvio:Attribute }
      }
    }
  }
