PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX3xx_0
WHERE
  { ?USRPX3xx_0  a                  SDR:USRPX3xx
    { ?Entity_0  RFDevice:isProducerOf  ?USRPX3xx_0
      { ?Var0  RFDevice:hasNoiseFigure  ?Entity_0
        { ?Var0  Nuvio:hasValue  ?Var1
          {   { ?Var1  RFDevice:hasDecimalValue  ?DataValue0
                FILTER ( ?DataValue0 > "0"^^xsd:decimal )
              }
            UNION
              { RFDevice:Decibel
                          Nuvio:hasUnitOfMeasure  ?Var1
              }
          }
        }
        {   { ?Weight_0  Nuvio:isExpressedBy  ?Entity_0 }
          UNION
            { ?Weight_0  a                    RFDevice:Weight }
        }
      }
    }
  }
