PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SDR_0
WHERE
  { ?SDR_0  a                     SDR:SDR
    { ?Var0  RFDevice:supportsSpectrumSensing  ?SDR_0
      {   { ?Var0  a                     RFDevice:AdjustableBandwidthSensing }
        UNION
          { ?Entity_0  RFDevice:hasBandwidth  ?Var0
            { ?Entity_0  a                    Nuvio:Entity ;
                        Nuvio:expresses       ?Entity_0
              { ?Entity_0  a                    RFDevice:LatitudeValue
                { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                  FILTER ( ?DataValue0 != 1076261868 )
                }
                { ?Ratio_0  RFDevice:hasNoiseFigure  ?Entity_0 }
              }
            }
          }
        OPTIONAL
          { ?Var0  a                     RFDevice:Receiving }
      }
    }
  }
