PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?BistaticRadar_0
WHERE
  { ?BistaticRadar_0
              a                     RFDevice:BistaticRadar
    { ?Entity_0  RFDevice:isProducerOf  ?BistaticRadar_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_0  a                    RFDevice:SweptSpotJamming
          OPTIONAL
            { ObjectDescription:Power_instance17
                        Nuvio:hasProcessQuantity  ?Entity_0
            }
          { ?Entity_0  a                    RFDevice:LatitudeValueInRadian }
          OPTIONAL
            { ?Entity_0  a                    Nuvio:Attribute
              { ?Entity_0  Nuvio:represents  ?InformationEntity_0
                { ?InformationEntity_0
                            a                     Nuvio:InformationEntity
                }
              }
            }
        }
      }
    }
  }
