PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX310_0
WHERE
  { ?USRPX310_0  a                  SDR:USRPX310
    { ?Entity_0  Nuvio:aggregateOf  ?USRPX310_0
      { ?Entity_0  a                    Nuvio:UnitOfMeasure
        { ?ContinuousWaveRadar_0
                    Nuvio:expresses  ?Entity_0
          { ?ContinuousWaveRadar_0
                      a                     RFDevice:ContinuousWaveRadar
            { ?ContinuousWaveRadar_0
                        Nuvio:partOf  ?IEDTrigger_0
              { ?IEDTrigger_0
                          a                     RFDevice:IEDTrigger
              }
            }
          }
        }
      }
    }
  }
