PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB200_0
WHERE
  { ?USRPB200_0  a                  SDR:USRPB200
    { ?USRPB200_0  Nuvio:partOf  ?Object_0
      { ObjectDescription:Instance162
                  Nuvio:participatesIn  ?Object_0
      }
    }
  }
