PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    OPTIONAL
      { ?RadioComponent_0
                  Nuvio:aggregateOf  ?ElectronicAttackSystem_0
        { ?Spartan3ADSPFPGA_0
                    Nuvio:compositeOf  ?RadioComponent_0
          { ObjectDescription:Spartan6FPGA_instance0
                      Nuvio:aggregateOf  ?Spartan3ADSPFPGA_0
          }
        }
      }
  }
