PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { ?JammingSystem_0
                RFDevice:supportsJamming  ?Var0
      { ?Var0  a                     RFDevice:FixedBandwidthSensing
        { ObjectDescription:Instance543
                    RFDevice:hasMaxSensedPower  ?Var0
        }
        { ?Var0  a                     Nuvio:Entity
          { ?Var0     a                     Nuvio:Object .
            ObjectDescription:ElectronicSupport_instance2
                      Nuvio:hasParticipant  ?Var0
          }
        }
      }
    }
  }
