PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarSystem_0
WHERE
  { ?RadarSystem_0
              a                     RFDevice:RadarSystem
    OPTIONAL
      { ?RadarSystem_0
                  Nuvio:partOf  ?RadarJammer_0
        { ?RadarJammer_0
                    a                     RFDevice:RadarJammer
          OPTIONAL
            { ?Entity_0  RFDevice:hasFrequencyRange  ?RadarJammer_0
              { ?Entity_0  a                    Nuvio:Entity
                { ?Entity_0  a                    RFDevice:RadioFrequencyBand }
              }
            }
        }
      }
  }
