PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Entity_0  Nuvio:hasObjectQuantity  ?Half_DuplexCommunicationsSystem_0
      {   { ?InformationRepresentation_0
                      Nuvio:expresses  ?Entity_0
            { ?Entity_0  a                    RFDevice:DecimalValue
              { ?Entity_0  RFDevice:hasDoubleValue  ?DataValue0
                FILTER ( ?DataValue0 < 81.8 )
              }
              OPTIONAL
                { ?Var0  Nuvio:hasValue  ?Entity_0
                  OPTIONAL
                    { ?Entity_0  a                    Nuvio:Attribute }
                }
            }
          }
        UNION
          { ?InformationRepresentation_0
                      a                     Nuvio:InformationRepresentation .
            ?InformationContent_0
                      Nuvio:represents      ?InformationRepresentation_0
            { ?InformationContent_0
                        a                     Nuvio:InformationContent
            }
          }
      }
    }
  }
