PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    { ?UnmannedPlatform_0
                RFDevice:isDeployedOn  ?Full_DuplexCommunicationsSystem_0
      { ?UnmannedPlatform_0
                  a                     RFDevice:UnmannedPlatform
      }
    }
  }
