PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    OPTIONAL
      { ?Satellite_0  RFDevice:isDeployedOn  ?SurveillanceRadar_0
        { ObjectDescription:Moving_instance7
                    RFDevice:supportsSpectrumSensing  ?Satellite_0
        }
      }
  }
