PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?MonostaticRadar_0
WHERE
  { ?MonostaticRadar_0
              a                     RFDevice:MonostaticRadar
    OPTIONAL
      { ?Entity_0  RFDevice:isProducerOf  ?MonostaticRadar_0
        { ?InformationRepresentation_0
                    Nuvio:isExpressedBy  ?Entity_0
          { ?Entity_0  a                    RFDevice:CoverPulsesJamming
            { ?Entity_0  a                    RFDevice:SpatialAreaUnit }
          }
        }
      }
  }
