PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    OPTIONAL
      { ?Entity_0  RFDevice:supportsTuning  ?PulseRadar_0
        { ?Entity_0  a                    Nuvio:Entity .
          ?Value_1  Nuvio:isExpressedBy   ?Entity_0
          {   { ?Entity_0  a                    gml:AbstractParametricCurveSurface }
            UNION
              { ?Entity_0  a                    RFDevice:NoiseJamming
                { ?Attribute_0  RFDevice:hasPulseRepetitionFrequency  ?Entity_0 }
              }
            { ?AntennaPolarization_0
                        Nuvio:hasProcessQuality  ?Entity_0
            }
            OPTIONAL
              { ?Entity_0  Nuvio:relevantIndividual  ?FrequencyShiftKeyingModulation_0
                { ?FrequencyShiftKeyingModulation_0
                            a                     RFDevice:FrequencyShiftKeyingModulation
                }
              }
            { ?Value_0  Nuvio:hasValue  ?Entity_0 }
          }
        }
      }
  }
