PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    OPTIONAL
      { ?Transceiving_0
                  RFDevice:supportsTuning  ?Half_DuplexCommunicationsSystem_0
        { ?Transceiving_0
                    a                     RFDevice:Transceiving
          OPTIONAL
            { ?Transceiving_0
                        a                     Nuvio:Process .
              ?Attribute_0  Nuvio:hasProcessQuality  ?Transceiving_0
              { ?Attribute_0  a                 Nuvio:Attribute }
            }
        }
      }
  }
