PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RFSystem_0
WHERE
  { ?RFSystem_0  a                  RFDevice:RFSystem
    { ?RFSystem_0  RFDevice:isProducerOf  ?Entity_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_0  a                    RFDevice:ElectricChargeUnit
          { ?Entity_0  a                    Nuvio:Value .
            RFDevice:MilliampereHour
                      Nuvio:hasUnitOfMeasure  ?Entity_0
            { ?Var0  Nuvio:hasValue  ?Entity_0
              { ?FrequencyUnit_0
                          Nuvio:hasUnitOfMeasure  ?Var0
                { ?FrequencyUnit_0
                            a                     RFDevice:FrequencyUnit
                }
              }
            }
          }
        }
      }
    }
  }
