PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN200_0
WHERE
  { ?USRPN200_0  a                  SDR:USRPN200
    { ?Entity_0  RFDevice:hasVoltage  ?USRPN200_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_0  a                    RFDevice:DeceptiveJamming
          { ?Entity_0  a                    Nuvio:InformationEntity
            { ?Entity_0  a                    Nuvio:Situation .
              ?ElectricChargeUnit_0
                        Nuvio:relevantIndividual  ?Entity_0
              { ?Entity_0  Nuvio:relevantIndividual  ?NoiseJamming_0
                { ?NoiseJamming_0
                            a                     RFDevice:NoiseJamming
                  { ?NoiseJamming_0
                              RFDevice:hasPulseRepetitionFrequency  ?Quantity_0
                    { ?Quantity_0  a                  Nuvio:Quantity }
                  }
                }
              }
            }
          }
          { SDR:Length_83_3mm
                      RFDevice:hasWidth  ?Entity_0
          }
        }
      }
    }
  }
