PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX310_0
WHERE
  { ?USRPX310_0  a                  SDR:USRPX310
    OPTIONAL
      { ?Entity_0  RFDevice:isDeployedOn  ?USRPX310_0
        { ?Process_0  Nuvio:isExpressedBy  ?Entity_0
          OPTIONAL
            {   { ?Entity_0  RFDevice:hasDoubleValue  ?DataValue0
                  FILTER ( ?DataValue0 <= "73.48361"^^xsd:double )
                }
              UNION
                { ?Entity_0  a                    Nuvio:UnitOfMeasure }
            }
        }
      }
  }
