PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SearchRadar_0
WHERE
  { ?SearchRadar_0
              a                     RFDevice:SearchRadar
    { ?Var0  RFDevice:hasCapability  ?SearchRadar_0
      { ?Entity_0  RFDevice:hasBandwidthRange  ?Var0
        { ?InformationEntity_0
                    Nuvio:expresses  ?Entity_0
          { ?Entity_0  a                    RFDevice:WhipAntenna
            {   { ?Entity_0  a                    Nuvio:Object .
                  ?AnalogModulation_0
                            Nuvio:participatesIn  ?Entity_0
                  { ?AnalogModulation_0
                              a                     RFDevice:AnalogModulation
                  }
                }
              UNION
                { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                  FILTER ( ?DataValue0 > 212519808 )
                  { ?Entity_0  a                    RFDevice:TimeInterval }
                }
            }
            { ?Entity_0  a                    Nuvio:InformationEntity }
          }
        }
      }
    }
  }
