PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CommunicationsSystem_0
WHERE
  { ?CommunicationsSystem_0
              a                     RFDevice:CommunicationsSystem
    { ?CommunicationsSystem_0
                Nuvio:partOf  ?Receiver_0
      { ?Receiver_0  a                  RFDevice:Receiver
        { ?XC3SD1800AFPGA_0
                    Nuvio:compositeOf  ?Receiver_0
          { ?XC3SD1800AFPGA_0
                      a                     SDR:XC3SD1800AFPGA
            { ?XC3SD1800AFPGA_0
                        RFDevice:hasProducer  ?Var0
            }
          }
        }
      }
    }
  }
