PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  sf:   <http://www.opengis.net/ont/sf#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?Entity_0  RFDevice:hasProducer  ?ElectronicAttackSystem_0
      {   { ?Entity_0  a                    Nuvio:Entity .
            ?Object_0  Nuvio:isExpressedBy  ?Entity_0
          }
        UNION
          { ?Entity_0  a                    sf:MultiCurve
            { ?Entity_0  Nuvio:hasValue  ?Var0
              { ?Var0  RFDevice:hasDoubleValue  ?DataValue0
                FILTER ( ?DataValue0 >= -52.91 )
                { ?Var0  RFDevice:hasNonNegativeIntegerValue  ?DataValue1
                  FILTER ( ?DataValue1 > 228502431 )
                }
              }
            }
          }
        OPTIONAL
          { ?Object_0  a                    Nuvio:Object .
            ObjectDescription:Instance1251
                      Nuvio:participatesIn  ?Object_0
          }
      }
    }
  }
