PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB2xx_0
WHERE
  { ?USRPB2xx_0  a                  SDR:USRPB2xx
    { ?Var0  RFDevice:supportsSpectrumSensing  ?USRPB2xx_0
      { ?Process_0  Nuvio:isExpressedBy  ?Var0
        {   { ?Var0  Nuvio:hasPrecision  ?DataValue0
              FILTER ( ?DataValue0 >= -505300560 )
              { ?Var0  a                     RFDevice:Length }
            }
          UNION
            { ?Var0  Nuvio:relevantIndividual  ObjectDescription:Instance1027 }
          { ?Process_0  a                   Nuvio:Process .
            ObjectDescription:AntennaPolarization_instance3
                      Nuvio:hasProcessQuality  ?Process_0
          }
        }
        { ?Var0  a                     RFDevice:SelfProtectionJamming }
      }
    }
  }
