PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicSupportSystem_0
WHERE
  { ?ElectronicSupportSystem_0
              a                     RFDevice:ElectronicSupportSystem
    { ?Entity_0  RFDevice:hasCapability  ?ElectronicSupportSystem_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?Value_0  Nuvio:isExpressedBy   ?Entity_0
        { ?Entity_0  a                    RFDevice:FrequencyShiftKeyingModulation
          { ?Entity_0  a                    RFDevice:SpatialAreaUnit }
          { ?Entity_0  a                    Nuvio:UnitOfMeasure }
        }
        { ?Value_0  a                     Nuvio:Value ;
                    Nuvio:hasUnitOfMeasure  ?WeightUnit_0
          { ?Value_0  Nuvio:hasPrecision  ?DataValue0
            FILTER ( ?DataValue0 >= 2078869797 )
          }
        }
      }
    }
  }
