PREFIX  sf:   <http://www.opengis.net/ont/sf#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarSystem_0
WHERE
  { ?RadarSystem_0
              a                     RFDevice:RadarSystem
    { ?RadarSystem_0
                Nuvio:partOf  ?Entity_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?Object_0  Nuvio:isExpressedBy  ?Entity_0
        { ?Entity_0  a                    sf:PolyhedralSurface
          { ?Entity_0  a                    RFDevice:Moving }
          { ?Entity_0  a                    RFDevice:SpatialUnit
            { ?Entity_0  a                    RFDevice:AntennaPolarization
              OPTIONAL
                { ?Entity_0  a                    Nuvio:UnitOfMeasure }
            }
          }
        }
      }
    }
  }
