PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    OPTIONAL
      { ?Half_DuplexCommunicationsSystem_0
                  RFDevice:isDeployedOn  ?Entity_0
        { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
          FILTER ( ?DataValue0 <= -624902454 )
          {   { ?Entity_0  a                    Nuvio:Situation .
                ?LatitudeValueInRadian_0
                          Nuvio:relevantIndividual  ?Entity_0
                { ?ElectronicSupportSystem_0
                            Nuvio:relevantIndividual  ?Entity_0
                  { ?ElectronicSupportSystem_0
                              a                     RFDevice:ElectronicSupportSystem
                  }
                }
              }
            UNION
              { ?LatitudeValueInRadian_0
                          a                     RFDevice:LatitudeValueInRadian
                { ?LatitudeValueInRadian_0
                            Nuvio:hasPrecision  ?DataValue1
                  FILTER ( ?DataValue1 = 1690556085 )
                }
              }
          }
        }
      }
  }
