PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Half_DuplexCommunicationsSystem_0
                Nuvio:partOf  ?RadarJammer_0
      { ?RadarJammer_0
                  a                     RFDevice:RadarJammer
        { ?SweepJamming_0
                    RFDevice:supportsTuning  ?RadarJammer_0
          { ?SweepJamming_0
                      a                     RFDevice:SweepJamming
          }
        }
      }
    }
  }
