PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?TrackingRadar_0
WHERE
  { ?TrackingRadar_0
              a                     RFDevice:TrackingRadar
    { ?TrackingRadar_0
                Nuvio:partOf  ?Entity_0
      {   { ?Entity_0  a                    Nuvio:Entity .
            ?Situation_0  Nuvio:isExpressedBy  ?Entity_0
          }
        UNION
          {   { ?Entity_0  a                    Nuvio:Attribute
                { ?DRFMJamming_0
                            RFDevice:supportsSpectrumSensing  ?Entity_0
                }
              }
            UNION
              { ?Situation_0  Nuvio:relevantIndividual  ?PolynomialSpline_0 }
          }
      }
    }
  }
