PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?GNURadio_0
WHERE
  { ?GNURadio_0  a                  SDR:GNURadio
    { ?Entity_0  RFDevice:hasProducer  ?GNURadio_0
      { ?Value_0  Nuvio:isExpressedBy  ?Entity_0
        {   { ?Entity_0  a                    RFDevice:DataSize }
          UNION
            { ?Var0  Nuvio:hasValue  ?Entity_0
              { ?Var0  RFDevice:hasFloatValue  ?DataValue0
                FILTER ( ?DataValue0 < 596041190 )
              }
            }
        }
        { ?Value_0  Nuvio:hasUnitOfMeasure  ?Process_0
          { ?Value_0  Nuvio:hasPrecision  ?DataValue1
            FILTER ( ?DataValue1 < 8554853 )
          }
          { ?Process_0  a                   Nuvio:Process }
        }
      }
    }
  }
