PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?Entity_0  RFDevice:isProducerOf  ?SurveillanceRadar_0
      { ?Entity_0  a                    RFDevice:VoltageUnit
        { ?Entity_0  a                    RFDevice:AntennaPolarization
          { ?Entity_0  Nuvio:informationSource  ?Var0
            { ?Var0  a                     RFDevice:PowerRange
              { ?FrequencyScanRate_0
                          RFDevice:hasMax  ?Var0
                { ?Var1  Nuvio:hasValue  ?FrequencyScanRate_0
                  { ?Var1  Nuvio:hasDataValue  ?DataValue0
                    FILTER ( ?DataValue0 = 883046908 )
                  }
                }
              }
            }
          }
        }
      }
    }
  }
