PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CR_0
WHERE
  { ?CR_0  a                     SDR:CR
    { ?Object_0  RFDevice:hasProducer  ?CR_0
      { ?CommunicationsJamming_0
                  Nuvio:participatesIn  ?Object_0
        { ?CommunicationsJamming_0
                    a                     RFDevice:CommunicationsJamming
          { ?Entity_0  RFDevice:hasEffectiveRadiatedPower  ?CommunicationsJamming_0
            { ObjectDescription:LatitudeValueInDegree_instance0
                        Nuvio:hasValue  ?Entity_0
            }
          }
        }
      }
    }
  }
