PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarWarningReceiver_0
WHERE
  { ?RadarWarningReceiver_0
              a                     RFDevice:RadarWarningReceiver
    OPTIONAL
      { ?RadarWarningReceiver_0
                  RFDevice:isProducerOf  ?Object_0
        { ?Entity_0  Nuvio:hasObjectQuality  ?Object_0
          { ?Entity_0  a                    Nuvio:Entity ;
                      Nuvio:isExpressedBy   ?Entity_0
            {   { ?Entity_0  a                    Nuvio:Attribute }
              UNION
                { ?Entity_0  Nuvio:hasValue  ?Var0 }
            }
          }
        }
      }
  }
