PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarWarningReceiver_0
WHERE
  { ?RadarWarningReceiver_0
              a                     RFDevice:RadarWarningReceiver
    OPTIONAL
      { ?Entity_0  RFDevice:supportsSpectrumSensing  ?RadarWarningReceiver_0
        {   { ?Entity_0  a                    Nuvio:Entity .
              ?InformationContent_0
                        Nuvio:isExpressedBy   ?Entity_0
              OPTIONAL
                { ?Entity_0  a                    RFDevice:LongitudeValue
                  { ?Entity_0  a                    Nuvio:Process }
                }
            }
          UNION
            { ?InformationContent_0
                        a                     Nuvio:InformationContent .
              ?InformationRepresentation_0
                        Nuvio:representedBy   ?InformationContent_0
              { ?InformationRepresentation_0
                          a                     Nuvio:InformationRepresentation .
                ?Entity_1  Nuvio:representedBy  ?InformationRepresentation_0
              }
            }
        }
      }
  }
