PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX3xx_0
WHERE
  { ?USRPX3xx_0  a                  SDR:USRPX3xx
    { ?Var0  RFDevice:hasCapability  ?USRPX3xx_0
      { ?Var1  RFDevice:hasEffectiveRadiatedPower  ?Var0
        { ?Var2  Nuvio:hasValue  ?Var1
          OPTIONAL
            { ?Var1  a                     RFDevice:Power }
        }
        { ?Attribute_0  RFDevice:hasTransmitPowerRange  ?Var0
          { ?Attribute_0  a                 Nuvio:Attribute }
        }
      }
    }
  }
