PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE3xx_0
WHERE
  { ?USRPE3xx_0  a                  SDR:USRPE3xx
    { ?Var0  RFDevice:supportsTuning  ?USRPE3xx_0
      {   { ?Var1  RFDevice:hasTransmitPowerRange  ?Var0
            { ?Var2  Nuvio:hasValue  ?Var1 }
          }
        UNION
          { ?Power_0  RFDevice:hasEffectiveRadiatedPower  ?Var0
            { ?Power_0  Nuvio:hasValue  ?Var3 }
          }
      }
    }
  }
