PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>

SELECT DISTINCT  ?RadarSystem_0
WHERE
  { ?RadarSystem_0
              a                     RFDevice:RadarSystem
    { ?Entity_0  RFDevice:isProducerOf  ?RadarSystem_0
      {   { ?Entity_0  RFDevice:supportsSpectrumSensing  ?PulseRadarModulation_0
            { ?PulseRadarModulation_0
                        a                     RFDevice:PulseRadarModulation
            }
          }
        UNION
          { ?Entity_0  a                    RFDevice:Modulation
            { ?Entity_0  a                    RFDevice:LongitudeValue }
          }
      }
    }
  }
