PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CommunicationsSystem_0
WHERE
  { ?CommunicationsSystem_0
              a                     RFDevice:CommunicationsSystem
    { ?Transmitting_0
                RFDevice:supportsJamming  ?CommunicationsSystem_0
      { ?Attribute_0  Nuvio:hasProcessQuantity  ?Transmitting_0
        { ?Attribute_0  a                 Nuvio:Attribute }
      }
    }
  }
