PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicSupportSystem_0
WHERE
  { ?ElectronicSupportSystem_0
              a                     RFDevice:ElectronicSupportSystem
    { ?Entity_0  Nuvio:aggregateOf  ?ElectronicSupportSystem_0
      { ?Entity_0  a                    Nuvio:Entity ;
                  Nuvio:isExpressedBy   ?Entity_0
        { ?Entity_0  a                    RFDevice:RangeGatePullOffJamming
          { ?Entity_0  a                    RFDevice:Angle
            { ?LongitudeValueInDegree_0
                        Nuvio:hasValue  ?Entity_0
              { ?LongitudeValueInDegree_0
                          a                     RFDevice:LongitudeValueInDegree
                { ?LongitudeValueInDegree_0
                            RFDevice:hasFloatValue  ?DataValue0
                  FILTER ( ( ?DataValue0 >= "-180"^^xsd:decimal ) && ( ?DataValue0 <= "180"^^xsd:decimal ) )
                }
              }
            }
          }
        }
      }
    }
  }
