PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SearchRadar_0
WHERE
  { ?SearchRadar_0
              a                     RFDevice:SearchRadar
    { ?Entity_0  Nuvio:aggregateOf  ?SearchRadar_0
      { ?Entity_0  Nuvio:isExpressedBy  ?Situation_0
        { ObjectDescription:DirectConversionReceiver_instance25
                    Nuvio:compositeOf  ?Entity_0
          { ?Power_0  RFDevice:hasTransmitPowerRange  ?Entity_0
            { ?Power_0  a                     RFDevice:Power }
          }
          { ?Entity_0  a                    RFDevice:Width
            { ?Entity_0  Nuvio:hasValue  ?Var0 }
            OPTIONAL
              { ?Entity_0  a                    Nuvio:Process .
                RFDevice:VerticalPolarization
                          Nuvio:hasProcessQuality  ?Entity_0
              }
          }
        }
        { ?Situation_0  a                 Nuvio:Situation }
      }
    }
  }
