PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SearchRadar_0
WHERE
  { ?SearchRadar_0
              a                     RFDevice:SearchRadar
    { ?Entity_0  RFDevice:hasWeight  ?SearchRadar_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_0  a                    SDR:Spartan6FPGA
          { ?Object_0  RFDevice:hasProducer  ?Entity_0 }
        }
      }
    }
  }
