PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE313_0
WHERE
  { ?USRPE313_0  a                  SDR:USRPE313
    { ?Object_0  RFDevice:hasProducer  ?USRPE313_0
      { ?DRFMJamming_0
                  Nuvio:hasParticipant  ?Object_0
        OPTIONAL
          { ?Entity_0  Nuvio:hasProcessQuantity  ?DRFMJamming_0
            { ?Entity_0  a                    Nuvio:Entity }
          }
      }
    }
  }
