PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { ?Entity_0  RFDevice:hasChargingTime  ?JammingSystem_0
      { ?Entity_0  a                    Nuvio:Entity ;
                  Nuvio:expresses       ?Object_0
        { ?Entity_0  a                    RFDevice:TimeUnit
          OPTIONAL
            { ?Detection_0  Nuvio:subprocessOf  ?Entity_0 }
        }
        { ?Object_0  a                    Nuvio:Object }
      }
    }
  }
