PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ModelX_0
WHERE
  { ?ModelX_0  a                    RFDevice:ModelX
    OPTIONAL
      { ?Var0  RFDevice:supportsSpectrumSensing  ?ModelX_0
        { ?Var0  a                     RFDevice:FixedBandwidthSensing
          { ?Var0  a                     RFDevice:InboundRangeGatePullOffJamming
            OPTIONAL
              { ?Entity_0  Nuvio:isExpressedBy  ?Var0
                { ?Var0  a                     gml:ArcStringByBulge
                  { ?Var0  a                     RFDevice:ElectricCharge }
                }
              }
          }
        }
      }
  }
