PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicSupportSystem_0
WHERE
  { ?ElectronicSupportSystem_0
              a                     RFDevice:ElectronicSupportSystem
    { ?Process_0  RFDevice:supportsTuning  ?ElectronicSupportSystem_0
      { ?FixedBandwidthSensing_0
                  Nuvio:hasSubprocess  ?Process_0
        { ?FixedBandwidthSensing_0
                    a                     RFDevice:FixedBandwidthSensing
        }
      }
    }
  }
