PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SearchRadar_0
WHERE
  { ?SearchRadar_0
              a                     RFDevice:SearchRadar
    { ?SearchRadar_0
                RFDevice:isProducerOf  ?Entity_0
      { ?Entity_0  a                    Nuvio:UnitOfMeasure
        { ?Entity_0  a                    Nuvio:InformationEntity }
        OPTIONAL
          { ?Entity_0  a                    RFDevice:Velocity }
      }
    }
  }
