PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?PulseRadar_0
                RFDevice:isProducerOf  ?Entity_0
      {   { ?Entity_0  Nuvio:expresses  ?Value_0 }
        UNION
          { ?Entity_0  a                    Nuvio:Situation .
            ?USRPN310_0  Nuvio:relevantIndividual  ?Entity_0
            { ?Clothoid_0  Nuvio:relevantIndividual  ?Entity_0
              { ?Clothoid_0  a                  gml:Clothoid }
              { ?USRPN310_0  a                  SDR:USRPN310
                { ?Var0  RFDevice:hasDataTransmissionMode  ?USRPN310_0 }
              }
            }
            OPTIONAL
              {   { ?CyclostationaryDetection_0
                              Nuvio:hasSubprocess  ?Entity_0
                    { ?Entity_0  a                    RFDevice:Percentage
                      OPTIONAL
                        { ?Var1  Nuvio:hasValue  ?Entity_0 }
                    }
                  }
                UNION
                  { ?ContinuousWaveRadarModulation_0
                              RFDevice:hasCapability  ?Entity_0
                  }
              }
          }
        { ?Value_0  a                     Nuvio:Value }
      }
    }
  }
