PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE313_0
WHERE
  { ?USRPE313_0  a                  SDR:USRPE313
    { ?XilinxZynq7000Family_0
                Nuvio:compositeOf  ?USRPE313_0
      { ?XilinxZynq7000Family_0
                  a                     SDR:XilinxZynq7000Family
        { ?XilinxZynq7000Family_0
                    Nuvio:aggregateOf  ?ARMProcessor_0
        }
      }
    }
  }
