PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    OPTIONAL
      { ?RadioComponent_0
                  Nuvio:partOf  ?ElectronicAttackSystem_0
        { ?RadioComponent_0
                    a                     RFDevice:RadioComponent
          { ?Mixer_0  Nuvio:aggregateOf  ?RadioComponent_0
            { ?Mixer_0  a                     RFDevice:Mixer }
          }
        }
      }
  }
