PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ModelX_0
WHERE
  { ?ModelX_0  a                    RFDevice:ModelX
    { ?Entity_0  RFDevice:hasNoiseFigure  ?ModelX_0
      { ?Entity_0  a                    Nuvio:Entity
        OPTIONAL
          {   {   { ?Entity_0  a                    RFDevice:BistaticRadar
                    OPTIONAL
                      { ObjectDescription:Weight_instance47
                                  RFDevice:hasNoiseFigure  ?Entity_0
                      }
                  }
                UNION
                  { ?Entity_0  a                    RFDevice:CommunicationsJamming
                    { ?Attribute_0  RFDevice:hasPulseRepetitionInterval  ?Entity_0
                      { ?Attribute_0  a                 Nuvio:Attribute }
                    }
                  }
              }
            UNION
              { ?Entity_0  a                    Nuvio:Process .
                ObjectDescription:Instance543
                          RFDevice:hasPulseWidth  ?Entity_0
              }
          }
      }
    }
  }
