PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE3xx_0
WHERE
  { ?USRPE3xx_0  a                  SDR:USRPE3xx
    { ?InstantaneousFrequencyMeasurementReceiver_0
                Nuvio:aggregateOf  ?USRPE3xx_0
      { ObjectDescription:RFFrontEnd_instance38
                  Nuvio:partOf  ?InstantaneousFrequencyMeasurementReceiver_0
      }
    }
  }
