PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CR_0
WHERE
  { ?CR_0  a                     SDR:CR
    OPTIONAL
      { ?Entity_0  Nuvio:compositeOf  ?CR_0
        { ?InformationRepresentation_0
                    Nuvio:isExpressedBy  ?Entity_0
          { ?Entity_0  a                    gml:ArcString
            { ?Entity_0  a                    Nuvio:InformationEntity }
            { ?Entity_0  a                    Nuvio:Attribute }
          }
        }
      }
  }
