PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB2xx_0
WHERE
  { ?USRPB2xx_0  a                  SDR:USRPB2xx
    { ?USRPB2xx_0  RFDevice:isProducerOf  ?Entity_0
      {   { ?Entity_0  a                    Nuvio:Entity .
            ?Process_0  Nuvio:isExpressedBy  ?Entity_0
            { ?Entity_0  a                    RFDevice:CommunicationsJamming
              OPTIONAL
                { ?Entity_0  RFDevice:hasDoubleValue  ?DataValue0
                  FILTER ( ?DataValue0 != "56.542313"^^xsd:double )
                }
            }
          }
        UNION
          { ?Process_0  a                   Nuvio:Process }
      }
    }
  }
