PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?JammingSystem_0
WHERE
  { ?JammingSystem_0
              a                     RFDevice:JammingSystem
    { ?Var0  RFDevice:supportsTransmitting  ?JammingSystem_0
      { ?Entity_0  RFDevice:hasFrequencyRange  ?Var0
        { ?Entity_0  a                    Nuvio:Entity .
          ?InformationRepresentation_0
                    Nuvio:isExpressedBy   ?Entity_0
          OPTIONAL
            {   { ?Entity_0  a                    RFDevice:ElectricCharge
                  { ?Entity_0  a                    Nuvio:UnitOfMeasure }
                }
              UNION
                { ?InformationRepresentation_0
                            a                     Nuvio:InformationRepresentation
                }
            }
        }
      }
    }
  }
