PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPX300_0
WHERE
  { ?USRPX300_0  a                  SDR:USRPX300
    OPTIONAL
      { ?Var0  Nuvio:aggregateOf  ?USRPX300_0
        {   { ?Var1  RFDevice:hasResolution  ?Var0 }
          UNION
            {   { ?Var0  a                     RFDevice:ADC }
              UNION
                { ?DirectionalAntenna_0
                            Nuvio:partOf  ?Var0
                  { ?DirectionalAntenna_0
                              a                     RFDevice:DirectionalAntenna
                    { ?Object_0  RFDevice:isProducerOf  ?DirectionalAntenna_0
                      { ObjectDescription:Instance1015
                                  Nuvio:hasParticipant  ?Object_0
                      }
                    }
                  }
                }
            }
        }
      }
  }
