PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?RangeGatePullOffJamming_0
                RFDevice:supportsJamming  ?ElectronicAttackSystem_0
      { ?RangeGatePullOffJamming_0
                  a                     RFDevice:RangeGatePullOffJamming
        { ?Power_0  RFDevice:hasEffectiveRadiatedPower  ?RangeGatePullOffJamming_0
          { ?Power_0  a                     RFDevice:Power }
        }
      }
    }
  }
