PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?Jammer_0  Nuvio:partOf  ?ElectronicAttackSystem_0
      { ?Jammer_0  a                    RFDevice:Jammer
        { ?Entity_0  RFDevice:hasProducer  ?Jammer_0
          { ?Entity_0  a                    Nuvio:Entity ;
                      Nuvio:expresses       ?Object_0
            { ?Object_0  Nuvio:aggregateOf  ?Entity_0
              { ?Entity_0  a                    RFDevice:AutomaticGainControl
                { ?Entity_1  RFDevice:hasMaxOutputPower  ?Entity_0 }
              }
            }
          }
        }
      }
    }
  }
