PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>

SELECT DISTINCT  ?ElectronicSupportSystem_0
WHERE
  { ?ElectronicSupportSystem_0
              a                     RFDevice:ElectronicSupportSystem
    { ObjectDescription:Producer_instance196
                RFDevice:hasProducer  ?ElectronicSupportSystem_0
    }
  }
