PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN310_0
WHERE
  { ?USRPN310_0  a                  SDR:USRPN310
    OPTIONAL
      { ?Var0  Nuvio:compositeOf  ?USRPN310_0
        { ?Var1  RFDevice:hasChargingTime  ?Var0
          { ?Var2  RFDevice:hasHeight  ?Var0 }
        }
      }
  }
