PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?USRPN200_0
WHERE
  { ?USRPN200_0  a                  SDR:USRPN200
    { ?Var0  RFDevice:supportsTuning  ?USRPN200_0
      {   { ?Var0  a                     Nuvio:Entity
            OPTIONAL
              { ?Var0  a                     gml:AbstractCurveSegment }
          }
        UNION
          { ?Var0  a                     RFDevice:Transceiving }
      }
    }
  }
