PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE3xx_0
WHERE
  { ?USRPE3xx_0  a                  SDR:USRPE3xx
    OPTIONAL
      { ?USRPE3xx_0  Nuvio:aggregateOf  ?XilinxZynq7000Family_0
        { ?XilinxZynq7000Family_0
                    a                     SDR:XilinxZynq7000Family
        }
      }
  }
