PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicSupportSystem_0
WHERE
  { ?ElectronicSupportSystem_0
              a                     RFDevice:ElectronicSupportSystem
    { ?Entity_0  RFDevice:hasCapability  ?ElectronicSupportSystem_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?Process_0  Nuvio:expresses     ?Entity_0
        {   { ?Process_0  a                   Nuvio:Process .
              ?Half_DuplexCommunicationsSystem_0
                        Nuvio:participatesIn  ?Process_0
            }
          UNION
            {   { ?Half_DuplexCommunicationsSystem_0
                            a                     RFDevice:Half-DuplexCommunicationsSystem
                }
              UNION
                { ?Var0  RFDevice:supportsTransmitting  ?Half_DuplexCommunicationsSystem_0 }
            }
        }
      }
    }
  }
