PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>

SELECT DISTINCT  ?RadarWarningReceiver_0
WHERE
  { ?RadarWarningReceiver_0
              a                     RFDevice:RadarWarningReceiver
    OPTIONAL
      { ?RadarWarningReceiver_0
                  RFDevice:supportsTuning  ?EmitterIdentification_0
        { ?EmitterIdentification_0
                    a                     RFDevice:EmitterIdentification
        }
      }
  }
