PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB200_0
WHERE
  { ?USRPB200_0  a                  SDR:USRPB200
    OPTIONAL
      { ?Object_0  RFDevice:isProducerOf  ?USRPB200_0
        { ?Object_0  Nuvio:hasObjectQuality  ?Entity_0
          OPTIONAL
            { ?Entity_0  a                    Nuvio:Entity
              { ?Entity_0  a                    RFDevice:LongitudeValueInDegree
                { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                  FILTER ( ?DataValue0 <= -642647483 )
                }
                { ?Entity_0  a                    RFDevice:ElectricCharge
                  { ?Entity_0  a                    Nuvio:Process }
                }
              }
            }
        }
      }
  }
