PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPE310_0
WHERE
  { ?USRPE310_0  a                  SDR:USRPE310
    { ?Var0  RFDevice:supportsTuning  ?USRPE310_0
      {   { ?Var0  a                     RFDevice:CoverPulsesJamming }
        UNION
          { ?Var0  a                     RFDevice:Receiving
            { ?RadarFrequencyBand_0
                        RFDevice:hasFrequencyRange  ?Var0
              { ?RadarFrequencyBand_0
                          a                     RFDevice:RadarFrequencyBand
                { ?Entity_0  RFDevice:hasMax  ?RadarFrequencyBand_0
                  { ?Entity_0  a                    Nuvio:Entity
                    { ?Entity_0  a                    RFDevice:Tuning
                      { ?Entity_0  a                    Nuvio:Value
                        { ?Entity_0  Nuvio:hasPrecision  ?DataValue0
                          FILTER ( ?DataValue0 >= 1624585469 )
                        }
                      }
                    }
                  }
                }
              }
            }
          }
      }
    }
  }
