PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?USRPN200_0
WHERE
  { ?USRPN200_0  a                  SDR:USRPN200
    { ?Entity_0  RFDevice:hasVoltage  ?USRPN200_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_0  a                    gml:OrientableSurface
          { ?Entity_0  a                    RFDevice:DoubleValue
            { ?Entity_0  a                    Nuvio:InformationEntity .
              ObjectDescription:USRPB2xxmini_instance16
                        Nuvio:isExpressedBy   ?Entity_0
            }
          }
        }
      }
    }
  }
