PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarWarningReceiver_0
WHERE
  { ?RadarWarningReceiver_0
              a                     RFDevice:RadarWarningReceiver
    { ?Entity_0  RFDevice:hasProducer  ?RadarWarningReceiver_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?InformationEntity_0
                  Nuvio:isExpressedBy   ?Entity_0
        {   { RFDevice:RadarBand_S
                        RFDevice:hasFrequencyRange  ?Entity_0
            }
          UNION
            {   { ?Entity_0  a                    RFDevice:NonNegativeIntegerValue }
              UNION
                { ?Entity_0  a                    Nuvio:UnitOfMeasure }
            }
        }
      }
    }
  }
