PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CR_0
WHERE
  { ?CR_0  a                     SDR:CR
    { ?IEDJammer_0  Nuvio:compositeOf  ?CR_0
      { ?RadioFrequencyBand_0
                  RFDevice:hasFrequencyAccuracy  ?IEDJammer_0
        { ?RadioFrequencyBand_0
                    a                     RFDevice:RadioFrequencyBand
          { ?Quantity_0  RFDevice:hasMin  ?RadioFrequencyBand_0
            { ?Quantity_0  a                  Nuvio:Quantity }
          }
        }
      }
    }
  }
