PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    { ?IEDJammer_0  Nuvio:partOf  ?Full_DuplexCommunicationsSystem_0
      { ?IEDJammer_0  a                 RFDevice:IEDJammer
        { ?CommunicationsJamming_0
                    RFDevice:supportsTransmitting  ?IEDJammer_0
          { ?CommunicationsJamming_0
                      a                     RFDevice:CommunicationsJamming
            { ?Quantity_0  RFDevice:hasPulseWidth  ?CommunicationsJamming_0 }
          }
        }
      }
    }
  }
