PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicSupportSystem_0
WHERE
  { ?ElectronicSupportSystem_0
              a                     RFDevice:ElectronicSupportSystem
    { ?Entity_0  RFDevice:hasProducer  ?ElectronicSupportSystem_0
      { ?Entity_0  a                    Nuvio:Entity .
        ?Situation_0  Nuvio:expresses   ?Entity_0
        OPTIONAL
          { ?Entity_0  a                    RFDevice:FrequencyScanRate
            { ?Entity_0  Nuvio:hasValue  ?Var0
              { ?UnitOfMeasure_0
                          Nuvio:hasUnitOfMeasure  ?Var0
              }
            }
            { ?Entity_0  a                    Nuvio:Attribute }
            { ?Situation_0  a                 Nuvio:Situation
              { ?Situation_0  Nuvio:relevantIndividual  ObjectDescription:Full-DuplexCommunicationsSystem_instance12 }
            }
          }
      }
    }
  }
