PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    { ?Full_DuplexCommunicationsSystem_0
                Nuvio:aggregateOf  ?Entity_0
      { ?Entity_0  Nuvio:expresses  ?Entity_0
        {   { ?Entity_0  a                    Nuvio:Attribute }
          UNION
            { ?Entity_0  a                    Nuvio:Situation
              { ?Velocity_0  Nuvio:relevantIndividual  ?Entity_0
                { ?Velocity_0  a                  RFDevice:Velocity }
              }
            }
        }
      }
    }
  }
