PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarWarningReceiver_0
WHERE
  { ?RadarWarningReceiver_0
              a                     RFDevice:RadarWarningReceiver
    { ?Entity_0  RFDevice:isProducerOf  ?RadarWarningReceiver_0
      {   { ?InformationEntity_0
                      Nuvio:isExpressedBy  ?Entity_0
          }
        UNION
          { ?Time_0  Nuvio:relevantIndividual  ?Entity_0
            OPTIONAL
              { ?XC6SLX75FPGA_0
                          Nuvio:relevantIndividual  ?Entity_0
                { ?XC6SLX75FPGA_0
                            a                     SDR:XC6SLX75FPGA
                }
                { ?Time_0  a                     RFDevice:Time
                  { ?Time_0  Nuvio:hasValue  ?Var0
                    { ?Var0  RFDevice:hasDecimalValue  ?DataValue0 }
                  }
                }
              }
            { ?Entity_0  Nuvio:hasValue  ?Var1 }
            OPTIONAL
              { ?System_0  Nuvio:isExpressedBy  ?InformationEntity_0
                { ObjectDescription:Satellite_instance1
                            RFDevice:isDeployedOn  ?System_0
                }
              }
          }
      }
    }
  }
