PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    { ?Full_DuplexCommunicationsSystem_0
                Nuvio:partOf  ?Transmitter_0
      { ?Transmitter_0
                  a                     RFDevice:Transmitter
        { ?RadioFrequencyBand_0
                    RFDevice:hasFrequencyAccuracy  ?Transmitter_0
          { ?RadioFrequencyBand_0
                      a                     RFDevice:RadioFrequencyBand
          }
        }
      }
    }
  }
