PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?TrackingRadar_0
WHERE
  { ?TrackingRadar_0
              a                     RFDevice:TrackingRadar
    { ?TrackingRadar_0
                RFDevice:hasCapacity  ?Weight_0
      { ?Weight_0  a                    RFDevice:Weight
        { ?Var0  Nuvio:hasValue  ?Weight_0
          { ?Var0  a                     Nuvio:Entity }
        }
      }
    }
  }
