PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarSystem_0
WHERE
  { ?RadarSystem_0
              a                     RFDevice:RadarSystem
    OPTIONAL
      { ?InstantaneousFrequencyMeasurementReceiver_0
                  Nuvio:partOf  ?RadarSystem_0
        { ?InstantaneousFrequencyMeasurementReceiver_0
                    a                     RFDevice:InstantaneousFrequencyMeasurementReceiver
          { ?Object_0  RFDevice:isProducerOf  ?InstantaneousFrequencyMeasurementReceiver_0
            { ?Object_0  a                    Nuvio:Object .
              ?Attribute_0  Nuvio:hasObjectQuality  ?Object_0
            }
          }
        }
      }
  }
