PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Entity_0  RFDevice:hasProducer  ?Half_DuplexCommunicationsSystem_0
      { ?Entity_0  a                    RFDevice:FrequencyScanRateUnit
        {   { ?Entity_0  a                    RFDevice:Velocity }
          UNION
            { ?Entity_0  Nuvio:hasValue  ?Var0
              { ?Var0  Nuvio:hasDataValue  ?DataValue0 }
            }
          OPTIONAL
            { ?Entity_0  a                    Nuvio:Situation ;
                        Nuvio:relevantIndividual  ?Mixer_0
              { ?Mixer_0  a                     RFDevice:Mixer }
            }
        }
      }
    }
  }
