PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?CR_0
WHERE
  { ?CR_0  a                     SDR:CR
    { ?Jammer_0  Nuvio:aggregateOf  ?CR_0
      {   { ?Jammer_0  a                    RFDevice:Jammer }
        UNION
          { ?RangeGatePullOffJamming_0
                      RFDevice:supportsTransmitting  ?Jammer_0
            { ?RangeGatePullOffJamming_0
                        a                     RFDevice:RangeGatePullOffJamming
            }
          }
      }
    }
  }
