PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Half_DuplexCommunicationsSystem_0
WHERE
  { ?Half_DuplexCommunicationsSystem_0
              a                     RFDevice:Half-DuplexCommunicationsSystem
    { ?Entity_0  RFDevice:hasProducer  ?Half_DuplexCommunicationsSystem_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_0  a                    Nuvio:Attribute
          { ?Entity_0  a                    RFDevice:DecimalValue
            { ?Entity_0  RFDevice:hasDecimalValue  ?DataValue0
              FILTER ( ?DataValue0 = -67.15 )
            }
            {   { ?Entity_0  a                    RFDevice:ElectricCharge }
              UNION
                { ?Var0  Nuvio:hasValue  ?Entity_0 }
            }
            {   { ?Entity_0  a                    Nuvio:Value
                  OPTIONAL
                    { ?Entity_0  Nuvio:hasPrecision  ?DataValue1
                      FILTER ( ?DataValue1 != -269968000 )
                    }
                }
              UNION
                { ?Entity_0  a                    Nuvio:Situation }
            }
          }
        }
      }
    }
  }
