PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription1000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    { ?Var0  RFDevice:supportsTuning  ?Full_DuplexCommunicationsSystem_0
      { ?Var0  RFDevice:hasBandwidth  ObjectDescription:Frequency_instance58
        { ?Entity_0  RFDevice:hasBandwidthRange  ?Var0
          { ?Entity_0  Nuvio:isExpressedBy  ?InformationRepresentation_0
            { ?Entity_0  a                    RFDevice:AngleUnit }
          }
        }
      }
    }
  }
